### DISCUSSION TITLE
Override Enqueuing of `theme.json` CSS Properties

### DISCUSSION THREAD

**Discussion by lukethacoder** [WordPress/gutenberg#39131] [Q&A]
Is there a hook available to override the enqueuing of the `theme.json` based CSS properties into the `<head/>`.

```css
.button:before {
  /* CSS variables don't work within pseudo elements here */
  background-color: var(--wp--preset--color--primary, black);
}
```

The use case here is being able to use the CSS variables within pseudo elements, which doesn't work when they're set on the `<body/>` tag, they need to be set on `:root`. 

If there isn't a way to tap into overriding the functionality, are there (easy-ish) ways to load in the `theme.json` properties manually so they can be set on the `:root` element.
