### DISCUSSION TITLE
How do I disable the .editor-styles-wrapper style that controls the .is-root-container widths?

### DISCUSSION THREAD

**Discussion by andyjamesn** [WordPress/gutenberg#43233] [Q&A]
I am integrating tailwind container widths to Gutenberg and have it working apart from some inline styles.

I want to control the width of the root containers using my container classes and this is overriding it.

```css
.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > :where(:not(.alignleft):not(.alignright)),.editor-styles-wrapper  .block-editor-block-list__layout.is-root-container > :where(:not(.alignleft):not(.alignright)) {
      max-width: revert;
      margin-left: auto !important;
      margin-right: auto !important;
    }
.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > .alignwide,.editor-styles-wrapper  .block-editor-block-list__layout.is-root-container > .alignwide  {
      max-width: 1280px;
    }
.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > .alignfull,.editor-styles-wrapper  .block-editor-block-list__layout.is-root-container > .alignfull {
      max-width: none;
    }
  
.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > .alignleft,.editor-styles-wrapper  .block-editor-block-list__layout.is-root-container > .alignleft {
  float: left;
  margin-inline-start: 0;
  margin-inline-end: 2em;
}
.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > .alignright,.editor-styles-wrapper  .block-editor-block-list__layout.is-root-container > .alignright {
  float: right;
  margin-inline-start: 2em;
  margin-inline-end: 0;
}

.editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper > .aligncenter,.editor-styles-wrapper  .block-editor-block-list__layout.is-root-container > .aligncenter {
  margin-left: auto !important;
  margin-right: auto !important;
}

```

Is there a way to remove this code?
