### DISCUSSION TITLE
How to add CSS variables to .editor-styles-wrapper using javascript?

### DISCUSSION THREAD

**Discussion by haikbvn** [WordPress/gutenberg#46962] [Q&A]
Hello,

How to add CSS variables to .editor-styles-wrapper using javascript?

e.g:

```css
.editor-styles-wrapper {
    --color--primary: #1c6c30;
    --color--secondary: #839681;
}
```

Thanks!
