### DISCUSSION TITLE
How to change the navigation breakpoint for mobile Overlay Menu?

### DISCUSSION THREAD

**Discussion by cawa-93** [WordPress/gutenberg#49572] [Q&A]
Currently Overlay Menu brakepoint is 600px. Is to small for our design. I would like set for it at least 800px. I don't see the corresponding settings in Gutenberg. Therefore, it needs to be redefined somehow by CSS? 🤔

**Comment by t-hamano** [comment]
As far as I know, the only way to do this now is to override the default media queries with CSS.

However, it appears that the introduction of breakpoints (or container queries) is being explored in #45274.

**Reply by cawa-93** [reply]
After experimenting, it doesn't seem possible. WP navigation block have mobile-first layout and switch to desktop layout on 600px or higher. I can't overwrite that rules without patching wp core files.

**Reply by t-hamano** [reply]
Yes, I know that the core breakpoint is mobile first. If your expected breakpoint is greater than that, you would need to counteract those core styles once the screen width is greater than 600px.

To take one selector as an example:

```css
/* Part of the default navigation styles */
.wp-block-navigation__responsive-container-open {
	display: flex;
}

@media (min-width: 600px) {
	.wp-block-navigation__responsive-container-open:not(.always-shown) {
		display: none;
	}
}

/* Reset core style */
@media (min-width: 600px) {
	.wp-block-navigation__responsive-container-open:not(.always-shown) {
		display: flex;
	}
}

/* Apply the core style at 800px again */
@media (min-width: 800px) {
	.wp-block-navigation__responsive-container-open:not(.always-shown) {
		display: none;
	}
}
```
