### DISCUSSION TITLE
Why not have the style engine generate reasonable semantic classes instead of repetitive .wp-container-whatever classes?

### DISCUSSION THREAD

**Discussion by cbirdsong** [WordPress/gutenberg#61417] [Ideas]
In [#41993](https://github.com/WordPress/gutenberg/issues/41993#issuecomment-2097108026), @ramonjd points out that layout classes like `is-vertical` and `is-nowrap` are only generated for backwards compatibility:

https://github.com/WordPress/gutenberg/blob/8dc36f6d30cc163671bdaa33f0656fdfe91f1447/lib/block-supports/layout.php#L739-L744

If this class will be kept indefinitely for backwards compatibility, why not use it? It seems nonsensical to keep a class around forever while ignoring it in favor of outputting the same CSS over and over again under different classes. 

Instead of repeating `flex-direction: column;` inside every `.wp-container-whatever`, the style engine could generate a style for `.is-layout-flex.is-vertical`[^1] the first time it encounters a a block with that layout, and then every subsequent block that needs the class would be good to go. In aggregate, this would make pages require much less generated CSS. 

Here is what the style engine generated for a simple test page with a bunch of different group/row/stack blocks on it: 

```css
.wp-container-core-group-is-layout-2.wp-container-core-group-is-layout-2 {
  justify-content: space-between;
}
.wp-container-core-group-is-layout-5.wp-container-core-group-is-layout-5 {
  flex-wrap: nowrap;
}
.wp-container-core-group-is-layout-6.wp-container-core-group-is-layout-6 {
  flex-wrap: nowrap;
}
.wp-container-core-group-is-layout-7.wp-container-core-group-is-layout-7 {
  flex-wrap: nowrap;
  justify-content: center;
}
.wp-container-core-group-is-layout-8.wp-container-core-group-is-layout-8 {
  flex-wrap: nowrap;
  justify-content: flex-end;
}
.wp-container-core-group-is-layout-9.wp-container-core-group-is-layout-9 {
  flex-wrap: nowrap;
  justify-content: space-between;
}
.wp-container-core-group-is-layout-11.wp-container-core-group-is-layout-11 {
  flex-direction: column;
  align-items: flex-start;
}
.wp-container-core-group-is-layout-12.wp-container-core-group-is-layout-12 {
  flex-direction: column;
  align-items: flex-start;
}
.wp-container-core-group-is-layout-13.wp-container-core-group-is-layout-13 {
  flex-direction: column;
  align-items: center;
}
.wp-container-core-group-is-layout-14.wp-container-core-group-is-layout-14 {
  flex-direction: column;
  align-items: flex-end;
}
.wp-container-core-group-is-layout-16.wp-container-core-group-is-layout-16 {
  flex-wrap: nowrap;
}
.wp-container-core-group-is-layout-17.wp-container-core-group-is-layout-17 {
  flex-wrap: nowrap;
}
.wp-container-core-group-is-layout-18.wp-container-core-group-is-layout-18 {
  flex-wrap: nowrap;
  justify-content: center;
}
.wp-container-core-group-is-layout-19.wp-container-core-group-is-layout-19 {
  flex-wrap: nowrap;
  justify-content: flex-end;
}
.wp-container-core-group-is-layout-20.wp-container-core-group-is-layout-20 {
  flex-wrap: nowrap;
  justify-content: space-between;
}
.wp-container-core-group-is-layout-22.wp-container-core-group-is-layout-22 {
  flex-direction: column;
  align-items: flex-start;
}
.wp-container-core-group-is-layout-23.wp-container-core-group-is-layout-23 {
  flex-direction: column;
  align-items: flex-start;
}
.wp-container-core-group-is-layout-24.wp-container-core-group-is-layout-24 {
  flex-direction: column;
  align-items: center;
}
.wp-container-core-group-is-layout-25.wp-container-core-group-is-layout-25 {
  flex-direction: column;
  align-items: flex-end;
}
.wp-container-core-navigation-is-layout-2.wp-container-core-navigation-is-layout-2 {
  justify-content: flex-start;
}
.wp-container-core-group-is-layout-30.wp-container-core-group-is-layout-30 {
  justify-content: space-between;
}
```

- 2,919 bytes
- 23 rules
- `flex-wrap: nowrap;` repeated 10 times
- `flex-direction: column;` repeated 8 times

If the style engine instead created block-agnostic utility classes, this can be refactored down to simply: 

```css
.is-nowrap {
  flex-wrap: nowrap;
}
.is-layout-flex.is-vertical {
  flex-direction: column;
}

.is-layout-flex.is-content-justification-left {
  justify-content: flex-start;
}
.is-layout-flex.is-content-justification-center {
  justify-content: center;
}
.is-layout-flex.is-content-justification-right {
  justify-content: flex-end;
}
.is-layout-flex.is-content-justification-space-between {
  justify-content: space-between;
}
.is-layout-flex.is-content-justification-stretch {
  justify-content: stretch;
}

.is-layout-flex.is-vertical.is-content-justification-left {
  align-items: flex-start;
}
.is-layout-flex.is-vertical.is-content-justification-center {
  align-items: center;
}
.is-layout-flex.is-vertical.is-content-justification-right {
  align-items: flex-end;
}
.is-layout-flex.is-vertical.is-content-justification-stretch {
  align-items: stretch;
}
```

- 862 bytes
- 13 rules, nothing repeated unnecessarily

That's **70% less CSS** for just a simple test page. Why are these convoluted repetitive classes being generated when there is no custom value entered by the user that would require them?

---

_Related issue: https://github.com/WordPress/gutenberg/issues/54033_

[^1]: I guess it might need to be `.is-layout-flex:where(.is-vertical)` to keep specificity the same between the two layouts.

**Comment by ramonjd** [comment]
Thanks for opening this discussion.

I like the idea of maintaining a set of utility classes and applying them as necessary rather than generating bespoke, unique classnames. 

The unique classnames do serve a purpose as far as I can tell where blocks have unique and specific layout properties. Here's a random dump from a test site:

<details>

<summary>Generated CSS</summary>

```css
.wp-container-core-group-is-layout-1 {
	gap: 4px;
	flex-direction: column;
	align-items: flex-start;
}
.wp-container-core-group-is-layout-2 {
	gap: 24px;
}
.wp-container-core-navigation-is-layout-1 {
	justify-content: flex-end;
}
.wp-container-core-group-is-layout-3 {
	justify-content: space-between;
}
.wp-container-content-9 {
	flex-grow: 1;
}
.wp-container-core-group-is-layout-5 > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
	max-width: 729px;
	margin-left: auto !important;
	margin-right: auto !important;
}
.wp-container-core-group-is-layout-5 > .alignwide {
	max-width: 1200px;
}
.wp-container-core-group-is-layout-5 .alignfull {
	max-width: none;
}
.wp-container-core-group-is-layout-5 > .alignfull {
	margin-right: calc(var(--wp--preset--spacing--40) * -1);
	margin-left: calc(var(--wp--preset--spacing--40) * -1);
}
.wp-container-core-group-is-layout-5 > * {
	margin-block-start: 0;
	margin-block-end: 0;
}
.wp-container-core-group-is-layout-5 > * + * {
	margin-block-start: 71px;
	margin-block-end: 0;
}
```

</details>

I suppose the challenge will be extract common rules and apply classes to blocks - the bepoke layout declarations would still have to live somewhere 🤔
