### ISSUE TITLE
 Editor stylesheet CSS specificity issues

### ISSUE THREAD

**Issue by brettsmason** [WordPress/gutenberg#10067]
**Describe the bug**
Editor stylesheet CSS specificity issues.

**To Reproduce**
1. Add editor stylesheet as per the documentation.
2. Add a basic heading tag eg `h2`
3. An example of the generated style I'm using which works fine:
```
.editor-block-list__block h2 {
   font-size: 2rem;
   line-height: 1.16666667;
}
```
4. The `line-height` rule is being overruled by a few rules in core with higher specificity:
```
.wp-block-heading h1.editor-rich-text__tinymce, .wp-block-heading h2.editor-rich-text__tinymce, .wp-block-heading h3.editor-rich-text__tinymce {
   line-height: 1.4;
}

.editor-rich-text__tinymce.mce-content-body {
    line-height: 1.8;
}
```

**Expected behavior**
Core styles should have less specificity to allow for an easier time adding a comprehensive custom editor stylesheet.

Could the above rules not be written like:
```
.wp-block-heading h1, .wp-block-heading h2, .wp-block-heading h3 {
   line-height: 1.4;
}

.editor-rich-text__tinymce {
    line-height: 1.8;
}
```
This allows the editor stylesheet to correctly trump the core styles.
This is only a brief example, but I'm sure there are others. I'd be happy to list all problematic styles that I find if it helps.

**Additional context**
Gutenberg 3.8 and WordPress 4.9.8

**Comment by designsimply** [comment]
Tested and confirmed with the following steps:

1. Add the following to the theme's functions.php file:

```
add_theme_support( 'editor-styles' );
add_editor_style( 'editor-style.css' );
```
2. Add this to editor-style.css in the theme folder:

```
h2 {
   color: salmon;
   font-size: 4rem;
   line-height: 3;
}
```

**Result:** I expected the line height to be 3 (exaggerated for visibility) and it wasn't.

![screen shot 2018-09-20 at 7 52 19 am](https://user-images.githubusercontent.com/1119271/45823250-85cbfa80-bcaa-11e8-8fe6-f97099020076.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15045&action=edit running WordPress 4.9.8 and Gutenberg 3.9.0-rc.2 using Firefox 62.0 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment]
This issue is great for a specific case and to see if we can improve something by continuing the work started in #9008. There is another issue #9534 which asks for feedback related to styling, and I thought I would point you there in case you would like to contribute to that conversation—which is more about critical thinking on the approach for styling on a more general level.

> I'd be happy to list all problematic styles that I find if it helps.

Thanks! Let's ask about this. @youknowriad, would it help to have more examples here?

**Comment by youknowriad** [comment]
Yes, this is very useful and I expect we polish this over time. Most of these styles can be resolvers by changing the way they are being applied but we need to do these changes with care. A list of specificity issues would be great to have.

@jasmussen might also be interested in this.

**Comment by m-e-h** [comment]
Another unnecessarily specific block is the Code block:

in **block-library/edit-blocks.css** we have:
```
.wp-block-code .editor-plain-text {
    font-family: Menlo,Consolas,monaco,monospace;
    font-size: 14px;
    color: #23282d;
}
```
in **editor/style.css** we have:
```
.gutenberg .editor-plain-text {
    border: none;
    box-shadow: none;
    color: inherit;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
    margin: 0;
    padding: 0;
    width: 100%;
}
``` 
Since `.editor-plain-text` is already set to `inherit` *color, font-family,* and *font-size*, we could probably just add the styles to `.wp-block-code` rather than `.wp-block-code .editor-plain-text`

**Comment by m-e-h** [comment]
```
.editor-block-list__block ul:not(.wp-block-gallery) {
    list-style-type: disc;
}
```
A little less specific would be:
```
.editor-block-list__block ul {
    list-style-type: disc;
}
.editor-block-list__block .wp-block-gallery {
    list-style-type: none;
}
```

**Comment by chrisvanpatten** [comment]
@m-e-h That one in particular has been fixed as of this morning in #10358.

**Comment by celloexpressions** [comment]
This should be considered a blocker for API freeze and 5.0. Theme authors can't effectively implement block and editor style support until CSS specificity requirements can be finalized. This also impacts bundled theme updates, which will set the precedent for theme best practices.

**Comment by nickcernis** [comment]
Specificity issues are also blocking work we're doing to make existing themes Gutenberg-friendly.

We currently have to add more specific rules for editor widths in order to override default editor block styling when using `add_editor_style( 'editor-style.css' );`.

For example, the CSS in the Gutenberg theme support handbook to [change editor width](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor) looks like this:

```CSS
/* Main column width */
body.gutenberg-editor-page .editor-post-title__block,
body.gutenberg-editor-page .editor-default-block-appender,
body.gutenberg-editor-page .editor-block-list__block {
    max-width: 720px;
}

/* Width of "wide" blocks */
body.gutenberg-editor-page .editor-block-list__block[data-align="wide"] {
    max-width: 1080px;
}

/* Width of "full-wide" blocks */
body.gutenberg-editor-page .editor-block-list__block[data-align="full"] {
    max-width: none;
}
```

But this has no effect when using `add_editor_style( 'editor-style.css' );`, as noted in [this closed issue](https://github.com/WordPress/gutenberg/issues/9894#issuecomment-423189558).

We are currently using more specific rules as a workaround (with an extra `.wp-admin` class):

```CSS
body.wp-admin.gutenberg-editor-page .editor-block-list__block,
body.wp-admin.gutenberg-editor-page .editor-default-block-appender,
body.wp-admin.gutenberg-editor-page .editor-post-title__block {
	max-width: 732px;
}
```

**Comment by youknowriad** [comment]
When using `add_editor_style( 'editor-style.css' );` this should be enough:

```css
.wp-block {
	max-width: 732px;
}
```
