### ISSUE TITLE
Add support for page title styles within editor-styles. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#10485]
Theme authors can customize the page title style by enqueuing a stylesheet that includes something like this:

```
.editor-post-title__block .editor-post-title__input {
	font-family: serif;
}
```

However, if their theme is using our auto-injected CSS for `editor-styles` (introduced in #9008), that's not possible. 

It's very likely that theme authors will want the page title font/size to match up with the rest of the text in the editor styles, so we should figure out how to make that possible without enqueueing a second editor stylesheet. 

cc @youknowriad

**Comment by nickcernis** [comment]
This may be solved by https://github.com/WordPress/gutenberg/issues/10067 if `body` is mapped to `.edit-post-visual-editor` (which contains the `.editor-post-title__input` element) instead of `.editor-block-list__block`, which does not).

You would be able to do something like this in editor styles:

```CSS
body .editor-post-title__block .editor-post-title__input {
	font-family: serif;
}
```

And Gutenberg would map it to this, which will affect the page title:

```CSS
.edit-post-visual-editor .editor-post-title__block .editor-post-title__input {
	font-family: serif;
}
```

**Comment by nickcernis** [comment]
Noting this now works for me in the editor stylesheet as of WP 5.0 Beta 3:

```CSS
.editor-post-title__block .editor-post-title__input {
	font-family: serif;
}
```

This can likely be closed as a result.
