### ISSUE TITLE
Emtpy cover block becomes black box in frontend

### ISSUE THREAD

**Issue by Leefke** [WordPress/gutenberg#10854]
**Describe the bug**
If you insert a cover block and don't upload any image or video, it will appear as a black box in the frontend.

**Expected behavior**
If the block in the backend is empty, I would expect the placeholder not to render any content. 

Tested with Gutenberg 4.1 RC 1 + Twenty Seventeen as well as Twenty Nineteen.

<img width="865" alt="gutenberg test_cover block" src="https://user-images.githubusercontent.com/44335851/47265923-d2b42280-d52f-11e8-80d3-030adf922f07.png">

**Comment by draganescu** [comment]
I tested this and was able to reproduce it. @mtias I wonder why don't you consider this a bug? If I add an image and the placeholder is empty nothing is shown on the front end.

**Comment by earnjam** [comment]
You can use the cover block for text with a background color and no image. So we definitely should still render a background color on the front-end even without media. 

In the instance like from #21709, where you insert a cover block, but don't upload any media or select an overlay color, then it falls back to the default, which is black. That is also what is happening here. We should possibly clarify in the placeholder that a black background is selected by default, or else show the sidebar controls the whole time. Right now we aren't rendering them until the user selects media or a color. 

Technically speaking, the black background comes from the `has-background-dim` class. It's adding that if the block has a `dimRatio` of anything other than 0. The default `dimRatio` is 40. So it's appending that class by default. 

We could maybe be smarter about not showing anything if no text is entered ***or*** media is selected. But we still render markup for other "empty"/non-configured blocks (video and image blocks are good examples), so I'm not sure that's the right solution. Even if we stop rendering the background until one is selected, we'd still have a 430px tall empty space. 

I think the solution here is probably to clarify that black is already selected for the user, or else make the default completely transparent and change it to another value once media is selected. 

![image](https://user-images.githubusercontent.com/4267290/81982360-b1c68d00-95ff-11ea-9217-1c34c31aa3cb.png)

![image](https://user-images.githubusercontent.com/4267290/81982581-1386f700-9600-11ea-9eec-baf993261991.png)

**Comment by mtias** [comment]
Yes, it seems like a small side-effect of how the defaults interact when no media or content is set, that's why I removed the "bug" as it's more of a "need clarification". For example, even if we were to say the overlay is completely transparent when showing the placeholder, the front would still render an empty area, which can also be weird. I think perhaps nothing should be rendered if there's no inner content, no media & no user-set color.

**Comment by JappIC** [comment]
I think this may have an easy solution

In my case when I create a new "background block" if I choose a predefined color in the wordpress theme, it is not respected and it looks black because the file "wp-includes / css / dist / block-library / style. min.css "is being called after the style file for gutenberg theme settings.

However, it does respect when I generate a color from the color palette because it generates a style in the html of the "background block"

An easy solution would be to first call the file "wp-includes / css / dist / block-library / style.min.css" and then the style.css of the Gutenberg theme configuration. This way you always respect the customer's customization when using the default theme colors.

![Screenshot_19](https://user-images.githubusercontent.com/3437192/99586001-04ce3200-29df-11eb-897b-55ffe9c09e9f.png)

**Comment by kraftner** [comment]
@JappIC It's not an issue of load order but CSS selector specifity:

`.wp-block-cover.has-background-dim` will always overwrite `.has-verde-background-color`, no matter in which order you load the files.

**Comment by kraftner** [comment]
I think the solutions would be to either

- always show the overlay controls, even without a media set
- set the default `dimRatio` to 0 if there is no image so the `.has-background-dim` class isn't added

**Comment by cebbinger** [comment]
The opacity of `.has-background-dim` is set to `0.5` while no other value is set by the user. While no background media is selected, the user can not choose a different value. As a result, using only background color in a cover block is different from background colors in other blocks, like groups. In my opinion that's unintuitive if not a bug.

Since this problem only occurs when no media is selected, I'm currently using this workaround to reset the background opacity to 1:

```css
.wp-block-cover-image:not([style*="background-image:url"]).has-background-dim:not(.has-background-gradient)::before,
.wp-block-cover-image:not([style*="background-image:url"]) .wp-block-cover__gradient-background,
.wp-block-cover:not([style*="background-image:url"]).has-background-dim:not(.has-background-gradient)::before,
.wp-block-cover:not([style*="background-image:url"]) .wp-block-cover__gradient-background {
  opacity: 1;
}
```

Unfortunately this breaks video backgrounds as they have no `background-image` applied. In order to make video backgrounds work with this workaround, we need to put the full opacity colored layer under the video and then dim the video:

```css
video.wp-block-cover__video-background {
  z-index: 1;
}

/* Repeat for 10, 20, …, 100 */
.wp-block-cover-image.has-background-dim.has-background-dim-10 video.wp-block-cover__video-background,
.wp-block-cover.has-background-dim.has-background-dim-10 video.wp-block-cover__video-background {
  opacity: .9;
}
```
