### ISSUE TITLE
Media & Text block: remove inline styles

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#11268]
## Is your feature request related to a problem? Please describe
In Media & Text block user can resize the image but it uses inline styles for styling: 

```html
<div class="wp-block-media-text alignwide" style="grid-template-columns:37% auto;">
```

Like in any other blocks we should not use inline styles. 

In this case it locks using CSS Grid and two columns, and behaviour is hard to overwrite with own styles. Nothing wrong with CSS Grid, I use it myself.

Here is one example when using alignfull and setting the actual content the same width as "alignwide".

### Screenshot without inline styles (no resizing yet)

<img width="1408" alt="media and text block, no inline styles. All is good, image on the left, text on the right" src="https://user-images.githubusercontent.com/1820415/47748282-1ecf3780-dc93-11e8-8b0a-71c7028f8e2b.png">

### Styles

```css
.wp-block-media-text.alignfull {
   grid-template-areas: "media-text-start media-text-media media-text-content media-text-end";
   grid-template-columns: auto minmax(0, 22rem) minmax(0, 22rem) auto;
}
```

Note that trick is using four columns now.

### Screenshot with inline styles `grid-template-columns:37% auto`

<img width="1422" alt="media and text block with inline styles breaks the layout" src="https://user-images.githubusercontent.com/1820415/47748587-cf3d3b80-dc93-11e8-9a9d-ad36479936db.png">

Could be hard to see from the image but it basically breaks the layout. 

Even bigger issue is that in the editor **I can't resize the image at all with my custom styles**.

## Describe the solution you'd like
Have bock setting to set 4-5 "steps" for image width, and use conditional classes like on every other block so far.

## Describe alternatives you've considered
Remove re-sizing feature and inline styles. It doesn't give theme authors freedom to do what they want.
