### ISSUE TITLE
Gutenberg frontend style.css has admin CSS

### ISSUE THREAD

**Issue by jdevalk** [WordPress/gutenberg#11668]
**Describe the bug**
On the frontend, every site with Gutenberg gets `block-library/style.css` loaded. That file contains CSS that is meant for the backend, like this:

```css
@keyframes fade-in{
    0%{
        opacity:0
    }
    to{
        opacity:1
    }
}
@keyframes editor_region_focus{
    0%{
        box-shadow:inset 0 0 0 0 #33b3db
    }
    to{
        box-shadow:inset 0 0 0 4px #33b3db
    }
}
@keyframes rotation{
    0%{
        transform:rotate(0deg)
    }
    to{
        transform:rotate(1turn)
    }
}
@keyframes modal-appear{
    0%{
        margin-top:32px
    }
    to{
        margin-top:0
    }
}
```

**To Reproduce**
1. Go to https://joost.blog
2. View the source, find `block-library/style.css`
3. See the above at the top. See that it's not used in that CSS file anywhere.

**Expected behavior**
This should not be included in that CSS file.

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version WP 5.0 beta

**Comment by jdevalk** [comment]
Another bit that clearly doesn't belong in here:

```css
.editor-block-list__layout .reusable-block-edit-panel{
    align-items:center;
    background:#f8f9f9;
    color:#555d66;
    display:flex;
    flex-wrap:wrap;
    font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen-Sans,Ubuntu,Cantarell,Helvetica Neue,sans-serif;
    font-size:13px;
    position:relative;
    top:-14px;
    margin:0 -14px -14px;
    padding:8px 14px
}
.editor-block-list__layout .editor-block-list__layout .reusable-block-edit-panel{
    margin:0 -14px;
    padding:8px 14px
}
.editor-block-list__layout .reusable-block-edit-panel .reusable-block-edit-panel__spinner{
    margin:0 5px
}
.editor-block-list__layout .reusable-block-edit-panel .reusable-block-edit-panel__info{
    margin-right:auto
}
.editor-block-list__layout .reusable-block-edit-panel .reusable-block-edit-panel__label{
    margin-right:8px;
    white-space:nowrap;
    font-weight:600
}
.editor-block-list__layout .reusable-block-edit-panel .reusable-block-edit-panel__title{
    flex:1 1 100%;
    font-size:14px;
    height:30px;
    margin:4px 0 8px
}
.editor-block-list__layout .reusable-block-edit-panel .components-button.reusable-block-edit-panel__button{
    flex-shrink:0
}
@media (min-width:960px){
    .editor-block-list__layout .reusable-block-edit-panel{
        flex-wrap:nowrap
    }
    .editor-block-list__layout .reusable-block-edit-panel .reusable-block-edit-panel__title{
        margin:0
    }
    .editor-block-list__layout .reusable-block-edit-panel .components-button.reusable-block-edit-panel__button{
        margin:0 0 0 5px
    }
}
.editor-block-list__layout .reusable-block-indicator{
    background:#fff;
    border-left:1px dashed #e2e4e7;
    color:#555d66;
    border-bottom:1px dashed #e2e4e7;
    top:-14px;
    height:30px;
    padding:4px;
    position:absolute;
    z-index:1;
    width:30px;
    right:-14px
}
```

All of this seems editor CSS to me.
