### ISSUE TITLE
CSS should not use :not

### ISSUE THREAD

**Issue by jdevalk** [WordPress/gutenberg#11677]
Currently, we have a lot of CSS that is very non-performant, but also not very readable. Specifically, I think we shouldn't use `:not` as much, in things like:

```css
.wp-block-button__link:not(.has-background):active
```
and
```css
.wp-block-button__link:not(.has-text-color),.wp-block-button__link:not(.has-text-color):active,.wp-block-button__link:not(.has-text-color):focus,.wp-block-button__link:not(.has-text-color):hover{
    color:#fff
}
```
This is very slow for browsers to parse, but they're also very hard to read. Our example CSS is going to be built upon a lot, so it needs to be a bit better.
