### ISSUE TITLE
Innerblocks Should Be Friendly to Flex

### ISSUE THREAD

**Issue by rogerlos** [WordPress/gutenberg#11888]
Every use-case for `InnerBlocks` that I have--and whether this is shared by users as a whole remains to be seen, I guess--involves wrapping the blocks added in the `InnerBlocks` container and then using `flex` attributes to position them.

This is "easy enough" to do on the front end...but it's a lot trickier in the editor. Because `InnerBlocks.Content` (inexplicably, to me) doesn't automatically wrap the child blocks in `save` (and `edit`!), the developer ends up adding a wrapper around `InnerBlocks`, and makes that wrapper a flex container. 

(In my "section" block, which sets up a sidebar-like box, which can be filled with another custom block that is essentially the "Feature a Page Widget" widget on steroids, the wrapper has a class set based on select control in the "section" block inspector, plus a cajillion background options, hence some code you see below.)
 
```javascript
save: function( props ) {
    return(
        el(
            'div',
            {
                className: 'my-section',
                style: function_to_render_background_style( props.backgroundObject )
            }, 
            function_to_render_optional_title( props.title ),
            el(
                'div',
                { className: 'my-flex-wrapper my-flex-' + props.cols + '-column' },
                el(
                   InnerBlocks.Content
                )
            )
        )
    )
}
```
The HTML ends being something like:
```html
<div class="my-section" style="background-color: #000000">
    <p class="my-section-title">Someone Added a Title</p>
    <div class="my-flex-wrapper my-flex-two-column">
        <div class="steroid-clone">...</div>
        <div class="steroid-clone">...</div>
        <div class="steroid-clone">...</div>
        <div class="steroid-clone">...</div>
    </div>
</div>
```

The CSS for the flex part of the front end is pretty standard stuff, ignoring media queries and a million other things:
```scss
.my-flex-wrapper {
    display: flex;
    flex-wrap: wrap;
    > * {
        flex-grow: 0;
        flex-shrink: 0;
        margin: 0 0 5% 0;
    }
    &.my-flex-one-column {
        > * {
            flex-basis: 100%;
            min-width: 100%;
            width: 100%;
        }
    }
    &.my-flex-two-column {
        > * {
            flex-basis: 47.5%;
            min-width: 47.5%;
            width: 47.5%;
            margin-right: 5%;
            &:nth-of-type(2n) {
                margin-right: 0;
            }
        }
    }
}
```
**So we're finally at my issue:** because of the (unavoidable) div soup which is the editor, this is the styling adjustment you need to display the "section" children properly in a WYSIWYG way:
```scss
.edit-post-visual-editor {
    .my-section {
        .my-flex-wrapper {
            /* unset the wrapper flex */
            display: block; 
            .editor-inner-blocks {
                > .editor-block-list__layout {
                    /* set the wrapper flex _here_ */
                    display: flex; 
                    flex-wrap: wrap;
                    > .wp-block > .editor-block-list__block-edit > div > * {
                        /* "un-setting" the inner blocks items in a reliable way
                           Ensures they're full-width in their Gutenberg editor bucket */
                        min-width: 100%;
                        width: 100%;
                        margin-right: 0;
                    }
                }
            }
            &.my-flex-one-column {
                .editor-inner-blocks {
                    > .editor-block-list__layout {
                        > * {
                            /* Set Gutenberg item flex properties here */
                            flex-basis: 100%;
                            min-width: 100%;
                            width: 100%;
                        }
                    }
                }
            }
            &.my-flex-two-column {
                .editor-inner-blocks {
                    > .editor-block-list__layout {
                        > * {
                            /* Set Gutenberg item flex properties here */
                            flex-basis: 47.5%;
                            min-width: 47.5%;
                            width: 47.5%;
                            margin-right: 5%;
                            &:nth-of-type(2n) {
                                margin-right: 0;
                            }
                        }
                    }
                }
            }
        }
    }
}
```
I think this style adjustment should be automatically handled by Gutenberg:

- It makes sense; if a user sets a flex style on an element, a truly WYSIWYG editor would be able to parse it
- The editor-adjusting CSS is inherently fragile; if y'all change the structure of the editor, or the innerblocks rendering method, the style adjustments can fail
- It's something which may need to be applied many times in a stylesheet; imagine I didn't have one block which used `InnerBlocks`, but a few of them, all of which use `flex`
- DRY: this adjustment is consistent in the context of `InnerBlocks.Content` and `InnerBlocks` rendering in general. I can easily picture thousands-of-characters of CSS in a complex near-future site solely dedicated to sorting out `flex` containers in the editor, which shouldn't be necessary.

This is made more difficult by the (to me) weird decision to not have `InnerBlocks` automatically wrap its children on the front end, and allow passing in the `className`, `tagName`, `style`, etc to that wrapper (or even a `noWrap` attribute for those who don't want it. The editor creates that wrapper! It's just not present on the front end, forcing an extra element in rendering functions, and making solving this more difficult. (i.e., you could require the auto-wrapper to be the flex container, making it easy to search for flex styling rules.).
