### ISSUE TITLE
Block mover hidden when left or right aligned

### ISSUE THREAD

**Issue by michealengland** [WordPress/gutenberg#12736]
**Describe the bug**
Left or right aligned blocks may have hidden move controls if it floated. This looks intentionally added in https://github.com/WordPress/gutenberg/pull/10085.

Could be related to https://github.com/WordPress/gutenberg/issues/12290

![pull quote test](https://user-images.githubusercontent.com/25035900/49702763-d70ccb80-fbc1-11e8-9b9a-4e47ad69f8cb.gif)

**To Reproduce**
1. Create a pull quote block.
2. Left or right align the pull quote block.
3. Attempt to drag or move the pull quote block.

**Expected behavior**
Expected the mover controls to be visible when hovering over the pull quote block.

**Screenshots**

<img width="782" alt="screen shot 2018-12-09 at 2 45 30 pm" src="https://user-images.githubusercontent.com/25035900/49702781-120eff00-fbc2-11e8-8bfe-4ffcdb322bf1.png">

# Initial Investigation

* While a non floated block pull-quote has a class="editor-block-mover is-visible" the block controls display as expected.
* While a pull quote block is floated left or right and has class="editor-block-mover is-visible" the block move controls are hidden. This is caused by an overflow on the parent container.

```scss
//editor/style.css line 349
.editor-block-list__layout .editor-block-list__block[data-align="left"] .editor-block-mover, .editor-block-list__layout .editor-block-list__block[data-align="left"] .editor-block-list__block-mobile-toolbar, .editor-block-list__layout .editor-block-list__block[data-align="right"] .editor-block-mover, .editor-block-list__layout .editor-block-list__block[data-align="right"] .editor-block-list__block-mobile-toolbar {
    display: none;
}
```

Turning off display none will display the block menu controls. However, the controls disappear while visible for the paragraph block that the pull quote is floated around.

You can get the block working properly again by changing `left: -30px` to `left: 0;'. However, the movement controls will display in an awkward place.

<img width="322" alt="screen shot 2018-12-09 at 3 03 29 pm" src="https://user-images.githubusercontent.com/25035900/49702905-e42aba00-fbc3-11e8-8116-2c2fb5055a1f.png">

```scss
.editor-block-list__block > .editor-block-mover {
    padding-right: 2px;
    // left: -30px;
    left: 0; // moves the block back in the container.
    display: none;
}
```
