### ISSUE TITLE
.has-vivid-cyan-blue-background-color.has-vivid-cyan-blue-background-color

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#12986]
```
.has-vivid-cyan-blue-background-color.has-vivid-cyan-blue-background-color {
    background-color: #0693e3;
}
```

The selector is duplicated in /wp-includes/css/dist/block-library/style.css. It should not be.

**Comment by swissspidy** [comment]
Class names are doubled to increase specificity to assure colors take effect over another base class color.

See https://github.com/WordPress/gutenberg/blob/cddee64697706f6b797a9fba39d075eff95ee0b0/packages/block-library/src/style.scss and discussion at #12005.

Certainly looks odd though.

**Comment by manake** [comment]
Ok, I understand but in such case the problem is that https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/ says that

> Themes are responsible for creating the classes that apply the colors in different contexts. Core blocks use “color” and “background-color” contexts.
>
> ```
> .has-strong-magenta-background-color {
>     background-color: #313131;
> }
> 
> .has-strong-magenta-color {
>     color: #f78da7;
> }
> ```

so this instruction is wrong?

**Comment by youknowriad** [comment]
That's a good question, do we still need the duplicate now that we did some work on the CSS specificity? cc @jasmussen @kjellr 

Should we update the docs?

**Comment by jasmussen** [comment]
> do we still need the duplicate now that we did some work on the CSS specificity?

From a quick attempt, we don't: #15104. 

I would very much like a sanity check on that one — it _appears_ to be working as intended in my tests, and from looking at the CSS, the reduced specificity of the button block selector should mean it works as intended. But I would very much like testing regardless, in case I'm missing something obvious.

If it works as I hope it does, I'm very happy that the big PR I struggled with is yielding benefits now!

**Comment by m-e-h** [comment]
> Themes are responsible for creating the classes that apply the colors in different contexts. Core blocks use “color” and “background-color” contexts.

The docs seem correct to me. I'm not sure what theme-created classes have to do with the specificity of the core color classes.

> do we still need the duplicate

Pretty sure we do. see https://github.com/WordPress/gutenberg/pull/15104#issuecomment-485537638
It's likely the extra specificity will always be needed here. I don't think it's a bad thing though.

I'm thinking this has more to do with the confusion that duplicate classes might cause?

If so, there are other ways to add specificity. The duplicate classes seemed like the best option to me.
Here are some other options:

### Single class
```css
/* specificity = 10 */
.has-luminous-vivid-amber-color {
	color: #fcb900;
}
```

- Not strong enough to handle link states etc.

### Duplicate class
```css
/* specificity = 20 */
.has-luminous-vivid-amber-color.has-luminous-vivid-amber-color {
	color: #fcb900;
}
```

- It can be used anywhere in the document
- Specificity can be increased at any time by adding the class again.
- Can be confusing for those not familiar with this browser spec.

### :root qualifier
```css
/* specificity = 20 */
:root .has-luminous-vivid-amber-color {
	color: #fcb900;
}
```
_This is my method of choice for personal projects._

- It can be used anywhere in the document
- Specificity can be increased by stacking `:root` selectors together. ie `:root:root`.
- I'm guessing this won't work with the `editor-styles` morphing.

### :not() qualifier
```css
/* specificity = 20 */
:not(.anythingWorks) .has-luminous-vivid-amber-color {
	color: #fcb900;
}
```
- It can be used anywhere in the document
- Not scalable. If, in the future, specificity needs strengthened we'll need to resort to one of the methods above because stacking `:not()` only counts the specificity of the strongest `:not`.

### Parent class qualifier
```css
/* specificity = 20 */
.wp-block-button .has-luminous-vivid-amber-color,
.wp-block-pullquote .has-luminous-vivid-amber-color {
	color: #fcb900;
}
```

- Not scalable. Will need to create a new selector for additional uses.
- If, in the future, specificity needs strengthened we'll need to resort to one of the methods above.
- Imposible to tell by looking at the code if there's a reason for the nesting other than specificity. _"Will something break if I use this class outside of wp-block-button?"_

### Element qualifier
```css
/* specificity = 11 */
a.has-luminous-vivid-amber-color,
blockquote.has-luminous-vivid-amber-color {
	color: #fcb900;
}
```

- Not strong enough
- Not scalable. Will need to create a new selector for additional uses.
- If, in the future, specificity needs strengthened we'll need to resort to one of the methods above.
- Won't always be the correct target in the editor view.
- Imposible to tell by looking at the code if there's a reason for the nesting other than specificity.

### !important
```css
/* specificity = 20 */
.has-luminous-vivid-amber-color {
	color: #fcb900 !important;
}
```

- It can be used anywhere in the document

**Comment by m-e-h** [comment]
I see now what you mean by "updating the docs". I guess they should be updated since copying and pasting what's there now wouldn't work for links.

Pretty sure link pseudo-classes are the only area giving us an issue. So we could always just add those specific pseudo-classes. 

So something like this maybe:
```
.has-luminous-vivid-amber-color,
.has-luminous-vivid-amber-color:link,
.has-luminous-vivid-amber-color:visited {
    color: #fcb900;
}
```

`:link` and `:visited` is just a less verbose version of `:hover`,`:focus`, `:active`, and `:visited`. But the long version could be used too if it's determined `:link` is too obscure here as well.
_Some day we could use [`:any-link`](https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link) to cover all of them but not with IE._

I personally like a higher specificity on every utility class but I also understand keeping things familiar for the average developer. This may be a good compromise. 

What do you think @jasmussen? Wanna try this in https://github.com/WordPress/gutenberg/pull/15104 or are we fine with the duplicate classes?

**Comment by chrisvanpatten** [comment]
> The docs seem correct to me. I'm not sure what theme-created classes have to do with the specificity of the core color classes.

It seems like the problem might be themes that wish to use the core color names, but override the rendered colors.

Not saying that's a good thing — but it seems to be the edge case being solved for.

**Comment by m-e-h** [comment]
Yeah, just now noticed that the example code in the docs didn't match up with the actual code. I could see that causing an issue for some every now and then.

Btw, where you been @chrisvanpatten ?! :smile:

**Comment by jasmussen** [comment]
> What do you think @jasmussen? Wanna try this in #15104 or are we fine with the duplicate classes?

I'm generally fine with whatever solves the problem at hand. 

Though I do think that the following might be much easier to parse:

```
.has-luminous-vivid-amber-color,
.has-luminous-vivid-amber-color:link,
.has-luminous-vivid-amber-color:visited {
    color: #fcb900;
}
```

and I can totally take a stab at that, including updating the docs to match (in a new PR), but before I go about that, is there consensus that this will work for us? You sure `:link` will cover the hover style?

And yes, I think `:link` is easier to parse than the duplicated selector, that really looks like a typo. And if anything, we can just explain what `:link` does in a code comment.

> Some day we could use :any-link to cover all of them but not with IE.

For better or worse, that some day might be [sooner than you think](https://www.theverge.com/2019/3/23/18278465/microsoft-edge-chromium-browser-screenshots-features-hands-on)!

**Comment by kjellr** [comment]
> Though I do think that the following might be much easier to parse:

Just wanted to second this. Since the doubling up of classnames is somewhat rarely seen, I'd support either a re-write along these lines, or just some more explanatory code comments above.

**Comment by chrisvanpatten** [comment]
> Btw, where you been @chrisvanpatten ?! 😄

New job! Still lurking (and reading most tickets) but haven't had as much time to actively contribute. Hoping we start onboarding our platform to Gutenberg later this year so I can get back into it :)

> Though I do think that the following might be much easier to parse:

I really like this solution. It's much more explicit, which is nice!

**Comment by m-e-h** [comment]
> You sure :link will cover the hover style?

Pretty sure.. I mean, it'll definitely count towards the hover style. And it should be the same specificity as what we have now, _20_. 

But I'm wondering, what happens when a theme does something like
```css
.entry a { /* specificity: 11 */ }

.entry a:hover { /* specificity: 21 */ }
```
Maybe something like this would be safer:
```css
.has-luminous-vivid-amber-color,
a.has-luminous-vivid-amber-color:link,
a.has-luminous-vivid-amber-color:visited {
    color: #fcb900;
}
```
That would match the 21 specificity.
