### ISSUE TITLE
Block styles: Make block aware when rendered in styles preview

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#13312]
**Is your feature request related to a problem? Please describe.**

When a block declares `styles`, a "Styles" panel is added to the block sidebar. When this panel is expanded, the block will be rendered in the panel for every style variation that exists.

It appears that blocks are unaware of whether they are rendered as part of the editor or in the styles preview panel. This context may be useful for block authors; it may be desirable for a block to provide an alternate render in the preview panel. Some examples that might benefit from different behavior in the preview panel:

- Blocks that render different image variations by style may not want to render several versions of the same block.
- Blocks that are expensive in terms of network or performance will suffer having their render multiplied by the number of styles the provide.
- An alternative view for the style preview may better describe the block for users. Some blocks are highly visual and can be confusing in the tiny previews.

If the block is aware of rendering in the sidebar, block authors can choose to render alternative output for the preview panel.

**Describe the solution you'd like**

A prop is provided to the block to indicate that it is rendered in the style preview.

**Describe alternatives you've considered**

Some of the problems described above can be mitigated by displaying and hiding different elements, for example:

```jsx
const myBlock = {
  edit: () => {
    <div className="my-block">
      <div className="my-block-post-view">Only visible in the editor</div>
      <div className="my-block-stylepreview-view">Only visible in the preview</div>
    </div>
  },
}
```

```css
.my-block > .my-block-stylepreview-view { display: none; }
.editor-block-styles__item-preview .my-block > .my-block-post-view { display: none; }
.editor-block-styles__item-preview .my-block > .my-block-stylepreview-view { display: block; }
```

However, this is a limited solution. The block remains unaware of what will be displayed and must render the entire tree. While this may help to avoid requesting redundant `<img />`, block authors would benefit from fine-grained control over how blocks are rendered in different contexts.
