### ISSUE TITLE
Cover Image: image is displayed in editor, but not on front-end

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#1403]
On front-end, for some reason (after clicking Save and Preview in admin area) the image is not displayed. although in back-end everything is ok (after page reload as well).
This might be a theme specific, but I can't identify any CSS rules that might be a reason.

Using WP 4.8, Gutenberg 0.2, Stargazer 3.0

**Comment by youknowriad** [comment]
Yes, frontend styles are coming soon. For instance, Cover Images need something like that to work:

```css
.wp-block-cover-image .cover-image {
  background-size: cover;
  background-attachment: fixed;
  height: 430px;
}
```

You can expect those to be added automatically in upcoming releases
