### ISSUE TITLE
Stray CSS class in column block style.css

### ISSUE THREAD

**Issue by m-e-h** [WordPress/gutenberg#14596]
**Describe the bug**

In the [column block style.scss](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/style.scss#L51) there's this:
```CSS
// Specificity overide to ensure margin is applied
// and preserved on last child to ensure that when columns
// are aligned to bottom they are are flush with each other
.wp-block-column,
.entry-content > .wp-block-columns .wp-block-column:last-child {
	margin-bottom: 1em;
}
```
I'm guessing the second selector was a mistake.

`.entry-content` isn't a WordPress class is it?

Also, it's unclear what the `:last-child` is overriding. I don't see a `margin-bottom` being specified on `.wp-block-column` anywhere else in this file.

Was this intentional @getdave ?
Sorry if it is was. I'm just eyeballing the CSS. Haven't actually looked in the browser.
