### ISSUE TITLE
Button Background Styling In The Inserter

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#16598]
**Describe the bug**

The `<button>` background style is inherited, meaning it is overriden by other unrelated styles easily. This can lead to unviewable buttons in the inserter when used outside of a post edit screen context.

For example in twentynineteen, this results in black text on a black background. I can avoid this issue with the following CSS rule:

```css
button.editor-block-types-list__item:hover {
	background: transparent;
}
```

**Comment by talldan** [comment]
Hi @tomjn, would you be able to provide some steps for reproduction? I know that might be tricky for this type of issue, if that's too difficult maybe some links to the code causing the issue, or screenshots of the problematic style rules in the browser devtools. A screenshot of the incorrect style would be great as well. Thanks!

**Comment by tomjn** [comment]
TwentyNineteen contains this style:

```css
.button:hover, button:hover, input[type="button"]:hover, input[type="reset"]:hover, input[type="submit"]:hover {
    background: #111;
    cursor: pointer;
}
```

Which means that when you hover over a button in the block inserter it's not possible to see the result:

<img width="444" alt="Screenshot 2019-07-16 at 12 32 39" src="https://user-images.githubusercontent.com/58855/61291256-ee4e1000-a7c5-11e9-9deb-d04e010036d1.png">


I added a rule to override this and enforce the original background style by setting it to `transparent`
