### ISSUE TITLE
Checked sharing button has the checkmark with wrong color

### ISSUE THREAD

**Issue by dingo-d** [WordPress/gutenberg#17567]
**Describe the bug**
When editing the post on make.wordpress.org/themes site, I noticed that one checkbox has the checkmark of the wrong color for that state

<img width="287" alt="Screenshot 2019-09-25 at 06 58 27" src="https://user-images.githubusercontent.com/8638515/65571243-55293b80-df64-11e9-8eca-692629ca8227.png">

Blue on blue makes it illegible.

I've inspected the style and it seems to be this code:

```css
input[type=checkbox]:checked::before {
    content: url(data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2020%2020%27%3E%3Cpath%20d%3D%27M14.83%204.89l1.34.94-5.81%208.38H9.02L5.78%209.67l1.34-1.25%202.57%202.4z%27%20fill%3D%27%231e8cbe%27%2F%3E%3C%2Fsvg%3E);
    /* margin:-.1875rem 0 0 -.25rem; */
    height: 1.3125rem;
    width: 1.3125rem;
}
```

The svg loaded in the `content` via `url` is blue.

<img width="855" alt="Screenshot 2019-09-25 at 07 14 23" src="https://user-images.githubusercontent.com/8638515/65571283-7b4edb80-df64-11e9-81f3-4f5db283a30f.png">

Not 100% sure where this comes from since it's bundled in `load-styles.php`.

EDIT:

The same thing happens in category picker in the sidebar.

**To reproduce**
1. Go to any post
2. Save it with sharing enabled
3. Go to that post again
4. See the faulty checkmark

**Expected behavior**
Checkmark should be white

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser Chrome
 - Version 76.0.3809.132
