### ISSUE TITLE
Cover Block: Fixed background problem in iPadOS 13.x Safari

### ISSUE THREAD

**Issue by depthoffocus** [WordPress/gutenberg#17718]
iPadOS now defaults to a 'Desktop' view in the browser on (all?) iPad devices, which suffers from the problem with Safari's handling of `background-size: cover` and `background-attachment: fixed`.

According to Apple's Safari 13 [release notes](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes), in iPadOS they have:

> Disabled -webkit-overflow-scrolling: touch on iPad. 

However, it appears not to be that simple. They have disabled it in the "desktop" mode, but seemingly still provide it it if you request the "mobile" site. 

The absence of this webkit-only feature means that the CSS implemented in #11480 that sets `background-attachment: scroll`  no longer works in the default iPadOS browser view:

```css
@supports (-webkit-overflow-scrolling: touch) {
    .wp-block-cover-image.has-parallax, .wp-block-cover.has-parallax {
        background-attachment:scroll
    }
}
```

**To reproduce**

1. Go to a page with a fixed background cover block above a lot of content
2. The background image will be blurry and stretched like it was before #11480
3. Choose "Request Mobile Website" 
4. The fix behaviour is restored

(Tested with Gutenberg 6.5.0)

**Expected behavior**

Ideally the existing mobile Safari behaviour should be preserved, since `background-attachment: fixed` is still not correctly supported.

**Smartphone (please complete the following information):**

 - Device: iPad Pro 10.5" 
 - OS: iOS 13.2
 -  Safari

_(Edited for clarity. Apologies for any dimwittedness -- this is my first ever github issue!)_

**Comment by depthoffocus** [comment]
As a potential fix, the best alternative property to test with `@supports` appears to be `-webkit-touch-callout: inherit`:

[(-webkit-touch-callout on developer.mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout)

So this is working for me:

```css
.wp-block-cover.has-parallax, .wp-block-cover-image.has-parallax {
  @supports (-webkit-touch-callout: inherit) {
    background-attachment: scroll;
  }
}
```
