### ISSUE TITLE
body not mapped to editor-style-wrapper in some cases

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#19262]
**Describe the bug**
This part of the theme main (frontend) stylesheet is included as Gutenberg asset style:
```css
body h1,
body h2,
body h3,
body h4,
body h5,
body h6 {
  color: #261773;
  text-transform: uppercase;
  font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
  font-weight: 400;
  margin: 0;
  transform: scaleY(0.6);
  font-size: 1.7em;
}
````
```php
    add_theme_support( 'editor-styles' );
// [...]
    wp_enqueue_style(
        'editor-theme',
        './styles/main.css',
        false,
        true
    );
````
While many styles with `body` selector are correctly rewritten/mapped(/whatever method internally used by the Gutenberg editor), the styles above also style the heading elements of the Gutenberg editor UI, not just the editor contents, which is unintended.

**To reproduce**
1. Enqueue the styles above as Gutenberg editor assets style.
2. Ensure `add_theme_support( 'editor-styles' );` is called correctly for the theme.
3. Enable that theme.
4. Visit a Gutenberg editor page and notice that its UI headings also have been styled.

**Expected behavior**
All `body` selectors in that stylesheet are mapped to `.editor-style-wrapper`.
