### ISSUE TITLE
url([...]url([...])[...]) causes styles wrapping to fail completely (although valid CSS)

### ISSUE THREAD

**Issue by strarsis** [WordPress/gutenberg#21569]
**Describe the bug**
Some inline SVG strings in CSS cause the Gutenberg editor to fail the wrapping of the theme styles.
Example SVG (reduced to a valid minimum (but useless) SVG that reproduces the issue in Gutenberg):
```svg
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'><defs><style>.b{clip-path:url(#a);}</style></defs></svg>
````
Many CSS postprocessors (SASS/PostCSS) inline small SVGs for optimization using `data:image:svg+xml;charset=utf-8,[escaped SVG]`.

**To reproduce**
1. Use a theme that contains an affected inline SVG string in its styles, e.g.
```css
body h2 {
  color: white !important;
}

.wp-block-group {
  color: blue !important;
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3Cdefs%3E%3Cstyle%3E.b%7Bclip-path:url(%23a);%7D%3C/style%3E%3C/defs%3E%3C/svg%3E");
  color: red !important;
}

body h2 {
  color: grey !important;
}
````
2. Open a post/page on which the aforementioned styles are applied in the Gutenberg editor.
3. Ensure a `core/group` and `core/heading` (H2!) block with some example text being present in the post/page.
4. Notice that the red color is not applied, unless the inlined SVG is removed.
The blue color isn't applied either - the whole declaration that selects `.wp-block-group` is not applied. But even the styles for the heading below aren't applied, the block got neither white or grey color, hence the whole stylesheet isn't applied when this bug hits.
Error in console:
````
Error while traversing the CSS: Error: undefined:2:27: missing '}'
````

**Expected behavior**
All styles are applied to editor styles wrapper correctly, as usual.

**Additional context**
WordPress `5.4`
Gutenberg `7.8.1`

The issue is caused by the succession of an `url(...)` reference (no `#` needed for this bug btw.) and then an "unnecessary" semicolon (when it is the last CSS property in declaration).

Further reduced test case with invalid but bug-reproducing SVG:
```css
.wp-block-group {
  background-image: url("data:image/svg+xml,%3Csvg%3E.b%7Bclip-path:url(test);%7D%3C/svg%3E");
  color: red !important;
}
````

Minimal version that causes the bug:
```css
.wp-block-group {
  background: url("url(t);");
}
````
The parser doesn't like `url()` in `urlI)` although this CSS validates with https://jigsaw.w3.org/css-validator/validator.

Gutenberg uses its own CSS parser implementation:
https://github.com/WordPress/gutenberg/blob/bb24bbef1790b165ca8608d4cee7a5ec6e85c234/packages/block-editor/src/utils/transform-styles/ast/parse.js
Wouldn't it be a good idea to use something existing like what PostCSS does (and works with native JavaScript)? There is even a [PostCSS plugin for exactly this](https://github.com/m-e-h/postcss-editor-styles).
