### ISSUE TITLE
.wp-block-column[style] selector broke layout in 5.4. Seems like an overly broad technique for selectors in general.

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#22557]
I apply a style attribute dynamically to the `.wp-block-column` for a custom page layout. This (new?) rule broke my layout in 5.4:

```css
.wp-block-column[style] {
    flex-grow: 0;
}
```

Any selector that solely tests for the existence of another attribute strikes me as overly broad. It would be much safer to use another class click `.wp-block-column.has-custom-width` or similar for whatever the purpose of the block is.

WP 5.4

**Comment by justintadlock** [comment]
@mrwweb - Is this still an issue?  I didn't see it in the code.  If not, we can close this ticket out.

**Comment by mrwweb** [comment]
@justintadlock I think this probably isn't an issue now. Looking at a recent site, I'm now seeing the rule:

```css
.wp-block-columns:not(.is-not-stacked-on-mobile) > .wp-block-column[style*="flex-basis" ]{
  flex-grow: 0;
}
```

I suspect that's the same rule with a more specific selector that's much less likely to cause problems. Closing.
