### ISSUE TITLE
Images should always provide dimensions

### ISSUE THREAD

**Issue by felixarntz** [WordPress/gutenberg#23244]
## Background
In order for the browser to set up a webpage's layout it's important that images have their dimension attributes `width` and `height` provided, as this will inform the browser of the effective aspect ratio of the image before it is even loaded. Without these attributes provided, the page layout will reflow once the image has loaded, causing so-called "layout shift" which is harmful for user experience (think about the experience where you want to click on something but just as you're about to do so the page content moves and you accidentally click on something else). These layout shifts always happen - the experience is worse on a slow network connection, but they are visible pretty much no matter how fast the connection is.

Historically the classic editor has always provided these attributes, but that was changed in Gutenberg, where now the majority of images is without `width` and `height`. This issue seeks to address this to reduce the cumulative layout shift across WordPress sites for content generated with Gutenberg. I've been working on a closely [related core issue](https://core.trac.wordpress.org/ticket/50367) (feel free to chime in there as well!) that addresses this in a more "patch-y" way that will retroactively work, but we should address this in Gutenberg too to get the proper experience in the editor itself as well.

The main question we should discuss and answer first is: Why was it initially decided to omit `width` and `height` attributes?

## Goal
The following blocks should always provide `width` and `height` on `img` elements, regardless of whether the user provided a custom size or not:
* `core/image`
* `core/gallery`
* `core/media-text`
* (did I miss any?)

## Related
* #869 and #4898
* #4914 and #5812

**Comment by oxyc** [comment]
Not sure about historical reasons but an idea to avoid the layout shift even if images are shown as `max-width: 100%` is using aspect ratio boxes.

```html
<!-- (width / height) set by block based on image natrual size -->
<figure class="wp-block-image size-large" style="--aspect-ratio: 810/540;">
  <img src="">
</figure>
```

```scss
.wp-block-image:not(.is-resized) {
  &[style*="--aspect-ratio"] img {
    width: 100%;
    height: auto;
  }
  
  @supports (--custom:property) {
    [style*="--aspect-ratio"] {
      position: relative;
    }

    [style*="--aspect-ratio"]::before {
      content: "";
      display: block;
      padding-bottom: calc(100% / (var(--aspect-ratio)));
    }  

    [style*="--aspect-ratio"] img {
      position: absolute;
      top: 0;
      left: 0;
      height: 100%;
    }  
  }
}
```
