### ISSUE TITLE
has-huge-font-size smaller than on editor when using default styling

### ISSUE THREAD

**Issue by mateuswetah** [WordPress/gutenberg#24023]
**Describe the bug**
The `has-huge-font-size` class used on the font size picker component sets a value of `48px` by default. But visiting the published page you can see that the font is a bit smaller, actually `42x`.

**To reproduce**
1. Use a theme that does not override and uses the default styling for font sizes, for example, _TwentySeventeen_;
2. Create a paragraph and, using the font size picker, set it as "Huge". You'll see in the input that `48` is set;
3. Publish or preview your post. Check the font size with the inspector, it should be `42px`.

**Expected behavior**
Default styling should display `48px` font size on both editor and theme side.

**Screenshots**
Editor side:
![Editor side screenshot, with font size set to huge](https://user-images.githubusercontent.com/1184874/87806420-3b2b5300-c82d-11ea-8a14-0eacdbfff5fb.png)

Theme side:
![Theme side with inspector open to check font size](https://user-images.githubusercontent.com/1184874/87806502-5dbd6c00-c82d-11ea-9bdc-53445b34476d.png)

**Editor version:**
- WordPress version: 5.5-beta2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?: "default"

**Desktop :**
 - OS: Linux Ubuntu 20.04
 - Browser Firefox
 - Version 78.0.2 64bits

**Additional context**
This seems to be pretty simple to fix, I'm just not sure if the solution wouldn't break any compatibility. I'm thinking of changing this, on `packages/block-library/src/style.scss`:
```scss
.editor-styles-wrapper .has-larger-font-size,
.editor-styles-wrapper .has-huge-font-size,
.has-larger-font-size, // Not used now, kept because of backward compatibility.
.has-huge-font-size {
	font-size: 42px;
}
```
To this:
```scss
// Not used now, kept because of backward compatibility. 
.editor-styles-wrapper .has-larger-font-size,
.has-larger-font-size {
	font-size: 42px;
}
.editor-styles-wrapper .has-huge-font-size,
.has-huge-font-size {
	font-size: 48px;
}
