### ISSUE TITLE
Full width mode editor

### ISSUE THREAD

**Issue by robsonsobral** [WordPress/gutenberg#24118]
Hi, guys!

**Is your feature request related to a problem? Please describe.**
When adding a 3 or more column block, the space is too narrow to properly edit.

**Describe the solution you'd like**
It would be awesome to have a full width mode, so we can use all the monitor text area.

**Describe alternatives you've considered**
I changed the value of the width property on the rules under the selector `.wp-block`:

```css
/* style.css | /wp-content/plugins/gutenberg/build/edit-post/style.css?ver=1594398684 */

.wp-block {
  /* max-width: 580px; */
  max-width: 100%;
}
```

Thank you!
