### ISSUE TITLE
theme.json: change text colors depending on background

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#24166]
I want to highlight an interaction that some themes do at the moment in PHP land, for which we don't have an alternative in the theme.json spec.

Note how the text color changes depending on the background color (dark/light combination):

![text-color-change](https://user-images.githubusercontent.com/583546/88310487-0416df00-cd10-11ea-9087-a9d1778cb129.gif)

**Comment by aristath** [comment]
Ideally this could be accomplished by adding a class to elements that have a background-color.
So if a block has the `has-background` class, we could add an extra class to it: `has-background-light` or `has-background-dark` depending on the luminosity of the background color.
If we do that, then themes will be able to just add CSS like this:
```css
.has-background-light:not(.has-text-color) {
  color: #000;
}

.has-background-dark:not(.has-text-color) {
  color: #fff;
}
```

I tried to create a PR for this one today, the only issue I ran into was properly getting the palette of available colors. We'll need that in order to get the color HEX value from the color-name, and then figure out if the color is light or dark.
