### ISSUE TITLE
WP 5.5: Double metabox borders

### ISSUE THREAD

**Issue by igorschoester** [WordPress/gutenberg#24612]
**Describe the bug**
A double border bottom in each metabox header.

**To reproduce**
1. Have a plugin with a metabox (e.g. Yoast SEO).
2. Go to create a new post.
3. Scroll down to the metabox.
4. See the double border.

**Expected behavior**
Only have a single border.

**Screenshots**
<img width="1016" alt="metaboxes" src="https://user-images.githubusercontent.com/35524806/90483745-7921dc80-e135-11ea-9e28-40654329bae0.png">

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 84

**Additional context**
I created this issue here because the border in WP itself spans the full width of the metabox. While the border in Gutenberg does not cover the actions.

The full width border was introduced in WP 5.5 itself: https://core.trac.wordpress.org/changeset/48373
Located in `wp-admin/css/common.css` on line 2035:
```css
.postbox-header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	border-bottom: 1px solid #ccd0d4;
}
```

[The handle only border](https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/meta-boxes/meta-boxes-area/style.scss#L29:L41) is located in `packages/edit-post/src/components/meta-boxes/meta-boxes-area/style.scss` on line 29:
```css
/* Override Default meta box stylings */
#poststuff h3.hndle,
#poststuff .stuffbox > h3,
#poststuff h2.hndle { /* WordPress selectors yolo */
	border-bottom: $border-width solid $gray-200;
	box-sizing: border-box;
	color: inherit;
	font-weight: 600;
	outline: none;
	padding: 15px;
	position: relative;
	width: 100%;
}
```
