### ISSUE TITLE
Add content-width option to global-styles & `theme.json`

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#25160]
Spawned from https://github.com/WordPress/gutenberg/issues/20771

I started building a block-based theme from scratch today, and was surprised by how hard it still is to do some things.
The hardest part when creating a theme for use with the editor is figuring out how to handle the following:
* Add `max-width` to blocks so they are limited to a pre-defined content-width
* Handle `alignwide`
* Handle `alignfull`

Writing the CSS for these things is an absolute nightmare, especially in FSE where the user can add a sidebar, 2 sidebars, have nested columns within groups that are nested in columns and so on.

Generating these styles automatically would be ideal, and if done properly would solve a lot of issues.

## `theme.json`
In `theme.json` we could use 2 options:
* `contentWidth`: (string) can use any CSS value (`90%`, `1000px`, `60em` etc)
* `alignWideWidth`: (string|number) If string then any CSS value. If number then assume proportionate to the `contentWidth` (`1.25` would be 1.25 times the contentWidth).

## Global Styles
In global-styles we'd need a setting for the content-width.
Adding the align-wide-width option would be of secondary importance and not really necessary. Good to have, but not a requirement.

-------------------
EDIT: After further experimentation I realized that what we need is not a site-width as this original post was stating, but a content-width.
Site-width would be useful when building a "boxed" layout, which is not what most people will want. Content-width on the other hand describes more accurately what this is about: Setting a max-width for the actual blocks.
The site-width can be accomplished with columns if needed (3 columns, with the middle one set to 900px and the other 2 left to auto-calc)

**Comment by kjellr** [comment]
> Adding the align-wide-width option would be of secondary importance and not really necessary. Good to have, but not a requirement.

This would be a nice first step towards letting Gutenberg handle wide/full alignments styles on the front end. Gutenberg already makes this work in the editor, but theme authors have to write (in some cases, _a lot_ of) styles on the front-end to implement the alignments there too. They shouldn't need to do that in the future, especially when block-based themes become the standard.

**Comment by aristath** [comment]
Regarding the generated CSS, as I meantioned before it's a nightmare to get t right - especially on layouts with sidebars.
Below is an example I found works in all cases, regardless of the layout used:
```css
:root {
    font-size: 22px;
    --contentWidth: 900px;
    --wideWidth: calc(1.25 * var(--contentWidth));
}

.wp-block-post-content {
    --paddingHorizontal: 1em;
    padding: 0 var(--paddingHorizontal);
}

.wp-block-post-content > :not(.alignfull):not(.alignwide):not(.alignleft):not(.alignright) {
    max-width: var(--contentWidth);
    margin-left: auto;
    margin-right: auto;
}

.wp-block-post-content .alignwide {
    width: calc(var(--wideWidth) + 2 * var(--paddingHorizontal));
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
}

.wp-block-post-content .alignfull {
    transform: translateX(calc(0px - var(--paddingHorizontal)));
    width: calc(100% + 2 * var(--paddingHorizontal));
    max-width: calc(100% + 2 * var(--paddingHorizontal));
    margin-left: auto;
    margin-right: auto;
}

.wp-block-post-content .alignleft {
    float: left;
    margin-left: calc(50% - var(--contentWidth) / 2);
}
  
.wp-block-post-content .alignright {
    float: right;
    margin-right: calc(50% - var(--contentWidth) / 2)
}       
```
It is something that I've been working on [for a long time](https://aristath.github.io/blog/the-gutenberg-layout-problem) on various themes, and so far doesn't seem to have any issues.
The downside is that it's a complicated solution, but that's only because the nature of the problem is complex.
What the above code does:
* Adds a left/right padding to the content. This helps for mobile views so the content doesn't go to the very edge of the screen which can be extremely annoying.
* Adds a width to alignwide elements, taking the padding into account
* Properly positions the alignfull elements
* Works with any number of sidebars in the layout etc
* Properly styles floated elements

In the above code I'm only doing this for `.wp-block-content`, but I'm sure we can abstract the logic and make it work everywhere.

**Comment by ZebulanStanphill** [comment]
Why can't the `.wp-block-post-content > :not(.alignfull):not(.alignwide):not(.alignleft):not(.alignright)` selector just be `.wp-block-post-content > *`? I don't like the heavy use of `:not` here; it feels really fragile to me, and it increases the specificity a lot.

**Comment by aristath** [comment]
Good point, updated :+1:

**Comment by scruffian** [comment]
What do you think about adding `box-sizing: border-box` so that we don't have to do so many calculations for padding?

(See https://github.com/WordPress/gutenberg/pull/25115)

**Comment by aristath** [comment]
Thank you @scruffian for your suggestion to use `border-box`.

The bare minimum I have to make alignments work properly regardless of the layout is now this:
```css
:root {
    --contentWidth: 900px;
    --wideWidth: calc(1.5 * var(--contentWidth));
}

* {
    box-sizing: border-box;
}

.wp-site-blocks {
    --paddingHorizontal: 1em;
    padding: 0 var(--paddingHorizontal);
}

.wp-site-blocks > *:not(.wp-block-post-content),
.wp-site-blocks > .wp-block-post-content > * {
    max-width: var(--contentWidth);
    margin-left: auto;
    margin-right: auto;
}

.wp-site-blocks .alignwide {
    width: var(--wideWidth);
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
}

.wp-site-blocks .alignfull {
    transform: translateX(calc(0px - var(--paddingHorizontal)));
    width: 100%;
    max-width: 100%;
    box-sizing: content-box;
}

.aligncenter {
    text-align: center;
}

.wp-site-blocks .alignleft {
    float: left;
    margin-right: 2em;
    max-width: 360px;
}

.wp-site-blocks .alignright {
    float: right;
    margin-left: 2em;
    max-width: 360px;
}       
```
A lot cleaner... and I think with a couple more tweaks we should be able to have a result that we can automatically add to FSE themes, taking the content-width setting into account.
