### ISSUE TITLE
Incorrect admin color scheme

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#25282]
When switching admin color scheme to a non-default color scheme, the CSS variables outputted are incorrect, which makes some components like <Button> have wrong colors.

For example, if I switch the color scheme to **Ectoplasm**, the buttons have the following colors:

```css
.wp-core-ui .button-primary {
	background: #a3b745;
	border-color: #a3b745;
	color: #fff;
}
```

But the CSS variables outputted still:

```css
:root {
	--wp-admin-theme-color: #007cba;
	--wp-admin-theme-color-darker-10: #006ba1;
	--wp-admin-theme-color-darker-20: #005a87;
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/668274/93039017-a13b2780-f670-11ea-899d-5e899987e61f.png)

**Editor version:**
- WordPress version: 5.5.1
- Default Gutenberg editor in WordPress (not the standalone plugin)
