### ISSUE TITLE
Default wp-env environment not functional: database connection errors

### ISSUE THREAD

**Issue by chrisRidgers** [WordPress/gutenberg#25717]
**Describe the bug**
`wp-env start` creates environment where wordress container cannot access mysql (mariadb) container.

**To reproduce**

Following documentation at: 

- https://developer.wordpress.org/block-editor/tutorials/devenv/
- https://developer.wordpress.org/block-editor/packages/packages-env/

```
➜  wp-create-block starter-block

Creating a new WordPress block in "starter-block" folder.

Creating a "block.json" file.

Creating a "package.json" file.

Installing packages. It might take a couple of minutes.

Formatting JavaScript files.

Compiling block.

Done: block "Starter Block" bootstrapped in the "starter-block" folder.

Inside that directory, you can run several commands:

  $ npm start
    Starts the build for development.

  $ npm run build
    Builds the code for production.

  $ npm run format:js
    Formats JavaScript files.

  $ npm run lint:css
    Lints CSS files.

  $ npm run lint:js
    Lints JavaScript files.

  $ npm run packages-update
    Updates WordPress packages to the latest version.

You can start by typing:

  $ cd starter-block
  $ npm start

Code is Poetry
➜  cd starter-block 
➜  wp-env start
✖ Error while running docker-compose command.
Starting 8a9345b875a8c995d91bc92a44fa1ff5_mysql_1 ... done
Starting 8a9345b875a8c995d91bc92a44fa1ff5_wordpress_1 ... done
Creating 8a9345b875a8c995d91bc92a44fa1ff5_cli_run     ... done
mysqlcheck: Got error: 1130: Host '172.21.0.5' is not allowed to connect to this MariaDB server when trying to connect
```

Which generates docker-compose.yml:

```
version: '3.7'
services:
  mysql:
    image: mariadb
    ports:
      - '3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - '${WP_ENV_PORT:-8888}:80'
    environment:
      WORDPRESS_DB_NAME: wordpress
    volumes: &ref_0
      - 'wordpress:/var/www/html'
      - >-
        /home/chris/Development/Personal/wordpress-demo/starter-block:/var/www/html/wp-content/plugins/starter-block
  tests-wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - '${WP_ENV_TESTS_PORT:-8889}:80'
    environment:
      WORDPRESS_DB_NAME: tests-wordpress
    volumes: &ref_1
      - 'tests-wordpress:/var/www/html'
      - >-
        /home/chris/Development/Personal/wordpress-demo/starter-block:/var/www/html/wp-content/plugins/starter-block
  cli:
    depends_on:
      - wordpress
    image: 'wordpress:cli'
    volumes: *ref_0
    user: '33:33'
  tests-cli:
    depends_on:
      - tests-wordpress
    image: 'wordpress:cli'
    volumes: *ref_1
    user: '33:33'
  composer:
    image: composer
    volumes:
      - '/home/chris/Development/Personal/wordpress-demo/starter-block:/app'
  phpunit:
    image: 'wordpressdevelop/phpunit:${LOCAL_PHP-latest}'
    depends_on:
      - tests-wordpress
    volumes:
      - 'tests-wordpress:/var/www/html'
      - >-
        /home/chris/Development/Personal/wordpress-demo/starter-block:/var/www/html/wp-content/plugins/starter-block
      - 'phpunit-uploads:/var/www/html/wp-content/uploads'
    environment:
      LOCAL_DIR: html
      WP_PHPUNIT__TESTS_CONFIG: /var/www/html/phpunit-wp-config.php
volumes:
  wordpress: {}
  tests-wordpress: {}
  mysql: {}
  phpunit-uploads: {}
```

And subsequently you receive generic database connection errors when visiting localhost:8888 and /wp/wp-admin

Logs:

```
wordpress_1        | WordPress not found in /var/www/html - copying now...
wordpress_1        | Complete! WordPress has been successfully copied to /var/www/html
wordpress_1        | [29-Sep-2020 19:30:50 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:50 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:50 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:30:53 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:53 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:53 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:30:56 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:56 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:56 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:30:59 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:59 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:59 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:02 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:02 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:02 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:05 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:05 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:05 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:08 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:08 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:08 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:11 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:11 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:11 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:14 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:14 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:14 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:17 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:17 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:17 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | 
wordpress_1        | WARNING: unable to establish a database connection to 'mysql'
wordpress_1        |   continuing anyways (which might have unexpected results)
wordpress_1        | 
wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1        | [Tue Sep 29 19:31:17.263850 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.10 configured -- resuming normal operations
wordpress_1        | [Tue Sep 29 19:31:17.263880 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
wordpress_1        | 172.22.0.1 - - [29/Sep/2020:19:40:19 +0000] "GET /wp-admin/ HTTP/1.1" 500 3583 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
```

**Expected behavior**
Running `wp-env start` from a plugin directory should result in a working dev environment with my plugin installed (if not active).

**Editor version (please complete the following information):**
- WordPress version: 5.5.1]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Not sure how to check this but presuming yes being a recent WordPress version
- If the Gutenberg plugin is installed, which version is it? Unknown

**Desktop (please complete the following information):**
 - OS: 
   LSB Version:	n/a
   Distributor ID:	ManjaroLinux
   Description:	        Manjaro Linux
   Release:	20.1
   Codename:	Mikah

**Additional context**
- Docker version 19.03.12-ce, build 48a66213fe
- Node Version: v12.18.4
- NPM Version: 6.14.6

Attempting to run other database containers and connect to the database results in a similar error:

```
➜  8a9345b875a8c995d91bc92a44fa1ff5 docker-compose run --rm mysql mysql -h mysql -uroot   
Creating 8a9345b875a8c995d91bc92a44fa1ff5_mysql_run ... done
ERROR 1130 (HY000): Host '172.22.0.5' is not allowed to connect to this MariaDB server
```
