### ISSUE TITLE
Gutenberg Editor - Matching frontend experience with color

### ISSUE THREAD

**Issue by Bowriverstudio** [WordPress/gutenberg#25809]
Hello all,

On the frontend I've got a setup like this:

![Gutenberg-Editor](https://user-images.githubusercontent.com/36542929/94996442-02fcfc00-0562-11eb-8213-7d2ffb240de4.png)

In the Gutenberg editor, I've added the styles,

```css

.block-editor-writing-flow {
  background: green;
}

.wp-block {
  max-width: 72rem;
  backroung:blue;
}
```

which results in:

![Result](https://user-images.githubusercontent.com/36542929/94996778-bca89c80-0563-11eb-9867-93e973f06420.png)

I'm not sure how to get the inner container blue or add the padding.

Thank you
