### ISSUE TITLE
Single Column Block Displays at 50% on Screens Between ($break-small) ($break-medium - 1)

### ISSUE THREAD

**Issue by aaroncampbell** [WordPress/gutenberg#26435]
When a column is added and set to single column (100%) it will only display at 50% width on smaller screens.

**To reproduce**
1. Add a column block, select the 100 variant, add some content.
2. Publish or preview in new tab
3. Adjust browser width to between 600 & 781px
4. Column is only 50% and left aligned.

**Screenshots**
![Gutenberg single column at 599px](https://user-images.githubusercontent.com/802412/97083708-a24c6680-15d7-11eb-97ca-8332a183559d.png)
Single column at 599px displays as expected
![Gutenberg single column at 600px](https://user-images.githubusercontent.com/802412/97083711-a2e4fd00-15d7-11eb-8e32-5734b9c5f50d.png)
Single column at 600px displays half-width

The problem seems to be some code [this code](https://github.com/WordPress/gutenberg/blob/a48eb9eef73b20850cbee5b3bfd4b05cfd8cbb07/packages/block-library/src/columns/style.scss#L49):
```SCSS
// Between mobile and large viewports, allow 2 columns.
@media (min-width: #{ ($break-small) }) and (max-width: #{ ($break-medium - 1) }) {
	// As with mobile styles, this must be important since the Column
	// assigns its own width as an inline style, which should take effect
	// starting at `break-medium`.
	flex-basis: calc(50% - 1em) !important;
	flex-grow: 0;

	// Add space between the multiple columns. Themes can customize this if they wish to work differently.
	// Only apply this beyond the mobile breakpoint, as there's only a single column on mobile.
	&:nth-child(even) {
		margin-left: 2em;
	}
}
```
