### ISSUE TITLE
Preset controls need the preset CSS variables in scope

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#26511]
Reported at https://github.com/Automattic/themes/pull/2659/files#r512186187

Theme authors can use CSS Custom Properties to define the presets, for example, to make the gradients depend on the solid colors:

```
{
  "color": {
    "gradients": [
      {
        "slug": "some-gradient",
        "gradient": "linear-gradient(to bottom, transparent 20%, var(--wp--preset--color--secondary) 20%, var(--wp--preset--color--secondary) 80%, transparent 80%)"
      }
    ],
    "palette": [
      {
        "slug": "primary",
        "color": "#000000"
      },
      {
        "slug": "secondary",
        "color": "#3C8067"
      }
    ]
  }
}
```

These definitions end up attached to the user-facing UI tools. The problem is that these tools aren't part of the editor canvas (wrapper by the `.editor-styles-wrapper` class), so the CSS Custom Properties aren't defined, hence it doesn't work. See what would happen in this case:

<img width="268" alt="97214074-eaff4d80-1798-11eb-9969-18182f7a9939" src="https://user-images.githubusercontent.com/583546/97341913-ef556480-1885-11eb-9727-655f5a169873.png">

This is because, both in the post-editor and the site-editor, the global styles are prefixed by the editor wrapper, hence its scope doesn't reach the UI controls.

**Comment by nosolosw** [comment]
Some thinking out loud:

- In the post editor, we pass the styles via the `styles` key of settings, so they are processed (added the `.editor-styles-wrapper`) as if they were theme styles. In the site editor, we add the wrapper ourselves.

- Presets defined at any level (global, but also core/paragraph, etc) create CSS Custom Properties. For them to be in the scope of the UI controls they have to be outside the editor wrapper.

One thing we can do to fix this is to separate how we embed styles and presets in the HTML document: the presets are always enqueued by the server as an inline stylesheet (no style rule mangling in the client) and the styles continue to work as they are now (processed by the client, as to only affect the editor canvas).

So, we'd have:

```css
/* inline stylesheet enqueued by the server for the presets */

:root { /* global context */
    --wp--preset--color--primary: 'value';
    --wp--preset--color--secondary: 'value';
}

p { /* core/paragraph context */
    --wp--preset--color--primary: 'value';
    --wp--preset--color--secondary: 'value';
}
```

```css
/* inline stylesheet created by the editor (post-editor, site-editor) for the styles */

.editor-styles-wrapper { /* global context */
    background-color: 'value';
}

.editor-styles-wrapper p { /* core/paragraph context */
    background-color: 'value';
}
```

cc @jorgefilipecosta in case you have any thoughts.
