### ISSUE TITLE
Code block: Font size does not work for TwentyTwentyOne 

### ISSUE THREAD

**Issue by mkaz** [WordPress/gutenberg#27827]
**Describe the bug**

Setting the font size for the code block will add the class `has-large-font-size` to the outer `pre` block but does not set the class for the inner `code` block. So for the theme TwentyTwentyOne the code block size appears to not work.

Markup ends up being:
```html
<pre class="wp-block-code has-large-font-size">
<code> // Foo </code>
</pre>
```

The CSS from the theme:

```css
.wp-block-code code {
    font-size: var(--global--font-size-xs);
    white-space: pre;
    overflow-x: auto;
    display: block;
}
```

Is it only a theme issue? If the class is attached to the `code` tag then it would work too.
