### ISSUE TITLE
Documentation: How to specify defaults for text colors separate from background colors?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#28146]
Being able to show different default colors for text and background feels like a good documentation to add to the Block editor handbook. https://developer.wordpress.org/block-editor/

The question came up here:
**Defining separate colors for backgrounds and text**

https://wordpress.org/support/topic/defining-separate-colors-for-backgrounds-and-text/

**Comment by JustinyAhin** [comment]
Looking at the code starting by https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/theme.php#L3689, it doesn't seem like this feature exists.

May worth opening a feature request on Trac

**Comment by paaljoachim** [comment]
I assume you mean a feature request issue here on the Gutenberg repo.

**Comment by JustinyAhin** [comment]
Huh 🤔, I guess we will need to register features for text color palette and background color palette and initialize the editor with it: https://gist.github.com/3a7cfd18695133af58d207bebbf0100f.git. This should normally happen on Trac.

**Comment by mkaz** [comment]
Justin, I think Paal (and the original question) were looking for documentation on how a user might set default colors using the block editor not for the documentation site. The snippet of code you included is correct, here is the [documentation page for color palettes](https://developer.wordpress.org/block-editor/developers/themes/theme-support/).

I think it still requires effort made on the theme side and not yet possible for a user to switch the defaults globally.

**Comment by paaljoachim** [comment]
Ahhh.....
Yes. I was talking about the Gutenberg plugin support question:
https://wordpress.org/support/topic/defining-separate-colors-for-backgrounds-and-text/

"In the theme 2021, functions.PHP adds support for editor-color-palette as well as editor-gradient-presets. Is there a way to specify defaults for text colors separate from background colors? I want to define an array of text colors and a different array of background colors."

**Comment by matthewmcvickar** [comment]
I would love to be able to set two separate palettes for the 'Text Color' and 'Background Color' color settings. Is that what this ticket is tracking? I can't quite figure out what's going on in this ticket or the linked 'custom colors' ticket (#6941). Has there been any movement on this feature?

**Comment by paaljoachim** [comment]
Hey @matthewmcvickar 

I mentioned this:
> Is there a way to specify defaults for text colors separate from background colors?

I found the initial support request intriguing. As it feels natural to have one color palette for the text colors and another set of colors - color palette for the background color. I noticed you linked in:
Core Component: Allow Saving Custom Colors to the Color Palette
https://github.com/WordPress/gutenberg/issues/6941 
I also noticed that 6941 links in many other issues as well. 

I assume that this issue actually can be closed, as it is still a feature that needs to be worked on, and when merged it will be natural to extend the color palettes documentation.

**Comment by cr0ybot** [comment]
#6941 was closed due to the introduction of theme.json, which does not address different palettes for background vs text.

I have been digging into the button block code for a few hours now to figure out if it is in any way possible to alter or remove the background color palette while leaving the text color palette alone, and I'm just not seeing a viable path. Maybe I'm missing something obvious, but I don't think this is about documentation, and I don't think this issue should be closed.

**Comment by paaljoachim** [comment]
Hey @cr0ybot 

I made this issue:
**Allow Saving Custom Colors to the unique Color Palette for color og background** (Might need to be renamed)
https://github.com/WordPress/gutenberg/issues/34445

**Comment by mkaz** [comment]
I updated the ticket to clarify that it is not just a documentation change but a feature to allow for specifying a palette is specific for background only colors, or text only colors.

**Comment by andreawetzel** [comment]
A came across this Issue while trying to find a way to specify a palette specific to link colors. We would like our editors see Blue in the palette for link colors, but not for text and background colors. 

![Screenshot 2024-09-17 at 11 27 48 AM](https://github.com/user-attachments/assets/83c68578-edbb-4942-ae16-7d9b0f10117f)

**Comment by cr0ybot** [comment]
Not a solution by any means, but I needed something that would at least differentiate different groups of colors in the palette. In my case, some of the colors meant for text vs background vs other elements are the same. This is the result:

![Image](https://github.com/user-attachments/assets/4d3f1c83-278a-476a-b7b5-06543ce9ac47)

To accomplish this, I put together this CSS hack which works based on 2 premises:

1. Your color palette slugs follow a well-defined naming scheme that includes the "group" the color is in. Here they look something like `--wp--preset--color--text-on-light-primary` and `--wp--preset--color--bg-dark-primary`.
2. The colors are defined so that items belonging to the same group are siblings (don't mix them around).

Presented in the original Sass:

```scss
/**
 * Color palette hack to show swatches grouped by type.
 *
 * This is looking for the style set on the button element to find a partial
 * match for the CSS variable names. This may need to be updated if the palette
 * changes or if the WordPress version is updated past 6.7.
 */
.components-circular-option-picker {

	&__option-group {
		align-items: end;
		display: grid !important;
		grid-template-columns: repeat(6, 1fr);
	}

	&__option-wrapper {
		@mixin palette-section( $label ) {
			grid-column-start: 1;
			margin-top: 1.25rem;

			&::after {
				content: $label;
			}
		}

		&::after {
			bottom: 100%;
			content: "";
			font-size: 0.5rem;
			font-weight: 500;
			left: 50%;
			position: absolute;
			text-transform: uppercase;
			transform: translateX(-14px);
			transform-origin: bottom left;
			transition: inherit;
		}

		&:hover {
			// Attempt to keep the label in place when hovering over the first swatch.
			&::after {
				transform: scale(0.8333) translateX(-14px) translateY(3px);
			}
		}

		&:nth-child(1 of :has(button[style*="palette--text"])) {
			@include palette-section("text");
		}

		&:nth-child(1 of :has(button[style*="palette--bg"])) {
			@include palette-section("background");
		}

		&:nth-child(1 of :has(button[style*="palette--fg"])) {
			@include palette-section("foreground");
		}
	}
}
```
