### ISSUE TITLE
Cover image block markup in the front-end

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#2902]
**Markup**:

```php
<section class="wp-block-cover-image has-background-dim" style="background-image:url(http://wordpress-svn/src/wp-content/uploads/2017/09/abc.jpg)">
	<h2>Donate Now – We need you</h2>
</section>
```

- Based on [HTML5 specs](https://www.w3.org/TR/html51/sections.html#elementdef-section) `<section>` should not be used, should be `<div>` instead.
- `<h2>` should not be hardcoded, it may be wrong heading level for correct heading hierarchy.

Quick note about CSS. 

```css
h2 {
		// ...
		font-size: 24pt;
		// ...
	}

	&.has-background-dim:before {
		background: rgba( black, 0.5 );
	}
```

Let theme handle font-size of the heading. At least it should not use `pt`. `background` should be `background-color`.
