### ISSUE TITLE
Table block markup in the front-end

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#2904]
Table block have similar issues opened but I leave this here just in case.

```php
<table class="wp-block-table">
	<tr>
		<td>First name</td>
		<td>Last name</td>
	</tr>
	<tr>
		<td>Xami</td>
		<td>Gello</td>
	</tr>
	<tr>
		<td>Zanna</td>
		<td>Petronen</td>
	</tr>
</table>
```

- You can't put `caption` or `<th>` elements in tables. Those would be good for semantic and accessible markup of tables. At least `<th>` is needed at the minimum.
- [Accessibility handbook have summary and reference links about tables](https://make.wordpress.org/accessibility/handbook/best-practices/markup/tables/).

About CSS:

```css
.wp-block-table {
	overflow-x: auto;
	display: block;

	table {
		border-collapse: collapse;
		width: 100%;
	}
}
````
All of these styles should be removed, themes already handles `table` styles. Also generated CSS `.wp-block-table table` doesn't match any element.
