### ISSUE TITLE
Blocks: Introduce separate stylesheet for editor with optional theme opt-in

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#2905]
**Markup**:

```php
<hr class="wp-block-separator">
```

**CSS**:

```css
.wp-block-separator {
	border: none;
	border-bottom: 2px solid $dark-gray-100;
	max-width: 100px;
	margin: 1em auto;
}
```

Many themes have styles for `<hr>` element so this will have styling issues with many themes. I propose removing styles from the front-end. Yeah I know then it would not match styles in the Gutenberg. That's something we need to solve.
