### ISSUE TITLE
Block widths in editor no longer respected in 10.3.1

### ISSUE THREAD

**Issue by philbuchanan** [WordPress/gutenberg#30547]
[As per the block editor how to guidelines](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#changing-the-width-of-the-editor), the suggested method for themes to set the width of blocks in the editor is as follows:

```css
.wp-block {
    max-width: 720px;
}
```

When using the Gutenberg plugin v10.3.1, the following styles are added:

```css
.edit-post-layout:not(.supports-layout) .wp-block {
    max-width: 840px;
}
```

Due to the increased specificity of that selector, the first block of code no longer works. This feels like an overly specific selector and makes it difficult to override as a theme developer. I believe this to be a regression in behaviour.
