### ISSUE TITLE
Make Synced Patterns lockable so content cannot be edited inline

### ISSUE THREAD

**Issue by vyskoczilova** [WordPress/gutenberg#32353]
## What problem does this address?
The seamless experience of editing reusable blocks (in core since 5.7) causes a lot of trouble for my clients. They are struggling to know when they are editing a reusable block and when the normal content. 

For example, you have a reusable block in a column and you want to add another content to the column, no to the RB. What do you do? Users do click on the existing content and click on the + icon.

I've been explaining it since the 5.7 is out and it doesn't help at all. They don't want to pay that much attention to the editing and "locked" reusable block content would be the best.

## What is your proposed solution?
Option to disable direct editing for reusable blocks - either allow to return to the state before 5.7 was released or just lock it (and users would go to revealed wp_blocks post archive or something).

I would love to select a reusable block just as a parent to move it around, but not the child (I think that's the part when it causes a lot of trouble).

If I miss a filter or something I'll be really glad if you point me in the right direction. I've tried to disable it via CSS and pointer events and it's just super tricky and kind of mission impossible when I want to move the blocks but not to edit them (eg you need to select them via list view and then move them around):

```scss
.is-reusable {
    opacity: 0.5;
    cursor: not-allowed;
	.block-editor-block-list__layout > * {
		pointer-events: none;
	}
	.block-list-appender {
		display: none;
	}
}
```
