### ISSUE TITLE
Query block: CSS Grid for Grid View option

### ISSUE THREAD

**Issue by dashkevych** [WordPress/gutenberg#32443]
I am wondering if there are any plans to use CSS Grid instead of Flexbox?

## What problem does this address?
At the moment, the Query block uses `flexbox` for the query container when the Grid View option is selected. Below are the styles that the Query block currently uses (WP 5.8-alpha-51064).

**Default styles:**

```css
.wp-block-query-loop.is-flex-container {
    flex-direction: row;
    display: flex;
    flex-wrap: wrap;
}

.wp-block-query-loop.is-flex-container li {
    margin: 0 0 1.25em 0;
    margin-right: 0px;
    width: 100%;
}

@media (min-width: 600px) {
  .wp-block-query-loop.is-flex-container li {
      margin-right: 1.25em;
  }
}
```

**3 columns layout styles:**

```css
@media (min-width: 600px) {
  .wp-block-query-loop.is-flex-container.is-flex-container.columns-3 > li {
      width: calc((100% / 3) - 1.25em + (1.25em / 3));
  }
}
```

## What is your proposed solution?

I believe that by using CSS Grid, we could reduce CSS styles used for this block.

**Default styles:**

```css
.wp-block-query-loop.is-flex-container {
    display: grid;
    grid-template-columns: 1fr;
    grid-gap: 1.25em;
}
```

**3 columns layout styles:**

```css
@media (min-width: 600px) {
  .wp-block-query-loop.columns-3 {
     grid-template-columns: 1fr 1fr 1fr;
  }
}
```
