### ISSUE TITLE
Gradient backgrounds should be set with `background-image` instead of `background`

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#32787]
I have been attempting some work with `background-clip: text` like so:

```
-webkit-background-clip: text;
-webkit-text-fill-color: transparent; 
-moz-background-clip: text;
-moz-text-fill-color: transparent;
```

To create a gradient effect on text like this:

![gradient-text](https://user-images.githubusercontent.com/1816309/122438598-7e6fd380-cf60-11eb-81a4-186fd4ed04ba.jpg)

However, this does not work when using either gradient presets or a custom gradient.  Both use `background: $gradient` instead of `background-image: $gradient` in the CSS output.  By changing those to use `background-image`, the effect works.

I'm not sure if there are any historical reasons for going with `background`, but I'd love to see us move to only targeting `background-image`.

**Comment by Azragh** [comment]
Agreed. `background:` affects
```
background-attachment
background-clip
background-color
background-image
background-origin
background-position
background-repeat
background-size
```
IMHO it's bad practice to use shorthand properties in inline styles alltogether.

**Comment by pbearne** [comment]
Hi all

I have started this but it seems that that change the background to background-color(or backgroundColor in js) if it is a straight color and to background-image(backgroundImage) if gradient 

this change is in 100's of files so I what to reach back to make sure that me removing all the shorthand background is what you need/want

note: the only shorthand background have left is `background: none`

here is the branch I have started https://github.com/pbearne/gutenberg/tree/%2332787_replace_background_css_with_background-(type)

**Comment by skorasaurus** [comment]
PR for this is also at https://github.com/WordPress/gutenberg/pull/35036

**Comment by bph** [comment]
@ajlende Is this is something you could take on... ?

**Comment by devanshijoshi9** [comment]
Hi @ajlende 👋 I have raised a new PR for this enhancement as some other components also have gradient background. Could you please review and let me know if any further modification is required? Thank you.

PR - https://github.com/WordPress/gutenberg/pull/57246

**Comment by justintadlock** [comment]
@devanshijoshi9 - I believe this needs to be fixed in the Style Engine. It's not just a fix in the CSS files. Specifically, this ticket deals with presets and other values set on a block as a background gradient.

**Comment by ramonjd** [comment]
I've added this to the task list for background image block supports:

- https://github.com/WordPress/gutenberg/issues/54336

**Comment by tcmulder** [comment]
Any movement on this? My use case is that I'm using [section styles ](https://make.wordpress.org/core/2024/06/24/section-styles/) to add a background color to groups (among other changes like text colors). Then, I can add a background image to the group, and if the image has transparency, the group's section style background color shows through—looks great. This _should_ work also for gradients, but since they use `background` rather than `background-image`, the color gets reset back to transparent !important.

For now, I'm using this sorta ugly hack to replace the `background` values:

```php
/**
 * Replace gradient background with background-image
 * 
 * Gutenberg adds a gradient background via the overreaching `background`
 * property: here we replace it with the more appropriate `background-image` property.
 * This allows us to override background values without needing to use !important for
 * each and every one.
 * 
 * IMPORTANT NOTE: if you are not using
 * `add_filter( 'should_load_separate_core_block_assets', '__return_true' )`
 * you will need to use wp_head instead of wp_footer.
 */
add_action( 'wp_footer', function() {
    global $wp_styles;
    $css = $wp_styles->get_data( 'global-styles', 'after' );
    if ( ! empty( $css ) && is_array( $css ) ) {
        $modified_css = array_map( function( $block ) {
            $result = preg_replace(
                '/\.has-([a-zA-Z0-9-]+)-gradient-background{background:\s*var\(--wp--preset--gradient--([a-zA-Z0-9-]+)\)\s*!important;}/i',
                '.has-$1-gradient-background{background-image: var(--wp--preset--gradient--$2) !important;}',
                $block
            );
            return $result;
        }, $css );
        $wp_styles->add_data( 'global-styles', 'after', $modified_css );
    }
}, 5 );

```

**Comment by justintadlock** [comment]
I eventually solved my initial issue with this (S)CSS:

```scss
///
/// Adds a clip-text/knockout style to the block. Essentially, this allows the
/// background to apply to the text itself instead of the background of the
/// entire element.
///
.wp-block-heading.is-style-knockout {
	background-clip: text !important;
	color: transparent !important;

	// Always remove text-shadow, which obscures the background with this
	// technique for knockout text.
	text-shadow: none !important;

	// Add a default gradient background if the user hasn't chosen one.
	&:not(.has-background) {
		background: var(--wp--preset--gradient--cool-to-warm-spectrum);
	}

	// Sub-elements, such as links, need to inherit the heading color for
	// the clip-text to work.
	> * {
		color: inherit !important;
	}
}
```

That's for a block style variation named `knockout`.

I haven't looked at it in a while, so it might need some cleanup.

---

Anyway, the issue still stands, despite having figured out a pure CSS method of doing this. There are other use cases that would be served by fixing this.
