### ISSUE TITLE
Remove block alignment wrapper in editor

### ISSUE THREAD

**Issue by keithdevon** [WordPress/gutenberg#33142]
## What problem does this address?

In the editor, blocks with alignment (e.g. Wide, Full) are wrapped in a div with the .wp-block class and a data-align attribute.

All other block specific classes are then added to a child of this block. 

```
<div class="wp-block" data-align="full">
    <div style="background-color: rgb(185, 204, 70);" class="wp-block-group has-brand-green-background-color has-background" ...>...</div>
</div>
```

This means that selectors such as `.wp-block-group.alignfull.has-background` have no effect in the editor.

This leads to two problems (that I know of):

1. Frontend theme styles often break and have to be recreated with specific editor stylesheets.
2. Sometimes, useful selector rules, particularly nth-of-type, nth-child, and adjacent operators, cannot be used in the editor.

For example, if you want to remove margins between two full-width groups with background colours you might do something like this:

```
.wp-block-group.alignfull.has-background + .wp-block-group.alignfull.has-background {
    margin-top: -50px;
}
```

This has no effect in the editor as there is no elelment that can contain all of these classes - they are split onto two levels of div.

Do we need the wrapper with .wp-block and the data-align? Blocks with no alignment don't have a wrapper, so I'm assuming it isn't used as a hook for the editor UI.

## What is your proposed solution?

Remove the `<div class="wp-block" data-align="full">` div and add the wp-block and alignment classes to the block level element.

E.g. `<div class="wp-block wp-block-group has-background alignfull ..." ...>...</div>`

If needed, the data-align attribute can be added in addition to the alignment class.

E.g. `<div class="wp-block wp-block-group has-background alignfull ..." data-align="full" ...>...</div>`

**Comment by justintadlock** [comment]
Wait until you start fighting `<style>` (group inherit layout styles) and `<svg>` (duotone) tags stuck between blocks too.  The following is just covering something like the 80% - 90% of cases I've seen.  I'm not even sure if it can be fixed, but removing the `[data-align]` wrappers would sure help.

```css
.is-root-container > :first-child,
.is-root-container > style:first-child + [class*=wp-block],
.is-root-container > [data-align]:first-child > [class*=wp-block]:first-child,
.is-root-container > .block-editor-block-list__block:first-child > :first-child,
.is-root-container > style:first-child + [data-align] > :first-child,
.is-root-container > [style*=hidden]:first-child + style + [data-align] > :first-child,
.wp-block-cover__inner-container > style:first-child + [class*=wp-block],
.wp-block-template-part > style:first-child + [class*=wp-block],
.wp-block-embed > .wp-block-embed,
.wp-block-spacer + [data-align] > :first-child,
.wp-block-group > [data-align]:first-child > :first-child,
.wp-block-group > style:first-child + .wp-block-group,
.wp-block-group > style:first-child + [data-align] > :first-child,
[data-align=full] + [data-align=full] > [class*=wp-block]:first-child,
[data-align=full] > [class*=wp-block]:first-child > [data-align=full]:first-child > [class*=wp-block]:first-child,
[data-align=full] + [style*=hidden] + [data-align=full] > [class*=wp-block]:first-child,
[data-align=full] + [style*=hidden] + style + [data-align=full] > [class*=wp-block]:first-child,
[data-align=full] + style + [data-align=full] > [class*=wp-block]:first-child,
[data-align=full] + style + style + [data-align=full] > [class*=wp-block]:first-child,
[data-align=full] + style + [style*=hidden] + [data-align=full] > [class*=wp-block]:first-child,
[data-align=full] + style + [style*=hidden] + style + [style*=hidden] + [data-align=full] > [class*=wp-block]:first-child {
	margin-top: 0;
}
```

**Comment by richtabor** [comment]
After testing theme.json themes today, I noticed this wasn't an issue (though I couldn’t really nail it down). Are the standard block margins removed if a theme has a theme.json file?

**Comment by justintadlock** [comment]
> After testing theme.json themes today, I noticed this wasn't an issue (though I couldn’t really nail it down). Are the standard block margins removed if a theme has a theme.json file?

The `[data-align]` wrapper is there for me regardless of whether I am using a theme with a `theme.json`.

I'm not sure what the standard block margins are.  Margins for me are added by the theme.

**Comment by richtabor** [comment]
@justintadlock The wrapper is still there, but the default block margins are removed from themes with theme.json (per this PR https://github.com/WordPress/gutenberg/pull/30375 I found). That's great for theme.json themes, but not for any current themes. :/

**Comment by justintadlock** [comment]
The source of default block margins doesn't really matter.  As long as the `[data-align]` wrapper is there, it's pretty much impossible to correctly use sibling selectors.

For example, you can't kill margins for this:

```html
<div data-align="full">
	<div class="wp-block-example"></div>
</div>


<div data-align="full">
	<div class="wp-block-example"></div>
</div>
```

With CSS like:

```css
.wp-block-example {
	margin-top: 2rem;
}

.wp-block-example.alignfull + .wp-block-example.alignfull {
	margin-top: 0;
}
```

That CSS works on the front end because the HTML is this:

```html
<div class="wp-block-example alignfull"></div>
<div class="wp-block-example alignfull"></div>
```

You can certainly do some weird and hacky workarounds to sort of make it work in the editor...until it doesn't.  And, this is just the most basic of examples.

`:first-child`, `:last-child`, and `:nth*` often get squashed by this too.

And, it's not all about margins.  It can be any style rule -- for example, a theme author might want to add/remove bottom/top borders between siblings, alternate default background colors, or a million other things.
