### ISSUE TITLE
Query Loop: Add "Stack On Mobile" toggle for Grid View

### ISSUE THREAD

**Issue by beafialho** [WordPress/gutenberg#34145]
Not sure if this has been discussed somewhere else. If that's the case, please point me there.

In the Columns block, there's a toggle that allows you to choose whether columns stack on mobile or not:

<img width="297" alt="S9GA-8hgcv" src="https://user-images.githubusercontent.com/65220155/129930001-8c6bb92b-20bd-44c2-9e95-991048e8ba62.png">

In the Query Loop block, when we select Grid View for posts, they always show up stacked on mobile because this option doesn't exist. That prevents us from achieving designs like the one below on mobile.

<img width="293" alt="Captura de ecrã 2021-08-18, às 16 57 55" src="https://user-images.githubusercontent.com/65220155/129931525-4824eddb-d137-4a83-8066-355d3d9da245.png">

| Mockup | Gutenberg |
| ----------- | ----------- |
| ![More Posts_2](https://user-images.githubusercontent.com/65220155/129931013-e7ad5462-6a0b-4127-a9c1-ee39dde07b79.jpg) | ![Frame 13](https://user-images.githubusercontent.com/65220155/129931175-e02e93a1-95b8-4c70-abd2-0d99a1f1d180.jpg) |

I propose we add it to allow more flexibility to create layouts.

**Comment by DHWP** [comment]
How is this still normal priority? this makes the query block unusable on a site that wants to display well on mobile...

**Comment by Paldom** [comment]
Is this still on the roadmap after 2 years? 
This would be a very useful feature.

**Comment by Paldom** [comment]
Meanwhile a workaround (Styles / ADDITIONAL CSS)

```css
@media(max-width: 781px) {
  .wp-block-post-template.is-flex-container.is-flex-container > li {
    width: auto !important;
  }
}
```

**Comment by osirismqz** [comment]
> Meanwhile a workaround (Styles / ADDITIONAL CSS)
> 
> ```css
> @media(max-width: 781px) {
>   .wp-block-post-template.is-flex-container.is-flex-container > li {
>     width: auto !important;
>   }
> }
> ```

Does not work anymore.

This worked for me:

```css
@media(max-width: 600px) {
  .wp-block-post-template-is-layout-grid.wp-block-post-template-is-layout-grid.wp-block-post-template-is-layout-grid.wp-block-post-template-is-layout-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr)) !important;
  }
}
```

Maybe we need to wait another year for this basic feature to be included.
