### ISSUE TITLE
Custom property for admin bar height

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#34413]
## What problem does this address?

When the admin bar is displayed, elements using a `sticky` or `fixed` position in the header need some adjustments to accomodate from the admin bar height properly.

## What is your proposed solution?

I have found that a custom property describing the admin bar height is a nice solution.

Here's what I use

```css
.admin-bar {
    --global--admin-bar--height: 32px;
}

@media only screen and ( max-width: 782px ) {

    .admin-bar {
        --global--admin-bar--height: 46px;
    }

}
```

Then, when you have an element that need an adjustment, you can use that custom property with a fallback, like that : 

```css
top: var(--global--admin-bar--height, 0);
```

I think it would be great to have a standardized custom property (`--wp--admin-bar--height` ?) outputed by WordPress and not by the theme.

What do you think ?
