### ISSUE TITLE
#34334 Breaks styles in theme's styles.css

### ISSUE THREAD

**Issue by mkkeck** [WordPress/gutenberg#34575]
### Description

#34334 Breaks some styles in themes-name/styles.css.
For example responsive font sizes defined in theme's styles.css won't work.

### Step-by-step reproduction instructions

For example I 've follow rules in my CSS file which enables responsive font sizes:

```css
.has-large-font-size {
  font-size: calc(1.275rem + .3vw)
}
@media (min-width: 1200px) {
  .has-large-font-size {
    font-size:1.5rem
  }
}
```

But with the #34334 there's an inline style added, which merges WordPress default global styles with the settings from theme.json which set's:
```css
body {
  /* ... */
  --wp--preset--font-size--small: .875rem;
  --wp--preset--font-size--normal: 1rem;
  --wp--preset--font-size--medium: 1.25rem;
  --wp--preset--font-size--large: 1.5rem;
  --wp--preset--font-size--huge: 2.25rem;
}
.has-large-font-size {
  font-size: var(--wp--preset--font-size--large) !important;
}
```

The `!important` flag is here the problem.

I think this could break much other themes, so please add a filter or hook, to modify or disable the `global-styles`.

### Environment info

- WordPress 5.8, default Gutenberg
- Browsers: all
- Not theme specific

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
