### ISSUE TITLE
Allow maximum width clamping of contentSize in theme.json

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#34772]
## What problem does this address?

Currently if you set a `contentSize` in `theme.json` then any blocks which are direct children of the Group block (if "Inherit layout" is turned on) will output css such as:

```css
.wp-container-{SOME_ID} > * {
    max-width: 70vw;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

In this case I'm using the Group block to divide up "sections" of my page. I want the group to be full width but the block contained within it to be visually centered and approx 70% of the viewport.

The CSS above works well until you reach very large screen sizes. At this point what you typically want is to "clamp" the maximum width of the inner content so that it doesn't become excessive. Typically I would use a `max-width` for this set to something like `70em`.

Unfortunately the generated CSS is already monopoloising the max-width. Moreover, there is no way within the `theme.json`'s `layout` config (or within the editor UI) to set a "max width" value.

## What is your proposed solution?

I propose:

1. We switch to using `width` to set the width of the inner blocks - is there a good reason to use `max-width`?
2. We add a new property to `layout` which is `maxSize` (or something) which would be used to output a CSS `max-width` for the inner blocks.
3. We add UI to the editor to allow the user to set a max width when they are no inheriting the default layout.

Desired CSS output:

```css
.wp-container-{SOME_ID} > * {
   width: 70vw;
   max-width: 70em;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

I know @youknowriad worked on this so I'd love to have his input as he may have additional insight here.

I will say that this requirement came directly from me trying to build a block theme and running into this issue.
