### ISSUE TITLE
`theme.json` can't have comments

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#35099]
## What problem does this address?

`theme.json` is a configuration file maintained by humans, rather than a data-interchange file used by software. Comments are an essential feature of any configuration file, in order to document important decisions, explain things that aren't obvious, etc. For example:

```json
"settings": {
		"spacing": {
			"//blockGap": "The design calls for a 24px gap. Coincidentally, that's the default value that Gutenberg defines. The default could change in the future, though, so this should be explicitly set.",
			"blockGap": "24px",
```

JSON tooling usually (and [mistakenly](https://github.com/zaach/jsonlint/issues/50#issuecomment-512435560)) doesn't allow comments, though. Many tools will strip them out, or just fail to run. There are lots of workarounds, but the half dozen I've tried have all had significant downsides. For example:

```json
"settings": {
		"custom": {
			"alignment": {
				"//alignedMaxWidth": "Foo bar blah blah blah...",
				"alignedMaxWidth": "50%"
			},
```

...results in:

```css
--wp--custom--alignment----aligned-max-width: Foo bar blah blah blah...;
```

## What is your proposed solution?

Consider using [JSON5](https://json5.org/) instead of JSON. It's a superset, so there aren't any back-compat issues.

If that's done, we'll need to document it, otherwise devs will assume they can't use comments and miss out on the benefits.

**Comment by glendaviesnz** [comment]
Is adding a schema link into theme.json an alternative approach to comments? eg.  `"$schema": "https://json.schemastore.org/theme-v1.json"`,  @ajlende has started a theme.json schema already at https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/theme-v1.json which I believe can be extended  to add descriptions to all of the fields, which when used with an IDE that supports it will show tooltips to developers.

**Comment by brownboycodes** [comment]
you can also write ✍🏽  the configuration files 📝  in YAML and convert it to JSON with tools like https://www.json2yaml.com/convert-yaml-to-json

YAML is also a superset of JSON and uses python 🐍  like line separation & indentation and commenting with `# comment`, and its as easy as JSON

#### theme configuration file in YAML
```yaml 
settings:
  spacing:
    # blockGap: "The design calls for a 24px gap. Coincidentally, that's the default value that Gutenberg defines. The default could change in the future, though, so this should be explicitly set."
    blockGap: 24px
  custom:
    alignment:
      # alignedMaxWidth: Foo bar blah blah blah...
      alignedMaxWidth: 50%
```

#### the equivalent JSON code converted from YAML with https://www.json2yaml.com/convert-yaml-to-json
```JSON
{
  "settings": {
    "spacing": {
      "blockGap": "24px"
    },
    "custom": {
      "alignment": {
        "alignedMaxWidth": "50%"
      }
    }
  }
}
```
