### ISSUE TITLE
Extend drop cap customizations with `theme.json`

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/gutenberg#36122]
## What problem does this address?
While working on TwentyTwentyTwo - it was noted that the dropcap layout looked tight (bad line-height) or undesirable [Drop cap needs attention/styling #180](https://github.com/WordPress/twentytwentytwo/issues/180) on certain user's systems. Currently, it was agreed that dropcap support was not imperative for TwentyTwentyTwo. 

Note: this is not imperative to WP 5.9 release or TwentyTwentyTwo progress at all.

However, it would be ideal to extend drop cap styling and support to allow for some `theme.json` settings to adjust things like: `line-height`, `font-weight`, and even `color` or `margin`.

## What is your proposed solution?

Extend drop cap support and put additional mechanisms in place in `theme.json` to allow theme authors to declaratively define drop cap styling.

Possible related conversation and considerations: [theme.json: whether or not to allow targetting settings that are specific to the block #35114](https://github.com/WordPress/gutenberg/issues/35114)

> Is it the objective to be able to configure every option in core blocks through theme.json? 
It would be so helpful to be able to preconfigure things like text alignment, vertical alignment, block alignment, block width, media position, and so on..

**Comment by justintadlock** [comment]
Yep, I ended up having to basically create a whole set of drop-cap properties so that I could overwrite this in upcoming global styles variation `.json` files:

```css
.has-drop-cap:not(:focus)::first-letter {
	font-family: var( --wp--custom--drop-cap--typography--font-family, inherit );
	font-size: var( --wp--custom--drop-cap--typography--font-size, 5.5em );
	font-weight: var( --wp--custom--drop-cap--typography--font-weight, 700 );
	font-style: var( --wp--custom--drop-cap--typography--font-style, normal );
	line-height: var( --wp--custom--drop-cap--typography--line-height, .85 );
	margin: var( --wp--custom--drop-cap--spacing--margin, 0.05em 0.1em 0 0 );
	padding: var( --wp--custom--drop-cap--spacing--paddig, 0 );
}
```
