### ISSUE TITLE
The margin added at the top level styles (for body) in theme.json is override by a margin added from gutenberg

### ISSUE THREAD

**Issue by overclokk** [WordPress/gutenberg#36147]
### Description

If I add a margin property to the theme.json at the top level styles the style generated is overwritten by a style added by the gutenberg plugin.

I also tried with the 2022 theme and gutenberg active.

### Step-by-step reproduction instructions

Gutenberg plugin is activated.
Theme 2022 activated

Add this to theme.json

```json
{
	"styles": {
		"spacing": {
			"margin": "0 5rem",
			"padding": "0"
		},
	}
}
```

See the source of the page.
In my test I see this in the source:

```css
body { // This is added by the theme.json
	margin: 0 5rem;
	padding: 0;
	--wp--style--block-gap: 1.5rem;
}
body { margin: 0; } // This is added by the gutenberg plugin
```

### Environment info

WP latest
Gutenberg Latest fro repo
Theme 2022

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
