### ISSUE TITLE
Add readonly styles

### ISSUE THREAD

**Issue by sybrew** [WordPress/gutenberg#3615]
## Issue Overview

There are no styles for `input[readonly]`, yet.

## Steps to Reproduce (for bugs)

1. Add a `<input type=text readonly>` meta field in any meta box.

## Expected Behavior

![image](https://user-images.githubusercontent.com/7662236/33137600-aee1a090-cfa8-11e7-8fe8-8059457132f7.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/7662236/33137614-bb25a05e-cfa8-11e7-9399-15f7ee8330b7.png)

## Possible Solution

```css
input.readonly, 
input[readonly], 
textarea.readonly, 
textarea[readonly] {
	background-color: #eee;
}
```

## Todos
- [ ] Tests
- [ ] Documentation
