### ISSUE TITLE
Allow modification of theme.json global styles

### ISSUE THREAD

**Issue by coreyworrell** [WordPress/gutenberg#36792]
## What problem does this address?

There is currently no way (that I can tell) to modify the output of the global styles when using `theme.json`.

Example use case: creating a color system to allow for different opacity of text and background colors.

Example setup:

`style.css` (or equivalent)

```css
.has-text-color {
  color: rgb(var(--color) / var(--text-opacity, 1));
}

.has-background {
  background-color: rgb(var(--background-color) / var(--background-opacity, 1));
}

.has-1-text-opacity {
  --text-opacity: .1;
}

.has-2-text-opacity {
  --text-opacity: .2;
}

.has-1-background-opacity {
  --background-opacity: .1;
}

/* etc... */
```

`theme.json`

```json
{
  "settings": {
    "color": {
      "palette": [
        {
          "name": "Primary",
          "slug": "primary",
          "color": "50, 150, 255"
        }
      ]
    }
  }
}
```

`global-styles` (`#global-styles-inline-css`)

```css
body {
  --wp--preset--color--primary: 50, 150, 255;
}

.has-primary-color {
  --color: var(--wp--preset--color--primary);
  /* or */
  color: rgb(var(--wp--preset--color--primary) / var(--text-opacity, 1));
}

.has-primary-background-color {
  --background-color: var(--wp--preset--color--primary);
  /* or */
  background-color: rgb(var(--wp--preset--color--primary) / var(--background-opacity, 1));
}
```

## What is your proposed solution?

If those styles were filterable then this could be easily done. The only solution I could see now is to dequeue the `global-styles` and then include our own CSS, but doing this feels like going against WordPress and not future-proof.

**Comment by oandregal** [comment]
Hi Corey, thanks for sharing your use case, it's very valuable.

I was looking at it, and this is how I understand it could be done with the current system. The preset colors can use CSS variables and will show up fine in the editor. So, if you do:

```json
{
  "settings": {
    "color": {
      "palette": [
        {
          "name": "Primary",
          "slug": "primary",
          "color": "rgb(50,150,255, var(--wp--custom--opacity, 1))"
        }
      ]
    }
  }
}
```

the only thing that remains is how you decide which opacity belongs to which block. For simplification, let's say that you'd want all paragraphs to have a 0.3 opacity. The only thing you'd have to do is to enqueue this CSS from your plugin:

```css
p {
  --wp--custom--opacity: .3;
}
```

Is this in line with what you were thinking?
