### ISSUE TITLE
Image left/right alignment escapes it's container in the editor

### ISSUE THREAD

**Issue by creativecoder** [WordPress/gutenberg#37504]
### Description

When an image is left or right aligned, how it looks on the editor does not match the actual site.

### Step-by-step reproduction instructions

1. Create a new post or page
2. Insert an image block, make it relatively small, and set it to left aligned
3. Insert a spacer block after it
4. Insert some text after that

I expect that the image is left aligned with the text, but it's not

### Screenshots, screen recording, code snippet

**Editor**

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/1699996/146625781-8f4776d5-5151-448e-8210-3669d7f0d916.png">

**Front end**

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1699996/146625806-2a95b549-7876-4d90-bc84-f197dd94376e.png">

---

Note that the float for alignment is applied to the block container in the editor

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1699996/146625944-b7cd067a-6ad8-4137-8d5f-eb978a17643c.png">

But the figure element inside the container on the front-end

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/1699996/146625970-8996e66c-5aff-4a50-918e-08b8c4a724a8.png">

### Environment info

- WP 5.9, Gutenberg 12.1.0-rc.1
- Firefox, macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by maxwrlr** [comment]
I have the same problem. I temporarily solve it with an editor-style:
```css
.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > .wp-block[data-align="left"] {
	margin-left: calc((100% -  <value-of-settings.layout.contentSize-of-theme.json>   ) / 2) !important;
}
```
