### ISSUE TITLE
Don't render layout styles if block styling is not applied

### ISSUE THREAD

**Issue by MatzeKitt** [WordPress/gutenberg#38280]
### Description

We explicitly didn't add theme support for `wp-block-styles` since we need consistency in our styles (that are output to multiple hundreds of websites. Since the layout styles in `gutenberg_render_layout_support_flag()` make only sense if you use the `wp-block-styles`, it's even harder to hold this consistency.

Thus, these layout styles should only be rendered if `add_theme_support( 'wp-block-styles' )` is added to the theme since it may break things very badly.

Why this is a bug in my opinion? Because if you decided to not include the core block styles, the core shouldn't add any styling for the blocks, but it does.

Or at least, allow removing these styles by not using static functions but proper function names that can be removed by `remove_action()`.

### Step-by-step reproduction instructions

1. Use a theme without `add_theme_support( 'wp-block-styles' )`
2. Apply custom styling for the blocks, e.g. the buttons block, like this:

```scss
.wp-block-buttons {
	.wp-block-button {
		display: inline-block;
		margin-right: 1rem;
		
		&:last-child {
			margin-bottom: 2.4rem;
			margin-right: 0;
		}
	}
	
	&.alignright {
		.wp-block-button {
			margin-left: 1rem;
			margin-right: 0;
			
			&:last-child {
				margin-left: 0;
			}
		}
	}
	
	&.is-content-justification-center {
		justify-content: center;
	}
}

.wp-block-button {
	&.aligncenter,
	&.is-content-justification-center {
		text-align: center;
	}
	
	&.alignright {
		/* rtl:ignore */
		text-align: right;
	}
	
	&:last-child {
		margin-bottom: 0;
	}
	
	// override auto-generated margin: 0; in WP 5.9
	&.wp-block-button {
		margin-bottom: 2.4rem;
	}
}

.wp-block-button__link {
	display: inline-block;
}

```

3. See, how WP 5.9's `.wp-container-<id>` breaks things depending on the alignment usage.

### Environment info

- WordPress 5.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No
