### ISSUE TITLE
Gallery Block: wrapper container for gallery items

### ISSUE THREAD

**Issue by CruelDrool** [WordPress/gutenberg#38296]
The last picture(s) in a gallery always has gap between them and the `figcaption` element. The old gallery block had a wrapper with the CSS-class `.blocks-gallery-grid` that I could target with a negative value for `margin-bottom`, and thus eliminate the gap. Besides that, it was also possible to set the flex [order](https://developer.mozilla.org/en-US/docs/Web/CSS/order) of the gallery itself and the gallery caption (e.g. putting the caption first).

## Proposed HTML-output
```HTML
<figure class="wp-block-gallery has-nested-images columns-default is-cropped">
   <div class="wp-block-gallery__wrapper">
      <figure class="wp-block-image size-large">...</figure>
      <figure class="wp-block-image size-large">...</figure>
      <figure class="wp-block-image size-large">...</figure>
      <figure class="wp-block-image size-large">...</figure>
   </div>
   <figcaption class="blocks-gallery-caption">Gallery caption</figcaption>
</figure>
```
### CSS
```CSS
.wp-block-gallery.has-nested-images {
    display: flex;
    /* flex-wrap: wrap; */
}

.wp-block-gallery__wrapper {
    display: flex;
    flex-wrap: wrap;
}
```

**Comment by aaronrobertshaw** [comment]
Hi @CruelDrool 👋 

Thanks for submitting this issue. 

I understand it can be inconvenient if you need to tweak some styles to take advantage of the new Gallery. 

Without covering the full history behind the change in gallery markup, the primary driving factor was to satisfy the [W3C accessibility guidelines for collections of images](https://www.w3.org/WAI/tutorials/images/groups/#a-collection-of-images). These have the `<figcaption>`, along with the `<figure>` elements, as direct children of the gallery i.e. the `<figure role="group">` element. Unfortunately, adding a wrapping around the images would break this.

The good news though is you can still achieve the styling you've outlined in this issue without any markup changes.

The gallery [already has a flex layout](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/gallery/style.scss#L6) so the caption can be reordered within it via the application of an `order` style, e.g. `order: -1;` to make the caption appear before the images.

Regarding the gap between gallery items, rather than applying styles to the proposed wrapper, we can instead target the caption itself and apply the negative margin to that. This can also take into account whether the caption is being reordered to appear first etc.

I've tested this across multiple browsers, Chrome, Safari, Firefox, Edge etc. and it's working for me in all of them with styles such as below:

```css
/* Style to counter margin */
.blocks-gallery-caption {
	/* Counter the margin for the gallery caption while still supporting custom gallery gutter sizes */
	margin-top: calc( var(--gallery-block--gutter-size, 16px) * -1 );
	
	/* Following styles were just for easier testing and visual confirmation of results */
	background: lightblue;
	padding: 10px 0;
}

/* Style to reorder gallery caption */
.blocks-gallery-caption {
	order: -1px;
}
```

<details>
<summary>Here's a demo of these styles in action</summary>


https://user-images.githubusercontent.com/60436221/151729242-5aba71ab-34b0-4152-8106-ca35decdf93f.mp4

</details>

If this helps solve your styling needs, I'd recommend closing this issue.

Thanks again for the feedback, it is appreciated 👍

**Comment by CruelDrool** [comment]
Thanks for the reply!

To add some context, my block elements have got a padding of 5px (with a background colour and a border),  All `figcaption `got a a margin (top and bottom) at 6px. I wanted the last pictures in the galleries to have the same distance between them and the `figcaption` as the other blocks, which would be the 6px. Hence the request for a wrapper, since that would make it easier to do so. I didn't have accessibility in mind when I did that.

Your idea for negative `margin-top` gave me some inspiration. Snippet of what I'm trying out:

```CSS
:root {
	--block-image--padding: 5px;
	--figcaption--margin: 6px;
	/* Keep the same distance between images as the block padding. */
	--gallery-grid--margin: var(--block-image--padding);
}

figure.wp-block-gallery {
	/* Remove default padding on the bottom */
	padding-bottom: 0;
}

.wp-block-gallery figcaption.blocks-gallery-caption
{
	/* Recalculate new margins */
	
	/* Use --gallery-grid--margin as default/fallback if --gallery-block--gutter-size isn't defined  */
	margin-top: calc(var(--gallery-block--gutter-size, var(--gallery-grid--margin)) * -1 + var(--figcaption--margin));
	margin-bottom: calc(var(--figcaption--margin) + var(--gallery-grid--margin));
}
````
However, all that just starts to break down as the gutter size increases beyond 35px. The distance between the last few images and the `figcaption` stays the same, of course, but as you can see in this picture:

![image](https://user-images.githubusercontent.com/17357859/151734661-99eb7322-4ea4-44a0-a370-1502c1346ada.png)

Admittedly, in this I'm using a large value for `--gallery-block--gutter-size` to exaggerate.
