### ISSUE TITLE
Block assets have more CSS than expected when Gutenberg is enabled

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#39393]
### Description

See full report at https://github.com/WordPress/gutenberg/pull/38712#issuecomment-1039363061

For themes that have `should_load_separate_block_assets` enabled, the styles for blocks are loaded as separate embedded stylesheets. The expected content of every stylesheet is the contents of the `style.css` of the block and, optionally, if the theme opts-in, the `theme.css` as well.

However, when Gutenberg is active, the block stylesheet has more contents than expected.

### Step-by-step reproduction instructions

- Use WordPress 5.9.X with the Gutenberg plugin active.
- Use a block theme (by default they have `should_load_separate_block_assets` enabled).
- Go to the front-end and inspect the `wp-block-group-inline-css`. It contains:

```css
.wp-block-group {
  box-sizing: border-box;
}
:where(.wp-block-group.has-background) {
  padding: 1.25em 2.375em;
}
.wp-block-group:where(.has-background) {
  padding: 1.25em 2.375em;
}
```

However, when Gutenberg is not enabled it instead outputs:

```css
.wp-block-group {
  box-sizing: border-box;
}

.wp-block-group:where(.has-background) {
  padding: 1.25em 2.375em;
}
```
