### ISSUE TITLE
Global styles: Lower selector specificity for declaring CSS properties (CSS variables)

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#40042]
### Description

Currently [WordPress global styles](https://make.wordpress.org/core/2022/01/08/updates-for-settings-styles-and-theme-json/) declare CSS properties/variables on `body` selector:
```css
body {
	--wp--preset--color--black: #000000;
	...
}
```

This seems to be quite high specificity as themes and plugins can not use `:root` or `html` now to override those CSS variables.

It would be great if WordPress CSS variables in global styles are declared on `:where(:root)` selector, which provides low enough specificity:
```css
:where(:root) {
	--wp--preset--color--black: #000000;
	...
}
```

That way also `:root` selector used in themes and plugins can override WordPress global styles CSS variables with ease.

There is really no need to set such high specificity (meaning using `body` selector) for declaring default CSS variables in my opinion.

### Step-by-step reproduction instructions

Not applicable here.

### Environment info

WordPress 5.9+

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No
