### ISSUE TITLE
Proposal: Allow defining a typography-scale in theme.json

### ISSUE THREAD

**Issue by aristath** [WordPress/gutenberg#40726]
## What problem does this address?
Defining font-sizes for all heading levels is a tedious task and can lead to visual inconsistencies.
Using a typography scale is not a new concept... Typography scales have been used in print for centuries and they are harmonious and visually pleasing. Implementing typography-scales in theme.json would allow theme developers and designers to accomplish sane, consistent results with minimum effort. 

Typography-scale calculator which can be used to show an easy example of how typo-scales work: https://type-scale.com

## What is your proposed solution?

Define a `settings.typography.scale` numeric value (float) in `theme.json` files.

This can then generate something like 
```css
body {
  --wp--preset--typography--scale: 1.2; /* The scale */
  --wp--preset--font-size--normal: 1rem;

  /* Auto-calculated values */
  --wp--preset--font-size--s: calc(var(--wp--preset--font-size--normal) / var(--wp--preset--typography--scale));
  --wp--preset--font-size--xs: calc(var(--wp--preset--font-size--s) / var(--wp--preset--typography--scale));

  --wp--preset--font-size--l: calc(var(--wp--preset--font-size--normal) * var(--wp--preset--typography--scale));
  --wp--preset--font-size--xl: calc(var(--wp--preset--font-size--l) * var(--wp--preset--typography--scale));
  --wp--preset--font-size--xxl: calc(var(--wp--preset--font-size--xl) * var(--wp--preset--typography--scale));
  --wp--preset--font-size--xxxl: calc(var(--wp--preset--font-size--xxl) * var(--wp--preset--typography--scale));
}
```
Font-sizes for elements can then be auto-calculated based on that value:
```css
h1 { font-size: var(--wp--preset--font-size--xxxl); }
h2 { font-size: var(--wp--preset--font-size--xxl); }
h3 { font-size: var(--wp--preset--font-size--xl); }
h4 { font-size: var(--wp--preset--font-size--l); }
h5 { font-size: var(--wp--preset--font-size--normal); }
h6 { font-size: var(--wp--preset--font-size--s); }
```

_Note: The var-names above are just an example to show the concept, not actual proposals for var-names_

The benefits of an implementation like this would be:
* Minimum effort for consistent and proportional designs
* The ability to change all font-sizes at once if desired. Usually when we change the font-size of `h3` and make it larger for example, we then have to change the size of `h2` to make it look larger than h3, then once that's done we need to go over and change the size of `h1` elements etc.
* In the future we can add a slider in the global-styles to allow users to tweak the value
* If users don't define custom font-sizes like small/large/xlarge etc, we have the opportunity to standardize these sizes by autogenerating them based on a defined typography-scale.
* Significantly reduced `theme.json` files. In most themes, using a typography scale would eliminate (or significantly reduce) the need to define `settings.typography.fontSizes`, `styles.elements.h1`, `styles.elements.h2`, `styles.elements.h3`, `styles.elements.h4`, `styles.elements.h5`, `styles.elements.h6`.
