### ISSUE TITLE
Arrow for Parent Block Selector

### ISSUE THREAD

**Issue by jon4896** [WordPress/gutenberg#41924]
## What problem does this address?

Understanding block nesting and navigating to parent blocks is pertinent to a novice user in creating and managing content with the Gutenberg editor.

I remember I liked the idea of the parent block selector when this first came out, but I didn't like the experience. Even as a long-time user of Gutenberg and mid-level block developer, the parent block selector can still throw me off because it looks like it's part of the toolbar for the selected block at a quick glance (despite the horizontal separation).

For a new user, it's only until you hover over the block and keep your cursor there that it tells you (1) it's a button, and (2) it's not for the current block, you're actually selecting a parent block, and even then, it just says "Select [Block Name]"—it can be unclear to new users that you're moving to a parent block, especially if the current block is the same or similar to the parent block (e.g. Group in Group, Column in Columns, etc.)

For as long as I've had to explain Gutenberg to new clients or coworkers, or new employees coming on board to manage the site who never received training from us, navigating to different blocks is the biggest stumbling block for them, and the parent selector being more specifically something that throws them off, or at bare minimum, doesn't aid them in their journey of discovering nesting by themselves.

## What is your proposed solution?

https://user-images.githubusercontent.com/21220302/175439534-f660d9e4-3209-4f5d-b528-ddac5082659c.mp4

My proposed solution is super simple and requires no changes to any of the components, just some simple CSS.

With every block that has a parent block, there is a simple left arrow (or top-left pointing arrow), and on hover, animates left as the actual parent block as it currently appears animates in from the right. I implemented it in my own plugin I use for clients and it's great.

Here's a demo for top-left pointing arrow. The angled arrow makes more logical sense if you think about it from the list-view perspective. However, the left arrow just "feels" right as a user. Check it out:

https://user-images.githubusercontent.com/21220302/175440312-b2dc4f90-8252-4397-983f-27fcb41e3db6.mp4

**CSS for left or "back" arrow:**

```css

.block-editor-block-parent-selector__button {
    overflow: hidden;
}

.block-editor-block-parent-selector__button::after {
    content: "\f340";
    font-family: dashicons;
    display: block;
    font-size: 17px;
    width: 1em;
    height: 1em;
    line-height: 1;
    font-style: normal;
    speak: never;
    text-decoration: inherit;
    text-transform: none;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: inherit;
    transition: transform 0.3s ease;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-left: -0.5em;
    margin-top: -0.5em;
}

.block-editor-block-parent-selector__button span.block-editor-block-icon {
    position: absolute;
    transform: translateX(150%);
    transition: transform 0.3s ease;
}

.block-editor-block-parent-selector__button.has-icon:hover span.block-editor-block-icon {
    transform: translateX(0);
}


.block-editor-block-parent-selector__button.has-icon:hover::after {
    transform: translateX(-250%);
}
```

**CSS for top-left pointing arrow:**

```css


.block-editor-block-parent-selector__button {
    overflow: hidden;
}

.block-editor-block-parent-selector__button::after {
    content: "\f340";
    font-family: dashicons;
    display: block;
    font-size: 17px;
    width: 1em;
    height: 1em;
    line-height: 1;
    font-style: normal;
    speak: never;
    text-decoration: inherit;
    text-transform: none;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: inherit;
    transition: transform 0.3s ease;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-left: -0.5em;
    margin-top: -0.5em;
    transform: rotate(45deg);
}

.block-editor-block-parent-selector__button span.block-editor-block-icon {
    position: absolute;
    transform: translate(150%,150%);
    transition: transform 0.3s ease;
}

.block-editor-block-parent-selector__button.has-icon:hover span.block-editor-block-icon {
    transform: translate(0,0);
}


.block-editor-block-parent-selector__button.has-icon:hover::after {
    transform: translate(-250%,-250%);
}
```

**NOTE:** I am an enthusiastic but totally new to contributor (this is my first ticket), so please give me any critical feedback in how I am presenting the problem/solution and if I could do it in a better way next time. I'm also not sure if this would have been better in a different section, or if there's an area to push this code for review.
