### ISSUE TITLE
Wrong local font file being referenced by @font-face generated from theme.json

### ISSUE THREAD

**Issue by mateuswetah** [WordPress/gutenberg#42190]
### Description

When using the `settings.typography.fontFamilies[].fontFace` setting in `theme.json`, we have a nice way to let Gutenberg create `@font-face` css for ourselves. 

Sadly, that feature is causing a bug by generating a `src` list prepended by `local('Name of the font'). The internals are done here:
https://github.com/WordPress/gutenberg/blob/6cdd6ae673a6492d8ef69d38264384f953621a75/lib/experimental/class-wp-webfonts-provider-local.php#L231

This seems nice, as it automatically handles the possibility of having local fonts installed on the user system. The problem is that by taking the `$font_familiy` name here, we don't consider that the user may have installed the font from separate files to bold, medium, light, etc. And those files should be listed as different `local` files.

**_I am not 100% sure that this is the cause of the bug that I will describe here, but I do feel we should have some option to disable or at least configure this prepending._**

### Step-by-step reproduction instructions

1. Install on your computer a font with different files for each weight. For example, "El Messiri" regular (ElMessiri-Regular.ttf) and bold (ElMessiri-Bold.tff) variations from [here](https://fonts.google.com/specimen/El+Messiri#standard-styles).
2. In your FSE theme, have the font files also available in a folder. Here I am using `assets/fonts/static/`;
3. Create a `theme.json` file with the following settings configuration:
```.json
{
  "settings": {
      "typography": {
	  "lineHeight": true,
	  "fontFamilies": [
		{
			"fontFamily": "\"El Messiri\", system-ui, -apple-system, \"Segoe UI\", \"Liberation Sans\", sans-serif",
			"name": "Titles (El Messiri)",
			"slug": "headings",
			"fontFace": [
				{
					"fontFamily": "\"El Messiri\"",
					"fontWeight": "400",
					"fontStyle": "normal",
					"src": [ "file:./assets/fonts/static/ElMessiri-Regular.ttf" ]
				},
				{
					"fontFamily": "\"El Messiri\"",
					"fontWeight": "700",
					"fontStyle": "normal",
					"src": [ "file:./assets/fonts/static/ElMessiri-Bold.ttf" ]
				}
			]
		}
          ]
       }
    }
}
```
4. Use the font family in any page just to demonstrate it. Have a heading block bold, for example.
5. Upload your theme and page to any web hosting service.
6. Access the page. Via browser inspector, we can see that the generated `@font-face` will be something like this:
```css
@font-face {
  font-family: "El Messiri";
  font-style: normal;
  font-weight: 400;
  font-display: fallback;
  src: local("El Messiri"),
    url("https://your-host.com/wp-content/themes/your-theme/assets/fonts/static/ElMessiri-Regular.ttf")
      format("truetype");
}
@font-face {
  font-family: "El Messiri";
  font-style: normal;
  font-weight: 700;
  font-display: fallback;
  src: local("El Messiri"),
    url("https://your-host.com/wp-content/themes/your-theme/assets/fonts/static/ElMessiri-Bold.ttf")
      format("truetype");
}
```
The font will appear **bold in computers where the local font is not installed, but regular where it is**. (attachments bellow). In other words, is like if the font-face gives up loading the bold font once it finds the regular one.

I know it sounds weird, but I am bringing this here as the issue is completely solved if we remove the `local('El Messiri')` from the font-face css.

### Screenshots, screen recording, code snippet

![font_working](https://user-images.githubusercontent.com/1184874/177582723-4f7feb19-bec5-4fb9-ae27-02415aaa2647.jpeg)
![font_not_working](https://user-images.githubusercontent.com/1184874/177582737-4ae30497-8efc-4c57-b3aa-458399aa1d11.jpeg)

### Environment info

- WordPress 6.0.0, Gutenberg 13.5.2
- Tested on latest Google Chrome, Opera and Firefox. Weirdly, Firefox does present the error, but after a considerable time (something like 30 secs) it loads the bold font correctly.
- Tested on a Windows 11.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
