### ISSUE TITLE
Redundant/overwritten CSS properties

### ISSUE THREAD

**Issue by schlessera** [WordPress/gutenberg#4260]
## Issue Overview

Some of the provided SCSS files contain redundant CSS properties, where a given property is set twice or more, overwriting the previous value.

While this is probably no real issue, as Sass should be smart enough to optimize this, it just creates unneeded cruft inside of the source files.

## Expected Behavior

A given CSS property should only be set once.

## Current Behavior

Some CSS properties are set multiple times within the same selector, like for example the `position: fixed;` in `editor/edit-post/layout/style.scss`:
```css
.editor-layout .editor-post-publish-panel {
	position: fixed;
	z-index: z-index( '.editor-layout .editor-post-publish-panel' );
	top: $admin-bar-height-big;
	bottom: 0;
	right: 0;
	left: 0;
	overflow: auto;
	position: fixed;
}
```

## Possible Solution

Only the last modification to a property should be kept.
