### ISSUE TITLE
Code block has duplicate background in editor

### ISSUE THREAD

**Issue by justintadlock** [WordPress/gutenberg#43587]
### Description

The `<code>` element inherits the `background` value from its parent `<pre>` when using the Code block in the editor (not an issue on the front end).  Generally, this is not an issue with solid background colors.  However, if the Code block has padding and a gradient background, the duplicate background becomes apparent.

### Step-by-step reproduction instructions

1. Add a Code block to the editor.
2. Add a gradient background.
3. Add some padding.

### Screenshots, screen recording, code snippet

![code-block-duplicate-bg](https://user-images.githubusercontent.com/1816309/186512780-319db8f6-1625-42b6-a47e-ee55c83a7f8b.jpg)

This is coming from the `reset.css` code:

```css
html :where(.editor-styles-wrapper) code, 
html :where(.editor-styles-wrapper) kbd {
    background: inherit;
    font-family: monospace;
    font-size: inherit;
    margin: 0;
    padding: 0;
}
```

The solution should be to remove the `background: inherit` line or unset it specifically for the Code block.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
