### ISSUE TITLE
Gallery columns don't match with other full width elements

### ISSUE THREAD

**Issue by Axinet** [WordPress/gutenberg#4548]
## Issue Overview
Gallery with 2 columns is narrower than centered image (both blocks should match main column/paragraph width).

## Steps to Reproduce (for bugs)

1. Insert centered image 
2. Insert 2 column gallery
3. Switch to frontend view
4. Last gallery image ends at a different position than a single image.

All desktop browsers that show gallery (IE11 doesn't)

## Expected Behavior
Gallery with should match singl image/paragraph width like in gutenberg editor in admin:
![31453423-6d413630-aeb2-11e7-9a46-64db1ca4bad5](https://user-images.githubusercontent.com/393549/35048927-c997be3e-fb9e-11e7-870c-0796d98e372d.PNG)
Above screnshot is from **admin** but problem is on **frontend** (see below).

## Current Behavior
There is visible gap on frontend (highlighted with blue boxes)
![gallery issue](https://user-images.githubusercontent.com/393549/35048969-e118222e-fb9e-11e7-8981-dbfbea0e6368.PNG)

The screen comes from Gutenberg 2.0.0 (in version 1.9 gap was twice as wide but only at right side).

## Possible Solution
For 2 columns and 2 images gallery adding 
```css
.wp-block-gallery.aligncenter .blocks-gallery-image:first-child {
    margin-left:0;
}
.wp-block-gallery.aligncenter .blocks-gallery-image:last-child {
    margin-right: 0;
}
```
solves the issue, didn't have time to enumerate it over different settings.
Margin styles from images come from `/wp-content/plugins/gutenberg/blocks/build/style.css`.

## Related Issues and/or PRs
Could be related to Responsive image gallery block #4035 (it also mentions `.blocks-gallery-image` margins, but I don't understand from provided screen and description what is really issued there).

## Todos
- [ ] Tests
- [ ] Documentation
