### ISSUE TITLE
Filter/Remove/Add Heading Levels

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#45628]
## What problem does this address?

It's important for us to be able to remove heading levels on client projects in posts, to limit them to predefined options, e.g. `h2`/`h3` , but not `h1`/`h4`/`h5`.

I understand that you can enforce self-discipline, but that's not enough for clients, and writers can easily write posts that break things or be sloppy with heading levels. They don't want tools to help enforce this, they don't even want it to be possible in the first place.

<img width="128" alt="Screenshot 2022-11-09 at 15 08 26" src="https://user-images.githubusercontent.com/58855/200866624-555732a3-3f04-4d76-914f-bb0b822aff63.png">

A custom header block is also not an option as that introduces portability issues as well as a constant maintenance burden to keep porting cores changes and reapply the modified `HEADING_LEVELS` array

## What is your proposed solution?

```
const HEADING_LEVELS = [ 1, 2, 3, 4, 5, 6 ];
```

This constant needs to be filterable or configurable

**Comment by tomjn** [comment]
Specifically, we've been trying to re-implement this in the core headings block on every update to WP with CSS giving limited to poor results:

<img width="160" alt="Screenshot 2022-11-09 at 15 09 57" src="https://user-images.githubusercontent.com/58855/200867079-ef62671a-02e7-4102-bea5-86d2ca4ee0b7.png">

**Comment by tomjn** [comment]
Likewise if the individual buttons had a predictable ID or class that could be targeted then that would also solve the problem

**Comment by tomjn** [comment]
For the moment, this is doing what I need it to with this CSS in WP 5.9 but it's likely to break:

```scss
// Hide unwanted heading levels
.block-library-heading-level-dropdown {
	button:nth-of-type( 1 ),
	button:nth-of-type( 4 ),
	button:nth-of-type( 5 ),
	button:nth-of-type( 6 ) {
		display: none;
	}
}
```
