### ISSUE TITLE
Component: Button with `disabled` prop changes text color in active state

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#47859]
### Description

Even though the `disabled` property of the `Button` component is set to `true`, the color of the text changes in the `active` state, such as pressing the primary mouse key.  To me, this change in text color seems unintentional.

https://user-images.githubusercontent.com/54422211/217448988-3563753d-1dde-40b0-a75f-0a1fa1e8907c.mp4

As far as I've been able to discover, you can see the change with the button in the link control in the block editor.

https://user-images.githubusercontent.com/54422211/217449008-fac0a00e-1be4-4387-8fb5-6702fbf4e1a3.mp4

This problem does not occur with `Button` components that have the `aria-disabled` attribute. For example, [the button to update a post has the prop](https://github.com/WordPress/gutenberg/blob/0d056cfae33a530c58dedc84c821f229383d713e/packages/editor/src/components/post-publish-button/index.js#L170).

If this behavior is unintentional, I have found that the following CSS solves the problem:

```css
/* From */

&:not([aria-disabled="true"]):active {
	color: $components-color-foreground;
}

/* To */
&:not(:disabled):not([aria-disabled="true"]):active {
	color: $components-color-foreground;
}
```

However, the pseudo-style of the button component is overridden in various places. The above changes will increase the level of CSS specificity and we may need to check the impact on them.

### Step-by-step reproduction instructions

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
