### ISSUE TITLE
Gallery block does not respect opting out of base layout styles

### ISSUE THREAD

**Issue by cbirdsong** [WordPress/gutenberg#47948]
### Description

The gallery block does not respect the ability to opt out of [base layout styles](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#disabling-base-layout-styles) via `add_theme_support( 'disable-layout-styles' );`. 

### Step-by-step reproduction instructions

1. Add `add_theme_support( 'disable-layout-styles' );` to a non-FSE theme.
2. Add a gallery block to a page. 
3. Inspect the gallery block. You will find a class like `.wp-block-gallery-10` and an accompanying `<style>` block like this:
```css
.wp-block-gallery.wp-block-gallery-10 {
    --wp--style--unstable-gallery-gap: var(--wp--style--gallery-gap-default, var( --gallery-block--gutter-size, var( --wp--style--block-gap, 0.5em ) ) );
    gap: var(--wp--style--gallery-gap-default, var( --gallery-block--gutter-size, var( --wp--style--block-gap, 0.5em ) ) );
}
```

### Environment info

- WordPress 6.1, core version of Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Thanks for reporting @cbirdsong. I am able to confirm in Twenty Twenty-One using WordPress 6.2 Beta 2 and the latest version of Gutenberg. 

![image](https://user-images.githubusercontent.com/4832319/220378245-ffbe177d-c89c-4892-bef8-97af8e6d3569.png)

**Comment by cbirdsong** [comment]
I can confirm this is still an issue in WordPress 6.3.

**Comment by webexpr-dhenriet** [comment]
@cbirdsong 

I can also confirm that the style is not applied to a hybrid theme (not FSE) on wp 6.4.3.
In my theme.json file I have set  the blockGap spacing to 0
```json
"styles": {
  "spacing": {
    "blockGap": "0"
  }
}
```
The css variable `--wp--style--block-gap` is equal to 0, `--gallery-block--gutter-size` is undefined.
The gallery images are displayed one below the other instead of respecting the columns
```css
.wp-block-gallery.wp-block-gallery-1 {
    --wp--style--unstable-gallery-gap: var(--wp--style--gallery-gap-default, var(--gallery-block--gutter-size, var(--wp--style--block-gap, 0.5em)));
    gap: var(--wp--style--gallery-gap-default, var(--gallery-block--gutter-size, var(--wp--style--block-gap, 0.5em)));
}
```
![Screenshot_1](https://github.com/WordPress/gutenberg/assets/62699215/b0596a2e-d431-4c16-b717-232e6c5f3ac9)


I can correct this by applying : 
```json
"styles": {
  "blocks": {
    "core/gallery": {
        "css": "--wp--style--block-gap: 1rem"
     }
  }
}
```
