### ISSUE TITLE
Interaction with neve theme causing Block "core/legacy-widget" is already registered. and Error: The “meta-sidebar” plugin cannot be rendered

### ISSUE THREAD

**Issue by donbowman** [WordPress/gutenberg#48749]
### Description

In the browser javascript console when editing a post, i see:

Block "core/legacy-widget" is already registered.

In the browser as an error I see `Error: The “meta-sidebar” plugin cannot be rendered`

This appears to be an interaction between Gutenberg and Neve.

### Step-by-step reproduction instructions

install wp 6.1.1, neve, gutenberg
create a new post

the neve sidebar will not show.
the javascript console will show the Block "core/legacy-widget" is already registered.

### Screenshots, screen recording, code snippet

```
registration.js:276 Block "core/legacy-widget" is already registered.
ne @ registration.js:276
react-dom.min.js?ver=18:1 TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at use-dispatch-with-map.js:40:11
    at Object.useMemo (react-dom.min.js?ver=18:1:115379)
    at e.useMemo (react.min.js?ver=18:1:9875)
    at use-dispatch-with-map.js:34:9
    at index.js:97:26
    at wt (react-dom.min.js?ver=18:1:47623)
    at $s (react-dom.min.js?ver=18:1:120736)
    at wl (react-dom.min.js?ver=18:1:88644)
    at bl (react-dom.min.js?ver=18:1:88572)
```

### Environment info

Wordpress 6.1.1
neve 3.5.4
gutenberg 15.2.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ghost** [comment]
@donbowman Have you tried contacting the Theme Author/Support first?

**Comment by donbowman** [comment]
Yes.
https://wordpress.org/support/topic/error-the-meta-sidebar-plugin-cannot-be-rendered/
there is a support thread open there. Its not clear to me which is the issue. It came w/ the gutenberg update, they were working together previous to 15.3.0

**Comment by donbowman** [comment]
i don't think 'help request' label is accurate or correct, the newer version of gutenberg introduced this behaviour. I'm not looking for assistance in configuring it, but between gutenberg and neve an incompatibility was introduced.

**Comment by ghost** [comment]
> I'm not looking for assistance in configuring it

Sure, but I can't reproduce it with any of the default WordPress themes (and a few others I'm using), so it does seem to be something the Theme Authors should have a look at first. If they believe they're doing everything right and something's broken in Gutenberg, they can pinpoint the issue with some context and we can attach a more specific label so the right contributors will notice it.

**Comment by donbowman** [comment]
here's the minimal reproduction:
1. wp 6.1.1 (I used docker-compose). Stock settings
2. Install neve theme from dashboard
3. Install gutenberg plugin from dashboard, activate it
4. Create a new post

the problem shows up immediately on step 4.

```
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
```

is what i used.
