### ISSUE TITLE
Button state styling missing from wp-element-button 

### ISSUE THREAD

**Issue by seothemes** [WordPress/gutenberg#49218]
### Description

When adding button element styles in theme.json, the state styles are not being applied correctly to `.wp-button-element`. The `.wp-block-button__link` styles are added correctly:

```css
.wp-element-button, .wp-block-button__link:hover {
    background-color: var(--wp--preset--color--contrast);
    color: var(--wp--preset--color--base);
}
```

The expected CSS should be:

```css
.wp-element-button:hover, .wp-block-button__link:hover {
    background-color: var(--wp--preset--color--contrast);
    color: var(--wp--preset--color--base);
}
```

I have also tested other elements but it appears to only be happening with buttons.

### Step-by-step reproduction instructions

1. Add a button block to a page
2. View page
3. Inspect CSS

## Twenty Twenty-Three generated CSS:

<img width="468" alt="screenshot of missing wp-element-button state styles" src="https://user-images.githubusercontent.com/24793388/226507736-2b17dde1-5572-411f-8906-50a64bfcdd2e.png">

## Twenty Twenty-Three default button styling:

<img width="905" alt="twenty twenty-three default button style" src="https://user-images.githubusercontent.com/24793388/226507573-53983807-3d98-4701-9593-d6c63e0f50b4.png">

### Environment info

- WordPress 6.1.1, Gutenberg 15.3.1, all themes
- All browsers
- All devices

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
