### ISSUE TITLE
Additional Block CSS: Selector impossible if attribute is not on block-level but on element-level (as in BEM)

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#49415]
## User Goal
As a block theme tweaker  (advanced user, designer with CSS knowhow, but no developer):
1. You add a helper class like `.has-outline-dashed` on a block instance like a Button block.
2. You add **Additional Block CSS**, which shall apply not all all instances of that block but only to block instances which have that helper class added via their **Additional CSS Class(es)**.

## TL;DR — My User Experience

If the attribute you want to override corresponds not to the block-level (as in BEM) of your block, but on an element level ...
1. In **Additional Block CSS** due to automatic prefixing it is impossible for "advanced users" (designers/tweakers) to formulate a proper CSS selector here.
2. Then the only way for advanced users is via **Global Additional CSS**, which is not in the "modular spirit" (modular CSS selectors yes, but all in one long text blob (enqueued all time!), instead of separate Additional CSS per each block (enqueued only on demand).
3. Professional theme.json developers/modders possibly can achieve that by writing a **proper block style** with inline **custom CSS as JSON values**.

## Followup

- Is there a solution currently other than 2) Global Additional CSS and 3) proper CSS within theme.json ?
- Is it possible that "Additional Block CSS" gets "a bit smarter" with what it prefixes?
  - Is there an existing syntax for "if the block has the helper then consider the Additional CSS here to match"? Ampersand maybe?
  - If not could that be implemented?

## My full testing

1) If I wanted to overwrite the default block style, it works easy:

Global Styles → Blocks → Button → Additional block CSS

```css
border-style: dashed;
```

- ✅ Works all nice
- ✅ No selector necessary
- ✅ No `!important` necessary

2) If I wanted to overwrite a particular block style "Outline", working with the same method fails.

Global Styles → Blocks → Button → Style Variation "Outline"

- No "Additional block CSS" here!
  - Note: I even fell into a usability pitfall. Clicked the "more" menu (3 vertical dots) in the Styles panel in the believe this is the way to get "Additional CSS" for the Style Variation "Outline". No this is the global one (as I later verified by writing "/* This is the Theme CSS Level Additional CSS */" and then accessed this from a totally different block and the same inline comment was still there.)

3) Select a button block instance → block settings → Advanced → Additional CSS Class(es)

- I assign my helper class `has-border-style-dashed`.
- Problem:
  - This is assigned on the block level `.wp-block-button`
  - But the relevant border to override is on the element level `.wp-block-button__link`

a) The only way I managed to select and override it was:

Global Styles → Additional CSS

```css
.has-border-style-dashed .wp-block-button__link {
  border-style: dashed;
}
```

- On a pure CSS selector level this is almost true to Modular CSS ("BE + M" instead of "BEM"), but on Block Editor UX / UI it is not modular. Everything in the Global CSS override blob.
- I tried to use the offered more modular ways, but failed, due to the prefixing/suffixing which happens behind the scenes, not being comprehensible.

b) Cleaner but failed attempt: Global Styles → Blocks → Button → Additional block CSS

- The basic version worked fine, see 1.
- But now we want it only if the button block has the helper class `has-border-style-dashed`.

b1) Additional block CSS:

```css
.has-border-style-dashed {
  border-style: dashed;
}
```

Outcome in `<style id='wp-block-library-inline-css'>`

```css
.wp-block-button .wp-block-button__link.has-border-style-dashed {
  border-style: dashed;
}
```

- ❌ Okay, so it prefixed it with the element-level `.wp-block-button__link`.

b2) So I try this now:

```css
.wp-block-button.has-border-style-dashed .wp-block-button__link {
  border-style: dashed;
}
```

Outcome in wp-block-library-inline-css:

```css
.wp-block-button .wp-block-button__link.wp-block-button.has-border-style-dashed .wp-block-button__link {
    border-style: dashed;
}
```

- ❌ No, I'm getting nowhere.

b3) Hence I tried to formulate a selector in the spirit of "has a parent with class .has-border-style-dashed":

```css
.has-border-style-dashed:has(.wp-block-button__link) {
  border-style: dashed;
}
```

Outcome in wp-block-library-inline-css:

```css
  .wp-block-button .wp-block-button__link.has-border-style-dashed:has(.wp-block-button__link) {
      border-style: dashed;
  }
```

- ❌ My last attempt has failed too.
