### ISSUE TITLE
Styles: add gradient support to text color options

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#49642]
This was mentioned as part of the [FSE Outreach Program's Build a Block Theme exploration](https://make.wordpress.org/test/2023/03/29/fse-program-exploration-build-a-block-theme/#comment-2973) in this [mentioned summary post
](https://gutenbergmarket.com/news/a-comprehensive-guide-to-building-wordpress-block-themes)
>Currently there is no way to add colour gradients to the text colour. This has to be done with CSS. This is likely quite difficult to achieve and isn’t the highest priority at the moment, but would be a great feature in the future.

My brain immediately went to some sort of accessibility concerns but wanted to note either way to see what folks thought! To be clear, this is for Site Editor > Styles > Color > Text:

<img width="275" alt="Screen Shot 2023-04-06 at 9 15 12 AM" src="https://user-images.githubusercontent.com/26996883/230437500-d34a7626-ce43-4e14-a51e-79c91e4468a7.png">

**Comment by aaronrobertshaw** [comment]
As you note, there might be some accessibility concerns with gradients. I imagine it might be tricky to effectively check the text's contrast with its background.

Perhaps we could use a similar approach here as we did when enabling the alpha channel for text colors. In that case, if we didn't otherwise detect a contrast issue and the text was transparent at all, we warn about the potential accessibility issue.

The PR introducing the alpha channel checking can be found here: https://github.com/WordPress/gutenberg/pull/38100

**Comment by justintadlock** [comment]
It's also worth noting that gradient text isn't a supported feature in CSS. Gradients are, for all intents and purposes, images in CSS.

The most common method to "fake" gradient text is to assign a background image, add `background-clip` to the element, and make the text transparent so that the background shines through.

Here's some sample CSS from a "clip text" Heading block style I have:

```css
.wp-block-heading.is-style-clip-text {
	background-clip: text !important;
	-webkit-background-clip: text !important;
	color: transparent !important;
}

/* Add a default background in case user hasn't selected one. */
.wp-block-heading.is-style-clip-text:not( .has-background ) {
	background: var( --wp--preset--gradient--cool-to-warm-spectrum );
}

/* Make sure sub-element text is also transparent. */
.wp-block-heading.is-style-clip-text > * {
	color: inherit !important;
}
```

That part is not particularly complex.

Making the UX work well for this would be the toughest part because you'd have to (under the hood) migrate the "text" gradient to the background and also hide the background setting in the UI.

I'm not sure if there are other methods for making text appear as if it had a gradient color.
