### ISSUE TITLE
Support `:hover` on block level

### ISSUE THREAD

**Issue by cawa-93** [WordPress/gutenberg#49716]
## What problem does this address?
Currently, we can specify styles per block and `:hover` for `elements` inside block. But we can't cpesify `:hover` styles on block itself. 
For example:
```js
// theme.json
{
	"styles": {
		"blocks": {
			"core/button": {
				"typography": {
					"textTransform": "uppercase"
				},
				"elements": {
					"link": {
						":hover": {
							"typography": {
								"textTransform": "lowercase"
							}
						}
					}
				}
			}
		}
	}
}
```

Will generate
```css
.wp-block-button .wp-block-button__link{text-transform: uppercase;}
.wp-block-button .wp-block-button__link a:where(:not(.wp-element-button)):hover{text-transform: lowercase;}
```
But needed css is:
```css
.wp-block-button .wp-block-button__link{text-transform: uppercase;}
.wp-block-button .wp-block-button__link:hover{text-transform: lowercase;}
```

## What is your proposed solution?
Provide support for pseudo classes like  `:focus` or `:hover` on block level. 
```js
{
	"styles": {
		"blocks": {
			"core/button": {
				"typography": {
					"textTransform": "uppercase"
				},
				":hover": { // currently has no effect
					"typography": {
						"textTransform": "lowercase"
					}
				}
			}
		}
	}
}
```
