### ISSUE TITLE
Use local css variables for colors in blocks like Button

### ISSUE THREAD

**Issue by WraithKenny** [WordPress/gutenberg#49931]
## What problem does this address?
There's a number of very complex problems related to Button styles (hover, user selected colors, UI, etc) that could be (relatively) easily solved with (locally scoped) css variables, as well as many similar issues with other blocks.

## What is your proposed solution?
We could pass the color value (whether from user input, or theme.json) into an intermediate css var (`--wp--local--color--text` or `--wp--local--color--background`) and then use that in the styles. 
### This is the current relevant css:
```CSS
.wp-element-button,
.wp-block-button__link {
	color: var(--wp--preset--color--white);
	background-color: var(--wp--preset--color--red);
	border-color: var(--wp--preset--color--red);
}
.wp-element-button:hover,
.wp-block-button__link:hover {
	background-color: var(--wp--preset--color--dark);
	color: var(--wp--preset--color--white);
}

/* From user selected colors. */
.has-grey-background-color {
	background-color: var(--wp--preset--color--grey) !important;
}
.has-red-color {
	color: var(--wp--preset--color--red) !important;
}

```
### Here's a working example of the alternative
```CSS
.wp-element-button,
.wp-block-button__link {
	--wp--local--color--text: #fff;
	--wp--local--color--background: #32373c;
	color: var(--wp--local--color--text);
	background-color: var(--wp--local--color--background);
	border-color: var(--wp--local--color--background);
}
.wp-element-button:hover,
.wp-block-button__link:hover {
	--wp--local--color--text: #fff;
	--wp--local--color--background: #000;
}

/* From theme.json set colors. */
.wp-element-button,
.wp-block-button__link {
	--wp--local--color--text: var(--wp--preset--color--white);
	--wp--local--color--background: var(--wp--preset--color--red);
}
.wp-element-button:hover,
.wp-block-button__link:hover {
	--wp--local--color--text: var(--wp--preset--color--white);
	--wp--local--color--background: var(--wp--preset--color--dark);
}

/* From user selected colors. */
.has-gray-background-color {
	--wp--local--color--background: var(--wp--preset--color--gray);
	background-color: var(--wp--local--color--background) !important;
}
.has-red-color {
	--wp--local--color--text: var(--wp--preset--color--red);
	color: var(--wp--local--color--text) !important;
}
```
This would also allow for sensible defaults for :hover (like inverting the text and bg values, and setting up Outline variant plus it's hover). And this would also allow easy customization by theme authors, who could utilize the locally scoped css variables without impacting anything else.

This is a generalizable pattern that can be applied to any Block, not just Button.
