### ISSUE TITLE
[Env Package]: permalink structure update via wp cli

### ISSUE THREAD

**Issue by shashwatahalder01** [WordPress/gutenberg#50538]
### Description

Tried to update the permalink from plain to pretty using wp cli. Still getting errors on git action Linux environment. 
CLI commands don't work on both env: development and test

The issue should be fixed by this [PR](https://github.com/WordPress/gutenberg/pull/49962). Is the issue still exist or I am doing something wrong?

Git Action:

```
name: End-to-End Tests

on:
  pull_request:
  push:
    branches:
      - e2e
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    name: e2e tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
         ref: "e2e"

      - name: Use desired version of NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: "npm"
          
      - name: Install dependencies  & start wp env
        run: |
          cd tests/e2e 
          npm ci 
          npm run wp-env start       
  
      - name: Set Permalink structure
        run: |
          cd tests/e2e 
          npm run wp-env run cli 'wp rewrite structure /%postname%/'  --hard 
          curl http://localhost:8888/wp-json/wp/v2
```

.wp-env.json:
```
{
      "core": null,
      "phpVersion": "7.4",
      "plugins": [
        "https://downloads.wordpress.org/plugin/woocommerce.latest-stable.zip"
      ],
      "themes": [
        "https://downloads.wordpress.org/theme/storefront.latest-stable.zip"
      ]
}
```

### Step-by-step reproduction instructions

1. start wp-env on git action
2. try to update permalink using cli

### Screenshots, screen recording, code snippet

<img width="273" alt="Screenshot at May 11 16-01-22" src="https://github.com/WordPress/gutenberg/assets/82957718/659059bb-2149-4794-811a-715e3577eee7">

### Environment info

"@wordpress/env": "^7.0.0"

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
