### ISSUE TITLE
Adding CSS to Editable tag messes up the placeholder

### ISSUE THREAD

**Issue by davidsword** [WordPress/gutenberg#5063]
Safari 11, wp 4.9.4, gb 2.1.0

Got an Editable component

```jsx
<div className="textBox">
    <Editable
        tagname="div"
        multiline="p"
        className="textBoxContent"
        placeholder="...."
        value={ attributes.content }
        onChange={ onChangeContent }
    />
</div>
```

The Editor `.textBoxContent` has some CSS to it, within the editor:

```css
div.textBox {
    margin: 20px 0;
    .textBoxContent {
        width: 90%;
        max-width: 400px;
        margin-left: auto;
        margin-right: auto;
        border: 1px solid red;
    }
}
```

The CSS messes changes mess with `.blocks-editable__tinymce[data-is-placeholder-visible=true]` element (the one that only shows when there's no content in Editor). Perhaps the placeholder needs some better CSS mirroring to factor in developers doing weird css things like I've done?

![weird](https://user-images.githubusercontent.com/1996370/36230401-2d4638ce-118f-11e8-912d-ba9732ced2a6.gif)

Don't know if it's as simple as "don't change the size/position of your Editable tag then" or if ya'll at a point of factoring in developer plugins - but thought I'd bring it up.
