### ISSUE TITLE
ZStack being absolutely positioned makes it hard to center and size

### ISSUE THREAD

**Issue by justgage** [WordPress/gutenberg#51807]
### Description

When working on Day One Web, we're trying to use ZStack to stack avatars, but it's troublesome due to the absolute positioning. Absolute positioning is problematic because it no longer dynamically takes up space in the DOM and can't be as quickly centered with Flexbox.

I'm curious if we can't use a negative margin instead of absolute positioning, and you can still get the proper layering by using a big of a hack with `position: relative` (see below) : https://codepen.io/justgage/pen/GRwjPZP

(in case the codepen dies, here's the code)

https://github.com/WordPress/gutenberg/assets/164033/9e6cd6a9-8805-4110-ab13-fe509f77c3d8

```html
<div class="overlap-stack justify-center reverse">
  <div class="avatar blue">
  </div>
  <div class="avatar red">
  </div>
  <div class="avatar">
  </div>
</div>
```

```less
.avatar {
  width: 50px;
  height: 50px;
  background-color: rgba(100, 100, 100, 0.8);
  border-radius: 99999px;
  position: relative; /* Add position relative for z-index to work */
  z-index: 1; /* Set initial z-index */
}

.red {
  background-color: #ff0000;
}

.blue {
  background-color: blue;
}

.overlap-stack {
  display: flex;
  & > * + * {
    margin-left: -20px;
  }
  background-color: lightgreen;
}

.reverse {
  flex-direction: row-reverse;
  & > * + * {
    margin-right: -20px;
  }
  & > * {
    margin-left: 0;
  }
}

.justify-center {
  justify-content: center;
}
```

### Step-by-step reproduction instructions

Here's a code example of something we were trying to do (simplified a bit)
```html
<div css={{ display: "flex," justifyItems: "center" }}>
    <ZStack offset={20} isLayered css={{ width, height: "30px" }}>
          {avatarsToShow.map((p: JournalParticipant) => (
            <Avatar user={p} />
          ))}
    </ZStack>
</div>
```

### Screenshots, screen recording, code snippet

Here you can see this is even happening in the storybook if you wrap an element around it:

<img width="350" alt="Screenshot 2023-06-22 at 7 21 43 AM" src="https://github.com/WordPress/gutenberg/assets/164033/747d64d6-d00b-4217-93b3-8d2c4c45a461">

### Environment info

```
    "@wordpress/components": "23.8.0",
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
