### ISSUE TITLE
Footnote Block: Styles are applying to elements that happen to have the `.fn` class.

### ISSUE THREAD

**Issue by shazahm1** [WordPress/gutenberg#52136]
### Description

The styles for this block select the `.fn` class globally. This makes any page content with this class render offscreen due to the text-indent property and replaced with `[1]`. The is the offending CSS:

``` CSS
.fn {
    counter-increment: footnotes;
    display: inline-block;
    font-size: smaller;
    text-indent: -9999999px;
    vertical-align: super
}

.fn:after {
    content: "[" counter(footnotes) "]";
    float: left;
    text-indent: 0
}
```

The class name needs to be more specific, or the CSS sector more specific.

### Step-by-step reproduction instructions

Add the `fn` class to any page element.

### Screenshots, screen recording, code snippet

![footnote-block](https://github.com/WordPress/gutenberg/assets/1185008/15ae307a-aeaf-4c20-a1aa-23f11a103914)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
