### ISSUE TITLE
CSS rules for UL, OL contain defaults for everything inside the Gutenberg class

### ISSUE THREAD

**Issue by igorschoester** [WordPress/gutenberg#5307]
In [edit-post/assets/stylesheets/main.scss](https://github.com/WordPress/gutenberg/blob/master/edit-post/assets/stylesheets/main.scss#L89) the rules for UL and OL seem to stem from [just the example page](https://github.com/WordPress/gutenberg/commit/67ed22d91db729feebf449da770c41bef9a39f86#diff-4c801ab8a67244f296df797408a28637R29). And after that get changed [here](https://github.com/WordPress/gutenberg/commit/d8eaefb81f103898a66ba2eaebd2057c255f7e7b#diff-4c801ab8a67244f296df797408a28637R46) to exclude it for that code?

```css
.gutenberg {
	ul:not(.wp-block-gallery) {
		list-style-type: disc;
	}

	ol:not(.wp-block-gallery) {
		list-style-type: decimal;
	}
}
```

As plugin you get the CSS applied:

<img width="554" alt="36780333-f694b15e-1c72-11e8-86d1-15a9f38f8b5d" src="https://user-images.githubusercontent.com/35524806/36790078-f468fb08-1c93-11e8-93e7-dcd097254b30.png">

Where on both occasions we specify `list-style: none`. In one case as specific as this:
```css
.wpseo-metabox-tabs-div ul {
	list-style: none;
}
```

I'd propose to not include defaults like this. And if some component needs them. Use specific styles for those.
