### ISSUE TITLE
Grid empty space issue in Columns block

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#5351]
## Issue Overview
Columns block have this CSS Grid:

```css
.wp-block-columns {
	display: grid;
	grid-auto-flow: dense;

	@for $i from 2 through 6 {
		&.has-#{ $i }-columns {
			grid-auto-columns: #{ 100% / $i };
		}
	}

	@for $i from 1 through 6 {
		.layout-column-#{ $i } {
			grid-column: #{ $i };
		}
	}
}
```

This can result to this kind of layout with lot's of empty spaces:

<img width="711" alt="Grid layout have empty space here and there" src="https://user-images.githubusercontent.com/1820415/36895320-2f5be836-1e17-11e8-9083-e8756c9cc881.png">

I'm all for using CSS Grid but we might need add extra `<div>` wrapper around columns.
