### ISSUE TITLE
Adding css property for core/list markers in theme.json has unexpected css output

### ISSUE THREAD

**Issue by itsamoreh** [WordPress/gutenberg#53597]
### Description

I added the following in theme.json for the core/list block:

```json
"styles": {
  "blocks": {
    "core/list": {
      "css": "& ::marker {color: var(--wp--preset--color--pink);}"
    }
  }
}
```

Works great on unordered lists, but it unexpectedly affects the text for ordered lists.

<img width="870" alt="screen-capture 2023-08-11 at 7 17 55 PM" src="https://github.com/WordPress/gutenberg/assets/12365909/297ab3cd-0bfe-41f0-9acb-1bfbe832ad89">

When you take a look at the CSS produced, you can see why.

```css
ol, ul ::marker {
    color: var(--wp--preset--color--pink);
}
```

I expect the following to be produced instead:

```css
ol ::marker, ul ::marker {
    color: var(--wp--preset--color--pink);
}
```

### Step-by-step reproduction instructions

1. Style list markers using the `css` property on the `core/list` block in theme.json
2. Observe that the wrong css rule is output - `ol, ul ::marker` instead of `ol ::marker, ul ::marker`

### Environment info

- WordPress 6.3, bundled version of Gutenberg, a barebones block theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
