### ISSUE TITLE
Enhancement: separate `global-styles` (theme.json output) into css parts, now it includes design tokens and also layout classes

### ISSUE THREAD

**Issue by tresorama** [WordPress/gutenberg#54135]
## What problem does this address?
theme.json is used to generate a css stylesheet injected on pages.
The css generated is enqueued with the handle name  `global-styles` (side note: here a better name for the handle could reflect the theme json nature), so extender can disable this style from the injection with `wp_dequeue_style("global-styles")`.

This CSS contains design tokens (colors, font sizes, spacing scale, ....).
But other that that it contains also definition for core layout css used into several blocks , like 

```css
body .is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
  max-width: var(--wp--style--global--content-size);
  margin-left: auto !important;
  margin-right: auto !important;
}

body .is-layout-constrained > .alignwide {
  max-width: var(--wp--style--global--wide-size);
}
```

Because of this, if an extender want to overwrites the layout portion, it likely want to dequeue `global-styles`, but doing that it also lose design tokens, that maybe it is not what the extender need/want.

## What is your proposed solution?

**I think is it more convenient to split this `global-styles` into parts, so they can be dequeued separately.**
At leasts "design-tokens" and "layout" parts, but we could take into consideration to split even more to accomodate other parts of the theme.json spec.
