### ISSUE TITLE
"Additional CSS" (Custom CSS) fails to display in Site Editor preview 

### ISSUE THREAD

**Issue by gungfujoe** [WordPress/gutenberg#54139]
### Description

The Site/Theme Editor allows you include "Additional CSS" with a style (often the only way to get around current editor limitations), and blocks allow you to add custom CSS classes..  I've done this for my site's navigation bar, and it works well on the page, but not in the site editor.  The custom CSS doesn't reflect in the otherwise-fully-rendered display.

### Step-by-step reproduction instructions

1. In the theme editor right-side pane, navigate to the "Styles" pane
2. Click the three vertical dots and select "Additional CSS"
3. Define some CSS for a class you want to use
4. Add that class to the "Additional CSS Class(es)" field for a block in a template
5. See the difference between your website and the Theme Editor's rendering of your website.

### Screenshots, screen recording, code snippet

The Editor UI has very limited options for styling a navigation menu, so I copied some of the code from my old theme's Navbar class.  It could probably benefit from some tweaking, but aside from replacing the colors with variables, it's 20-ish year old code:
`ul.navbar li a { color: var(--wp--preset--color--base); height: auto; background: var(--wp--preset--color--custom-darker-red); font-weight: bold; border: 1px solid var(--wp--preset--color--contrast); padding: 0.1em 0.6em; white-space: nowrap; }
ul.navbar li a:visited { color: var(--wp--preset--color--tertiary); background: var(--wp--preset--color--custom-darker-red); }
ul.navbar li a:hover { color: var(--wp--preset--color--primary); background: var(--wp--preset--color--contrast); text-decoration: none; }
ul.navbar li.current_page_item a, ul.navbar li.current_page_item a:visited , ul.navbar li.current_page_item a:hover { color: var(--wp--preset--color--base); height: auto; background: var(--wp--preset--color--primary); }
ul.navbar li.current_page_item a:before { content: "\00BB \0020"; }
ul.navbar li.current_page_item a:after { content: "\0020 \00AB"; }`
With that CSS defined, and the "navbar" class applied, here's how my navbar looks in the editor:
![Navbar-Editor](https://github.com/WordPress/gutenberg/assets/17948266/92ce5122-eb81-4a8a-989e-f673238186a5)

But here's how the same navbar looks on the site itself:
![Navbar-Site](https://github.com/WordPress/gutenberg/assets/17948266/b5a2a556-3bce-4b42-bd3a-26ccd1d99087)

There's nothing particularly fancy in this code.  Since CSS support is built into the editor's UI, it stands to reason that the editor should be parsing that CSS when rendering elements.

### Environment info

I'm using WordPress 6.3.1 on my [live site](https://www.kungfu-silat.com) and 6.4-alpha-56509 on the [dev/test site](https://dev.eharrishome.com) that the screenshots above were taken from, hosted on a DreamHost VPS account.  I'm accessing the site via Firefox 117.0 on Windows 10 Pro

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by jordesign** [comment]
Hi @gungfujoe - as this so far is limited to your site specifically - it seems there could be a number of factors at play.

As a start - could you please attempt to disable all plugins, and use one of the default (Twenty*) themes. If the problem goes away, enable them one by one to identify the source of your troubles.

If you can install plugins, install and activate "Health Check": <a href="https://wordpress.org/plugins/health-check/">https://wordpress.org/plugins/health-check/</a>  
It will add some additional features under the menu item under Tools > Site Health.
On its troubleshooting tab, you can Enable Troubleshooting Mode. This will disable all plugins, switch to a standard WordPress theme (if available), allow you to turn your plugins on and off and switch between themes, &lt;strong>without affecting normal visitors to your site&lt;/strong>. This allows you to test for various compatibility issues. 

There’s a more detailed description about how to use the Health Check plugin and its Troubleshooting Mode at <a href="https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/">https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/</a>

That will narrow down if this is an issue specifically with Gutenberg, or may be coming from your theme, or a plugin on the site.

**Comment by gungfujoe** [comment]
Thanks @jordesign , I've done exactly that, and in doing so, I think I've confirmed that this is an issue with the editor, and not with a conflict with any plugin I've got running.  Here's a snapshot of my test site (WordPress 6.4-alpha-56510) using the base Twenty Twenty-Three theme in both editor mode and normal display mode, using the same "additional CSS" that I pasted above.

Editor (with the window shrunken down to the point where you can see the "Additional CSS Class(es)" that I've applied:
![image](https://github.com/WordPress/gutenberg/assets/17948266/3072b2a5-2132-4941-a440-4a76b1c5e559)

Resultant page:
![image](https://github.com/WordPress/gutenberg/assets/17948266/4e4944b4-3d48-46fa-a7f9-abcfa5dd4ac7)

As you can see, the custom CSS is ignored in the editor view.

**Comment by glendaviesnz** [comment]
@gungfujoe I have done some testing, and for me the `.navbar` class is not added to the `ul` but to the block `nav` wrapper several layers up. If I updated your custom CSS to reflect this as `.navbar ul li` then the styles are applied in the editor as expected:

<img width="1091" alt="Screenshot 2023-09-05 at 12 24 37 PM" src="https://github.com/WordPress/gutenberg/assets/3629020/72d218bf-1e19-4648-80ef-319b9c78885f">

This is the updated CSS that I used:

```css
.navbar ul li a { color: var(--wp--preset--color--base); height: auto; background: var(--wp--preset--color--custom-darker-red); font-weight: bold; border: 1px solid var(--wp--preset--color--contrast); padding: 0.1em 0.6em; white-space: nowrap; } .navbar ul li a:visited { color: var(--wp--preset--color--tertiary); background: var(--wp--preset--color--custom-darker-red); } .navbar ul li a:hover { color: var(--wp--preset--color--primary); background: var(--wp--preset--color--contrast); text-decoration: none; } .navbar ul li.current_page_item a, .navbar 
 ul li.current_page_item a:visited , .navbar ul li.current_page_item a:hover { color: var(--wp--preset--color--base); height: auto; background: var(--wp--preset--color--primary); } .navbar ul li.current_page_item a:before { content: "\00BB \0020"; } .navbar ul li.current_page_item a:after { content: "\0020 \00AB"; }
```
