### ISSUE TITLE
Navigation block with no defined block gap doesn't render properly in the editor

### ISSUE THREAD

**Issue by properlypurple** [WordPress/gutenberg#54994]
### Description

If a theme defines a navigation block without any block gap defined, it should inherit the default block gap, and render that in the editor and the frontend. Since Gutenberg 16.7.0, the gap doesn't render in the editor.

### Step-by-step reproduction instructions

1. Start with a fresh site on the 2023 theme, without the Gutenberg plugin
2. Go to `Appearance > Editor`, and observe the navigation
3. Install and activate Gutenberg 16.7. 
4. Go back to `Appearance > Editor` and observe the navigation.

### Screenshots, screen recording, code snippet

In versions before 16.7.0, this css is being applied to the navigation in the editor
```css
.wp-block-navigation .wp-block-page-list, .wp-block-navigation__container, .wp-block-navigation__responsive-close, .wp-block-navigation__responsive-container, .wp-block-navigation__responsive-container-content, .wp-block-navigation__responsive-dialog {
  gap: inherit;
}
``` 
And
```css
.editor-styles-wrapper {
  --wp--style--block-gap: 1.5rem;
}
```
These are not present in Gutenberg 16.7.0. The frontend is unaffected in both cases.

Screenshot with Gutnberg 16.6
![image](https://github.com/WordPress/gutenberg/assets/40858144/00272c85-b8fb-4ec8-85c9-c8fe46b304b2)

Screenshot with Gutenberg 16.7
![image](https://github.com/WordPress/gutenberg/assets/40858144/a70e2b71-95ea-4e3d-8da9-7f80ba1db21a)

----------------------

Please note that this is not observable if the theme specifies a custom block gap for the navigation block like this
```
<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right"},"style":{"spacing":{"blockGap":"1.5rem"}}} /-->
```

### Environment info

- WP 6.3.1
- Gutenberg 16.7.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
