### ISSUE TITLE
.

### ISSUE THREAD

**Issue by emdashftw** [WordPress/gutenberg#55318]
.

**Comment by jeflopodev** [comment]
I can confirm the problem with my navigation in the header was an specifity problem (my bad). I added more specific declarations for my selectors, and voila, it was working again.

But I modified the query pagination selectors too. Because I thought that If I wanted to hide the page number I should had been hidding the entire block (makes more sense), and not only the `& .page-numbers` classes as I was doing. I also tried to solve the problem by adding more specificity.

So I went From:

```css
@media screen and (max-width: 599px) {
    & .page-numbers {
        display: none;
    }
}
```

To:

```css
@media screen and (max-width: 599px) {
    main nav.wp-block-query-pagination div.wp-block-query-pagination-numbers {
        display: none;
    }
}
```

Seems that the display property for the class `.wp-block-query-pagination-numbers` is computed/comes from the user-agent stylesheet.

![image](https://github.com/WordPress/gutenberg/assets/679512/7b785b5e-e35e-44df-900c-dbc1a16bb89b)

My understanding is that I should be able to easily override that `display: block` with simpler CSS declarations (with less specificity), since it is not compared against other CSS declarations.

![image](https://github.com/WordPress/gutenberg/assets/679512/a241c76f-1c92-4d7c-8b74-24e3cc667a0c)

460px viewport and the page numbers are still displayed

```php
function my_theme_enqueue_styles() {
    wp_enqueue_style( 'my_theme_style', get_stylesheet_uri() );
}
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
```

I tried enqueuing the `style.css` file and adding the CSS only there, and then it works. So it only doesn't work when applying the CSS through `styles.blocks.core/query-pagination-numbers.css`
