### ISSUE TITLE
`wp-scripts build` doesn't minify CSS that was `@import`

### ISSUE THREAD

**Issue by cawa-93** [WordPress/gutenberg#55885]
### Description

When building, part of the CSS is imported from another file. The CSS at the entry point is minified and processed with prefixes. However, the imported CSS is inserted "as is" without minification and prefix processing.

### Step-by-step reproduction instructions

Create `external.css` with 
```css
.external {
    /* Comment */
    appearance: none;
}
```

Create `entry.css` with 
```css
@import "external.css";

.entry {
    /* Comment  */
    appearance: none;
}
```

In `package.json` add `browserslist` property:
```json
{
  "browserslist": [
    "ff 10"
  ],
}
```

In project root add `webpack.config.js`:
```js
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
const path = require( 'path' );

module.exports = {
    ...defaultConfig,
    mode: 'production',
    entry: 'path/to/entry.css',
};
```

Run `wp-scripts build`

After that you should find `build/main.css` folder in project root.

**Expected `main.css` content**

```css
.external{-moz-appearance:none;appearance:none}
.entry{-moz-appearance:none;appearance:none}

/* or */
.entry,.external{-webkit-appearance:none;appearance:none}
```

**Actual `main.css` content**

```css
.external {
    /* Comment */
    appearance: none;
}

.entry{-moz-appearance:none;appearance:none}
```

### Environment info

@wordpress/scripts: 26.16.0,

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes
