### ISSUE TITLE
Cover: Auto light/dark styles not applied to button elements

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#58004]
I would expect that the auto `is-light` and `is-dark` styles applied to content within light and dark cover blocks, would also apply to button elements within, ensuring that those too are nicely visible. This would work the same way as the text color works, where the style is applied if there is no local override on the button itself. 

### Visual 
In the recording below, I am invoking the light/dark styles by changing the overlay color. The text is switching between white and black, but the button is not. The button does not have any styles applied directly to it:

https://github.com/WordPress/gutenberg/assets/1813435/98f6db95-0802-4406-bb2b-20422e7eba18

**Comment by ghost** [comment]
I am able to reproduce what you're experiencing. I would like to give this bug a try. Thanks.

**Comment by ghost** [comment]
How about we add button color and button text color options so you can choose the colors just like heading, overlay, and text? I think it has better control than auto.

**Comment by richtabor** [comment]
> How about we add button color and button text color options so you can choose the colors just like heading, overlay, and text? I think it has better control than auto.

Well, a button isn't always in a cover block. I think it'd be best if the auto-application that is applied to text, also covers the button. You can still adjust it per normal use afterwards too.

**Comment by ghost** [comment]
What if other users don't want auto-apply but have full controls?

**Comment by richtabor** [comment]
If the auto-application of color happens on the text, because it's detecting a light or dark color overlay, then it should also be applied on the button — that way you can actually see it.

**Comment by ghost** [comment]
Just light or dark, no other colors, then it should auto applies to button?

**Comment by richtabor** [comment]
Just like it does for the text already, yes.

**Comment by ghost** [comment]
Light or dark with the same amount applies to the button. I will work on it. Thanks.

**Comment by cbirdsong** [comment]
There needs to be a holistic color scheme system that these classes can be a part of. In the themes I develop, we use a bunch of intermediary variables when setting color values, like text color, link color and button color. Those get light and dark values defined based on the current color scheme, so it looks something like this:

_Codepen demo: https://codepen.io/cbirdsong/pen/abMyXdN?editors=0100_
```scss
// Definition of variables

body,
.is-light,
.has-white-background-color {
	--text-color: black;
	--background-color: white;
	--link-color: blue;
	--link-color-shifted: purple; // an active state
	--button-color: navy;
	--button-color-inverse: white; // the accompanying text color, checked for contrast
	--button-color-shifted: black;
	--button-color-inverse-shifted: skyblue;
}

.is-dark,
.has-black-background-color {
	--text-color: white;
	--background-color: black;
	--link-color: cyan;
	--link-color-shifted: magenta;
	--button-color: skyblue;
	--button-color-inverse: black;
	--button-color-shifted: white;
	--button-color-inverse-shifted: navy;
}

.has-dark-green-background-color {
	--background-color: darkgreen;
}

.has-pink-background-color {
	--background-color: pink;
}

// Application of variables

body,
.is-dark,
.is-light {
	color: var(--text-color);

	a {
		color: var(--link-color);

		&:focus,
		&:hover {
			color: var(--link-color-shifted);
		}
	}

	button {
		color: var(--button-color-inverse);
		background-color: var(--button-color);
		border-color: var(--button-color);

		&:hover,
		&:active {
			color: var(--button-color-inverse-shifted);
			background-color: var(--button-color-shifted);
			border-color: var(--button-color-shifted);
		}
	}
}
.has-background {
	background-color: var(--background-color);
}
```

This allows for the color scheme of a page section to change freely while also making it easy to override any particular value within it.
