### ISSUE TITLE
Font-size values (normal & huge) defined in theme.json conflict with default editor styles 

### ISSUE THREAD

**Issue by lunule** [WordPress/gutenberg#59701]
### Description

If you're using font sizes in theme.json with the slugs `normal` and/or `huge`, the specified values get overwritten in the admin by default editor styles.

A setup in theme.json like this don't work in the admin:

``` js
{
	"version": 2,
	"settings": {
		"typography": {
			"fluid": true,
			"fontSizes": [
				{
					"fluid": {
						"min": ".888rem",
						"max": "1rem"
					},
					"name": "Normal",
					"size": "1rem",
					"slug": "normal"
				},
				{
					"fluid": {
						"min": "1.333rem",
						"max": "1.777rem"
					},
					"name": "Huge",
					"size": "3rem",
					"slug": "huge"
				}								
			]
		}
	}
}
```

... because the following default editor styles overwrite the correct settings:

``` css
.editor-styles-wrapper {
    --wp--preset--font-size--normal: 16px;
    --wp--preset--font-size--huge: 42px;
}
```

### Step-by-step reproduction instructions

1. Set up a blank FSE theme
2. Define 2 custom font sizes in theme.json with the slugs `normal` and `huge`, with `size` values any other than the following:
   - `16px` for `normal`
   - `42px` for `huge`
3. Create a new page, and add some Lorem Ipsum text - then select a paragraph and change the font-size to `huge`.

You'll see that the font-size value applied doesn't match the values defined in `theme.json`.   

### Environment info

- WP 6.4.3 - Gutenberg plugin not active, blank theme
- OS: Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ramonjd** [comment]
Thanks for filing this issue.

Has this bug been fixed already? 🤔 

I tested in Gutenberg trunk, and also WordPress 6.5-beta3-57723-src without any plugins installed, and couldn't reproduce.

https://github.com/WordPress/gutenberg/assets/6458278/5216c43d-6f00-437f-8a8c-105ae7bc2f52

**Comment by lunule** [comment]
Hey @ramonjd , thanks for your quick reply.

In your video, I think you're using block styles.
The reported issue is different, it's about the font size values defined in the `theme.json` file's `typography` > `fontSizes` section.

**Comment by lunule** [comment]
Hey @ramonjd , thanks for your quick reply.

In your video, I think you're using block styles.
The reported issue is different, it's about the font size values defined in the `theme.json` file's `typography` > `fontSizes` section.

The below gif displays how these font sizes get displayed in the editor sidebar.

![theme-json-typography-fontsizes](https://github.com/WordPress/gutenberg/assets/190486/d38eb7ae-14a5-4bfb-8550-c9af0f381196)

The main issue here, as far as I see, is that this overwrite breaks the fluid typography feature enabled in the `theme.json` file as well.

I used a hotfix in the editor stylesheet, overwriting the style pushed by the default editor style with the font size values used in `theme.json`, but 
- this seems going against the DRY principle
- fluid typo is still broken by these editor stylesheet styles for the two font sizes (`normal` and `huge`).

The hotfix looks like this:

``` css
.editor-styles-wrapper,
:root {
    --wp--preset--font-size--normal: 1rem;
    --wp--preset--font-size--huge: 1.777rem;

    @media ( max-width: 768px ) {
	    --wp--preset--font-size--normal: .888rem;
	    --wp--preset--font-size--huge: 1.333rem;    	
    }

    @media ( min-width: 1601px ) {
	    --wp--preset--font-size--normal: 1rem;
	    --wp--preset--font-size--huge: 1.7777rem;     	
    }    
}
```

A permanent fix would be providing a way to disable specific default editor styles, like the one reported here.

**Comment by ramonjd** [comment]
> In your video, I think you're using block styles.
> The reported issue is different, it's about the font size values defined in the theme.json file's typography > fontSizes section.

Oh sorry, I forgot to mention I was using the theme.json font size presets mentioned in this issue's description, and was just applying those sizes at the block level yes. 

May I ask, have you tried testing in WordPress 6.5 beta or with the latest Gutenberg version? I only ask because the issue cites 

> WP 6.4.3 - Gutenberg plugin not active, blank theme

But there was a pretty major bug fix that was merged since 6.4, that might be related:

- https://github.com/WordPress/gutenberg/pull/58422

**Comment by lunule** [comment]
Hey @ramonjd ,

Thanks - I'm totally overwhelmed with a theme project now, but I'll reply as soon as I have some spare time, on 18th Monday at the latest.

**Comment by carolinan** [comment]
I can confirm that this has been fixed in 6.5. The font size in theme.json is used, even when it matches an existing CSS variable.

Normal and huge are legacy font sizes that used to be part of the default preset, but were renamed. They are output in the editor and front for backward compatibility.

**Comment by ramonjd** [comment]
Thanks for confirming @carolinan 

I'll close this issue as fixed.

@lunule if you can still reproduce in WordPress 6.5 or with the latest Gutenberg version, please feel free to reopen. 👍🏻

**Comment by iamtakashi** [comment]
Possible regression. The `huge` size went back to `42px`  for me in the editor with Gutenberg trunk. The size is correct on the front of the site.

**Comment by t-hamano** [comment]
I was also able to reproduce this problem with the latest Gutenberg.

I used the theme.json below and tested it in the site editor.

<details><summary>theme.json</summary>

```json
{
	"version": 2,
	"settings": {
		"typography": {
			"fluid": true,
			"fontSizes": [
				{
					"fluid": {
						"min": ".888rem",
						"max": "1rem"
					},
					"name": "Normal",
					"size": "1rem",
					"slug": "normal"
				},
				{
					"fluid": {
						"min": "1.333rem",
						"max": "1.777rem"
					},
					"name": "Huge",
					"size": "3rem",
					"slug": "huge"
				}
			]
		}
	}
}
```
</details> 

## WP6.5 RC4

The `body` element outputs the correct user-defined CSS variables. At the same time, a CSS variable with the default font size is output via the selector `:where(.editor-styles-wrapper)`, but this does not cause any problems as it is overridden.

![wp6 5](https://github.com/WordPress/gutenberg/assets/54422211/f2b35622-6562-404d-b9c4-894f1f0ea2d3)

## Latest Gutenberg

In the latest version of Gutenberg, this style relationship is reversed.

![image](https://github.com/WordPress/gutenberg/assets/54422211/9b9fbf86-3fa0-4b37-b782-8812717bc383)

![image](https://github.com/WordPress/gutenberg/assets/54422211/a9a8a25d-6baa-4461-a359-4c123149a2c7)

**Comment by ramonjd** [comment]
It's because of this change:

- https://github.com/WordPress/gutenberg/pull/42084

Specifically https://github.com/WordPress/gutenberg/pull/42084/files#diff-b03597cc3da199e5aa5a94950e8241135904853e7c3b82d758e42744878afae7R46

I'm not sure what to do here.

The `:where(.editor-styles-wrapper)` rules are defaults that persist for backwards compatibility.

https://github.com/WordPress/gutenberg/blob/ae904142f1c4c47c3d83ecc698f9e71da769bf1d/packages/block-library/src/editor.scss#L69-L69

But they conflict with a progressive change, that is, using `:root` for CSS custom properties.

Also, `block-library` is a curious place for these styles. Not so curious when we see that they were [added in 2021](https://github.com/WordPress/gutenberg/pull/37381) (Gutenberg 12.2/WordPress 5.9)

Since Gutenberg only supports the last 2 versions of WordPress, should we consider deleting these styles as a solution to this issue?

**Comment by t-hamano** [comment]
> Since Gutenberg only supports the last 2 versions of WordPress, should we consider deleting these styles as a solution to this issue?

I think these styles are meant to support older WordPress versions that don't use Gutenberg, so I'm concerned that these styles can't be removed.

However, on the editor side, these styles seem to exist in duplicate:

- [packages/block-library/src/common.scss](https://github.com/WordPress/gutenberg/blob/ae904142f1c4c47c3d83ecc698f9e71da769bf1d/packages/block-library/src/common.scss#L11-L14): `:root` selector is used
- [packages/block-library/src/editor.scss](https://github.com/WordPress/gutenberg/blob/ae904142f1c4c47c3d83ecc698f9e71da769bf1d/packages/block-library/src/editor.scss#L70-L71): `:where(.editor-styles-wrapper)` selector is used

I'm not that knowledgeable, but I think it might be possible to delete these styles defined in `editor.scss` 🤔

![font-sizes](https://github.com/WordPress/gutenberg/assets/54422211/a9a31856-16a4-4b14-8980-cf9f0a7f3008)

A similar issue has been reported in #56293, but @oandregal mentions this issue in detail in [this comment](https://github.com/WordPress/gutenberg/issues/56293#issuecomment-1827719483), so maybe he knows something about it 🙏

**Comment by lunule** [comment]
@ramonjd 

> The `:where(.editor-styles-wrapper)` rules are defaults that persist for backwards compatibility.

In this case, wouldn't it be a workable strategy to inject these rules in a version-dependent way, e.g. for versions below v6.4 or similar?

Even better, it would be great if 
- developers had a filter or an `add_support` rule to use to enable/disable these forced styles in the theme's `functions.php` file, or
- a similar "switch" to use in the `theme.json` file

... where, as we're talking about a feature that exists solely for backwards compatibility, the default state of the "switch" would be **_off_** (rules not added to any of the predefined stylesheets) - then theme authors developing with backwards compatibility in mind could simply enable the feature.

(Basically, my main main concern with this issue is the _forced nature_ of the inclusion of CSS presets with preset names that'll most probably be used by theme authors in the development process.)

**Comment by ramonjd** [comment]
> (Basically, my main main concern with this issue is the forced nature of the inclusion of CSS presets with preset names that'll most probably be used by theme authors in the development process.)

I agree, this is regrettable, but I think I might have found a couple of workable alternatives:

1. We move `.editor-styles-wrapper` to the HTML tag in the [iframe component](https://github.com/WordPress/gutenberg/blob/1655ed0610408f8ec18760033429e4aea1380dfe/packages/block-editor/src/components/iframe/index.js#L153-L153). `:root` has higher specificity therefore any theme CSS properties underneath will take precedence. 
2. We insert the backwards compat CSS into the iframe via JS before any `:root` rules are output. 

I've tested number 1, as the second seems inherently sketchy:

- https://github.com/WordPress/gutenberg/pull/60398

**Comment by ramonjd** [comment]
> In this case, wouldn't it be a workable strategy to inject these rules in a version-dependent way, e.g. for versions below v6.4 or similar?

Its a good question. I'm not sure.

Backwards compatibility is an important consideration for any WordPress change, but there's no one way of maintaining (and breaking) it.

It's probably a naive idea, but I think it would be nice to put all backwards compat fixes in a little box, e.g., a hook to allow folks to disable some or all of them completely on their sites.

Nevertheless, there are other, less technical paths, such as education and communication:

> - Should be constrained as much as possible to a small surface area of the API.
> - Should be documented as clearly as possible to third-party developers using Dev Notes.

https://developer.wordpress.org/block-editor/contributors/code/backward-compatibility/

It's hard to judge when backwards compatibility is no longer possible or sustainable. Maybe in a few years we'll come back to this issue and decide 2028 is the time to delete the styles 😆

**Comment by ramonjd** [comment]
> I've tested number 1, as the second seems inherently sketchy:

Number 1 broke too many things.

The sketchy one seems to work and has a lighter footprint:

- https://github.com/WordPress/gutenberg/pull/60400

**Comment by t-hamano** [comment]
I looked into this issue by looking at what priority CSS variables have in each WordPress version. This problem occurred in WP6.4 and was resolved once in WP6.5. However, the issue has been reproduced in the latest Gutenberg.

The following shows how a CSS variable with a slug of `huge` is overridden if the font size is registered via theme.json.

## WP6.3.4

### ✅ Non-iframed Post Editor

```css
/* Inline style */
.editor-styles-wrapper {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
.editor-styles-wrapper {
    --wp--preset--font-size--huge: 42px;
}
body {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
:root {
    --wp--preset--font-size--huge: 42px;
}
```

### ✅ Iframed Post Editor and Site Editor

```css
/* Inline style */
.editor-styles-wrapper {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
/* editor.min.css */
.editor-styles-wrapper {
    --wp--preset--font-size--huge: 42px;
}
/* style.min.css */
:root {
    --wp--preset--font-size--huge: 42px;
}
```

## WP6.4.4

### ✅ Non-iframed Post Editor

```css
/* Inline style */
.editor-styles-wrapper {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
.editor-styles-wrapper {
    --wp--preset--font-size--huge: 42px;
}
body {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
:root {
    --wp--preset--font-size--huge: 42px;
}
```

### ❌ Iframed Post Editor and Site Editor

```css
/* editor.min.css */
.editor-styles-wrapper {
    --wp--preset--font-size--huge: 42px;
}
/* Inline style */
body {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
/* style.min.css */
:root {
    --wp--preset--font-size--huge: 42px;
}
```

## WP6.5.2

### ✅ Non-iframed Post Editor

```css
/* Inline style */
.editor-styles-wrapper {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
:where(.editor-styles-wrapper) {
    --wp--preset--font-size--huge: 42px;
}
body {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
:root {
    --wp--preset--font-size--huge: 42px;
}
```

### ✅ Iframed Post Editor and Site Editor

```css
/* Inline style */
body {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
/* editor.min.css */
:where(.editor-styles-wrapper) {
    --wp--preset--font-size--huge: 42px;
}
/* style.min.css */
:root {
    --wp--preset--font-size--huge: 42px;
}
```

## Latest Gutenberg plugin

### ❌ Iframed Post Editor and Site Editor

```css
/* editor.css */
:where(.editor-styles-wrapper) {
    --wp--preset--font-size--huge: 42px;
}
/* Inline style */
:root {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
/* style.css */
:root {
    --wp--preset--font-size--huge: 42px;
}
```


### ✅ Non-iframed Post Editor

```css
/* Inline style */
.editor-styles-wrapper {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
/* editor.css */
:where(.editor-styles-wrapper) {
    --wp--preset--font-size--huge: 42px;
}
:root {
    --wp--preset--font-size--huge: clamp(2rem, 2rem +((1vw - 0.48rem)* 1.923), 3rem);
}
/* style.css */
:root {
    --wp--preset--font-size--huge: 42px;
}
```

It's difficult to find out the root cause due to the complicated history, but `editor(.min).css` appears to be causing the problem in both WP6.4 and the latest Gutenberg. Additionally, `style(.min).css` with the same CSS variables is also loaded in the editor in all versions, so it appears that `editor(.min).css` can be safely deleted.

I would like to test if #60400 solves this problem.
