### ISSUE TITLE
Backwards compatibility issue with shadow defaultPresets

### ISSUE THREAD

**Issue by getdave** [WordPress/gutenberg#59989]
Trac ticket: https://core.trac.wordpress.org/ticket/60815

There may be an issue for  themes that have shadow presets with the same slug as the core presets as it changes the CSS output for the theme.

----

I see that it may break a shadow when the following conditions are met

````
appearanceTools: false
theme defined custom shadows
and they are defined with same slug as defaultPresets
````

Also, prior to 6.5 shadows are enabled for button block and in global styles only.
It seems to be very unlikely edge case and shouldn't have big impact on themes.

-----

> Meaning that `defaultPresets` are off by default and when appearanceTools is set to true, they are enabled, which makes existing themes that are using default presets to work as before.

`appearanceTools` is also `false` by default, so it's still a problem for themes that haven't configured either.

Before this change, with a theme that has custom `settings.shadow.presets` defined with matching slugs to those in the defailt lib/theme.json and `settings.shadow.defaultPresets` and `settings.appearanceTools` both undefined, you'll end up with different CSS that gets output to the page.

In the first case the default styles will be output and in the second case, the theme styles will be output.

Here's an example of what I'm talking about.

```jsonc
// Relevant parts of theme.json
{
  "settings": {
    // `appearanceTools` is not set
    "shadow": {
      // `defaultPresets` is not set
      "presets": [
        {
          "name": "Natural",
          "slug": "natural",
          "shadow": "2px 2px 3px #000"
        }
      ]
    }
  }
}
```

```css
/* Generated CSS before */
--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);
```

```css
/* Generated CSS after */
--wp--preset--shadow--natural: 2px 2px 3px #000;
```

It's because to the `settings.shadow.defaultPresets` being used as the value for `prevent_override` in `PRESETS_METADATA` in `WP_Theme_JSON`. The setting defines the behavior of matching slugs in the default and theme origins for presets in theme.json.

https://github.com/WordPress/gutenberg/blob/cdfd75183952ce7ae1ec78e673ac719e002d2de8/lib/class-wp-theme-json-gutenberg.php#L181

https://github.com/WordPress/gutenberg/blob/cdfd75183952ce7ae1ec78e673ac719e002d2de8/lib/class-wp-theme-json-gutenberg.php#L2868-L2876

I'm suggesting that we revert this for 6.5 (at least this line since it is the one causing the problems). Then we can use the theme.json version bump to opt-in to breaking changes like this.

I'm adding the theme.json version bump in #58409. So you'd just need to update the migration from that PR to make sure that existing themes are unaffected.

Hopefully that all makes sense. 😅

_Originally posted by @ajlende in https://github.com/WordPress/gutenberg/pull/58766#discussion_r1529243086_

**Comment by t-hamano** [comment]
WP6.5 enables shadow UI at the block level. I think one of the reasons why `defaultPresets` was changed to `false` is that there is no way to change default presets in classic themes that do not have `theme.json`. Therefore, I suspect that simply reverting #58766 or increasing the theme.json version will not be able to resolve the issue.

Is it possible to cover this backward compatibility issue in a Dev Note? I expect that the themes that will be affected will be very limited.

**Comment by getdave** [comment]
I'll defer to @ajlende and @madhusudhand.

**Comment by ajlende** [comment]
> I think one of the reasons why `defaultPresets` was changed to `false` is that there is no way to change default presets in classic themes that do not have theme.json

What was the status of shadows in classic themes prior to this change?

This is what I see now on Twenty Twenty.

<img width="1280" alt="image" src="https://github.com/WordPress/gutenberg/assets/5129775/70049cef-31e1-4e2a-be67-fe072821b012">

```css
body {
	--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);
	--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);
	--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);
	--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1),
		6px 6px rgba(0, 0, 0, 1);
	--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);
}
```

The only difference I see is that buttons can have shadows in classic themes when `defaultPresets` is `true` by default. I guess I don't understand why that is a problem?

<img width="1280" alt="image" src="https://github.com/WordPress/gutenberg/assets/5129775/4303d8b7-f6cd-4ed9-b759-41055cf68585">


```css
body {
	--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);
	--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);
	--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);
	--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1),
		6px 6px rgba(0, 0, 0, 1);
	--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);
}
```

If there's an issue with showing the shadow presets in classic themes, that can be handled in the UI instead of the theme.json for now.
