### ISSUE TITLE
wp-scripts: minification of CSS imports is done too early in the process

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#61112]
## What problem does this address?

CSS files that are imported are minified, but the minification happens to early.
Each imported file is minified, but there's a line break between each import in the resulting file.

This is an improvement of #56516.

Example: 

Content of global.css
```css
@import "_reset.css";
@import "_typography.css";
```

Result
```css
*,:after,:before{box-sizing:border-box}
:where(h1,h2,.has-large-font-size,.has-x-large-font-size,.has-xx-large-font-size){text-wrap:balance}
```

Expected result
```css
*,:after,:before{box-sizing:border-box}:where(h1,h2,.has-large-font-size,.has-x-large-font-size,.has-xx-large-font-size){text-wrap:balance}
```

## What is your proposed solution?

Adjust the webpack.config.js to use `postcss-import` before `cssnano`
