### ISSUE TITLE
Site Editor: Pages three pane view overlaps on certain screen sizes

### ISSUE THREAD

**Issue by ndiego** [WordPress/gutenberg#62104]
### Description

When accessing the Pages screen in the Site Editor on smaller screens, such as tablets, two panes overlap. See the video for a walkthrough.

### Step-by-step reproduction instructions

1. Use TT4 and the latest version of Gutenberg
2. Open the Site Editor and navigate to the Pages screen
3. Make the browser width smaller, either manually or using the inspector (like in the video)
4. Notice that the two panes overlap

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/4832319/b00bac8e-a058-4b48-8c31-89b6ea3ff765

### Environment info

- WordPress 6.5
- Gutenberg 18.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
Noting this is overall tracked here: https://github.com/WordPress/gutenberg/issues/60847

**Comment by aatanasovdev** [comment]
It appears we'll need to activate the mobile layout below 960px browser width (considered as `large` viewport) and probably reduce the width of the sidebar from 360px to 320px from 1280px to the mobile layout. Otherwise, the panes won't fit. 

Here is an example preview:

https://github.com/WordPress/gutenberg/assets/38669058/3ef88a9d-1758-4d68-8210-8316c2de9b5c

I tested reducing the size of the three panes, but this approach might cause other styling issues.

Please let me know what you think.

**Comment by aatanasovdev** [comment]
I'd like to discuss the expected result of this task. Reviewing https://github.com/WordPress/gutenberg/issues/60847, it seems that the second and third panes will be a scrollable area, which requires changing the markup (wrapping the content and the canvas). 

However, the Layout component is used by all Site Editor Data Views, which will require testing each of them. Considering that I'm not sure whether, in this task, we'll follow [the new responsive approach](https://github.com/WordPress/gutenberg/issues/60847) or a temporary solution should be implemented.

**Comment by stokesman** [comment]
> it seems that the second and third panes will be a scrollable area, which requires changing the markup (wrapping the content and the canvas).

It’s not necessarily the case the markup will have to change. <details><summary>Here’s a quick bit of CSS that allows for horizontal scrolling without markup changes and prevents the panes from overlapping. It can be pasted into styles in dev tools if anyone cares to experiment.</summary>
```css
.edit-site-layout__content {
    overflow: auto;
}

.interface-navigable-region.edit-site-layout__sidebar-region {
    position: sticky;
    left: 0;
    background: #1e1e1e;
}

.edit-site-layout__content {
    padding-inline: 0 16px;
}

.edit-site-layout__area,
.edit-site-layout__canvas-container {
    min-width: 320px;
    z-index: auto;
}

@media (min-width: 782px) {
    .edit-site-layout__canvas {
        width: 100%;
    }
}
```
