### ISSUE TITLE
Custom CSS for block with a block style variation is not rendered to the page.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#62415]
## What?
The custom CSS added in the custom CSS input of a block with a block style variation, for example, a Button with the 'outline' variation as in the Twenty Twenty-Four theme, is not rendered on the page. It seems to be ignored.

## Why?
To be able to add custom CSS to block variant.

## Context 
We found that this wasn't working because @beafialho was building a theme and trying to style the `:hover` state of the 'outline' variants button. The temporal solution we found was adding this CSS to the Button**s** CSS input.

```css
 .is-style-outline .wp-element-button:hover{
  border-bottom: 5px solid yellow!important;
  background-color: transparent!important;
}
```

## Expected
The CSS should be rendered as the rest of the CSS included in the CSS input.

## Screencast
In the screencast is possible to see how the 'outline' custom CSS is not added to the rendered page code.

[Screencast from 07-06-24 16:12:49.webm](https://github.com/WordPress/gutenberg/assets/1310626/8331d3f2-29da-4bc3-813d-3cb8393bfca4)
