### ISSUE TITLE
[Palette] - Multiple color selection with the same "color" attribute

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#62930]
### Description

Inside theme.json, I don't understand why palette entries are based on the key "color" and not "slug".
Declaring an identical "color" several times with a different name and slug poses a problem.
By changing the color, the selection is multiple when it should be unique.

The case in point is the declination of CSS variables for a dark mode that will be overwritten.
For example, if I want to be able to separate the colors that will be overwritten in dark mode from those that won't be.

#### For example : 
- standard variables that will be fixed and not overwritten in dark mode :
`blue-400`
`green-400`

- the variables that will be overwritten in dark mode with "light-mode-to-dark-mode" syntax :
`blue-400-to-green-400`
`green-400-to-blue-400`

**The default Gutenberg result is  :** 

```css
body {
    --wp--preset--color--blue-400: #5F8DFF;
    --wp--preset--color--green-400: #6add05;
    --wp--preset--color--blue-400-to-green-400: #5F8DFF;
    --wp--preset--color--green-400-to-blue-400: #6add05;
}
```

**and what I'd like to do after  :** 

```css
body.dark-mode {
    --wp--preset--color--blue-400-to-green-400: var(--wp--preset--color--green-400);
    --wp--preset--color--green-400-to-blue-400: var(--wp--preset--color--blue-400:);
}
```

Currently, for a hybrid theme, creating a /styles folder and duplicating the theme.json file with dark.json seems complicated. The theme.json file is already very long if you have to maintain several files on top of it.
And switching files from the front with a light/dark mode button doesn't seem possible.

If we can't declare several colors with the same "color" attribute, how do we go about giving the person administering the content (who isn't a developer or integrator) the option of using native gutenberg blocks (without using ACF blocks or any other solution) to define colors (background,color) that are supported in style.css for a dark mode variation ?

### Step-by-step reproduction instructions

1. In theme.json, add this declaration  : 
```json
"palette": [    
    {
        "name": "Bleu 400",
        "slug": "blue-400",
        "color": "#1547c3"
    },
    {
        "name": "Bleu 400 to Green 400",
        "slug": "blue-400-to-green-400",
        "color": "#1547c3"
    },
    {
        "name": "Green 400",
        "slug": "green-400",
        "color": "#6add05"
    },
    {
        "name": "Green 400 to Blue 400",
        "slug": "green-400-to-blue-400",
        "color": "#6add05"
    }
],
```
2. Inside admin, select a color

### Screenshots, screen recording, code snippet

[581b444c-24f0-4845-b9ba-a8d30f104512.webm](https://github.com/WordPress/gutenberg/assets/62699215/d262eea0-cd92-4ddb-a696-46b84602fa7d)

----------

![Screenshot_2](https://github.com/WordPress/gutenberg/assets/62699215/b3f7950c-255b-4d64-9111-dbe7210ee084)

### Environment info

- WP 6.5.5
- Custom theme (Hybrid) with theme.json
- Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by webexpr-dhenriet** [comment]
I'm currently able to make this system work by forcing an unlikely "color" example: "color": "#1547c3-6add05"

```json
{
  "name": "Bleu 400 to Green 400",
   "slug": "blue-400-to-green-400",
   "color": "#1547c3-6add05"
},
```

This results in the loss of the palette preview, but the slug is applied.
Then I have to redeclare the styles for the back office and front end.

**In admin style :**
```scss
$imp: unquote('!important');

.editor-styles-wrapper {

    .has-text-color {
        
        //== overwrite theme.json value "#1547c3-6add05" for .has-blue-400-to-green-400 
        &.has-blue-400-to-green-400 {
            color: var(--wp--preset--color--blue-400) $imp;
        }
    }
}
```

**In front end style :** 
```scss
$imp: unquote('!important');

//== overwrite theme.json value "#1547c3-6add05" for .has-blue-400-to-green-400 
body {
    --wp--preset--color--blue-400-to-green-400: #1547c3 #{$imp};
}
//== Dark mode 
@include color-mode(dark) {

    body {
        --wp--preset--color--blue-400-to-green-400: #6add05 #{$imp};
    }
}
```

I also have to redeclare body as I'm doing my dark mode from the `:root` scope and also add` !important,` as mentioned here 
https://github.com/WordPress/gutenberg/issues/62959

It works, but it's not a great system.
The behavior of palette items should be like a radio button: I click, I select and the others are deselected ?

![Screenshot_6](https://github.com/WordPress/gutenberg/assets/62699215/4b1fd1b9-5a91-4376-8a2b-2749f43e4f66)
![Screenshot_5](https://github.com/WordPress/gutenberg/assets/62699215/e3423e78-0a65-4840-8b92-d7403d9e489e)
![Screenshot_4](https://github.com/WordPress/gutenberg/assets/62699215/54200fab-a524-4e67-8219-b0212100e039)
![Screenshot_2](https://github.com/WordPress/gutenberg/assets/62699215/f0b9120a-aab8-433d-8277-96346fa2540b)
