### ISSUE TITLE
[Style] - Inline style !important and CSS variable scope

### ISSUE THREAD

**Issue by webexpr-dhenriet** [WordPress/gutenberg#62959]
Is there any reason to put a `!important` on all inline styles generated by theme.json ?

```css
.has-black-800-color {
    color: var(--wp--preset--color--black-800) !important;
}
```

this should be enough ? Would it be possible to remove `!important` ?

```css
.has-black-800-color {
    color: var(--wp--preset--color--black-800);
}
```
For CSS variables, why is the scope body and not :root ?
```css
body {
    --wp--preset--color--black: #000000;
}
```
Would it be possible to encapsulate them in :root ?
```css
:root {
    --wp--preset--color--black: #000000;
}
```
