### ISSUE TITLE
Horizontal margin overridden in root-level blocks

### ISSUE THREAD

**Issue by ciampo** [WordPress/gutenberg#63191]
https://github.com/WordPress/gutenberg/assets/1083581/d1ed6a87-a972-47d6-933c-f9fda39038c1

While interacting with spacing input controls for another task, I noticed a few unexpected behaviors:
<details><summary>Now resolved: Out of sync visualization</summary>

### Padding/margin colored overlays out of sync

The colored overlay shown around a block doesn't seem to reflect the value chosen in the control:

- It doesn't show initially, even when going from "None" to "1" (see in the video at 12 seconds)
- the overlay shows a padding being applied even when going back to "None" (see in the video at 20 seconds)
- in general, it looks like the overlay is off by 1 position with respect to the slider (see in the video between 20 and 30 seconds)
- When enabling custom values and changing the value to `0`, the overlay still shows a large padding (see in the video at 34 seconds)

</details>

### Horizontal margin does not get applied

When applying horizontal margin, I moved the slider but nothing happened to the selected block (see video at 1 minute and 9 seconds)

**Comment by ciampo** [comment]
cc @aaronrobertshaw @glendaviesnz @andrewserong who I know have worked on this area of the project before

**Comment by andrewserong** [comment]
Thanks for the ping! I'll just ping @noisysocks, too, since there was a change back in February (https://github.com/WordPress/gutenberg/pull/59227) that could be related.

**Comment by noisysocks** [comment]
Yeah these issues sound exactly like the ones I fixed in https://github.com/WordPress/gutenberg/pull/59227.

Running the latest trunk locally, I can't reproduce any of the overlay issues you've mentioned. Is there a step I'm missing? Or something about your environment? What browser are you using?

> When applying horizontal margin, I moved the slider but nothing happened to the selected block (see video at 1 minute and 9 seconds)

This one I can reproduce. It looks like the `margin-left` and `margin-right` values are being overridden by a CSS rule added by the parent block's layout.

Here's the rule in the site editor:

```css
.editor-styles-wrapper .wp-container-core-group-is-layout-203 > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
  max-width: 565px;
  margin-left: auto !important;
  margin-right: auto !important;
}
```

And here's the rule in the post editor:

```css
.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
  max-width: 620px;
  margin-left: auto !important;
  margin-right: auto !important;
}
```

It makes sense that the layout would add `margin-left: auto` and `margin-right: auto` to centre-align the blocks, but I'm not sure why they're marked `!important`, which overrides the margin that the user sets. Is this to do with a recent specificity change? I'm not very familiar with how the layout CSS works.
