### ISSUE TITLE
Post Editor: Editor canvas squashed by metabox in mobile/tablet view

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#63708]
### Description

Regression introduced by #63222

Per #63222, the selectors was changed as follows to fix background height and padding when the editor canvas is not an iframe:

```css
// From
.edit-post-layout.has-metaboxes .edit-post-visual-editor {
	flex: 1 0 auto;
	height: auto;
}

// To
.edit-post-visual-editor:not(.is-iframed) {
	flex: 1 0 auto;
	height: auto;
}
```

This approach works for the desktop view, but in mobile/tablet views the editor canvas is _always_ an iframe, so this style no longer applies and the canvas gets squashed when the meta box is present.

### Step-by-step reproduction instructions

- Install the Yoast SEO plugin. This plugin injects a meta box with lots of content into the post editor.
- Switch to tablet/mobile view.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/264fca90-c495-43f1-b779-de1f6cb1b7f3

### Environment info

- WordPress Verson: 6.6
- Gutenberg version: 18.8.0 (Can be reproduced even after disabling)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes
