### ISSUE TITLE
Differing CSS specificity between Non-Iframed Editor and Front end

### ISSUE THREAD

**Issue by wongjn** [WordPress/gutenberg#63925]
### Description

With non-iframed block editor, specificity of top-level element selectors are different relative to other selectors. I believe this is due to the `.editor-style-wrapper` prefix.

### Step-by-step reproduction instructions

1. Create theme using code snippets below.
2. Activate the created theme.
3. Edit a page or post.
4. Add a Heading block, with default attributes and any text content.
5. Save.
6. Observe the font size.
7. Top right 3-dots menu → Preferences → Enable "Custom Fields".
8. Hit *Show and Reload Page* button (to enable the non-iframe editor).
9. Observe the heading block size is different to step 5.
10. On the front end, observe the heading block size is the same as 5.

##### `theme.json`
```json
{
  "$schema": "https://schemas.wp.org/wp/6.6/theme.json",
  "version": 3,
  "styles": {
    "blocks": {
      "core/heading": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--large)"
        }
      }
    },
    "elements": {
      "heading": {
        "typography": {
          "fontSize": "inherit"
        }
      }
    }
  }
}
```

##### `style.css`
```css
/*
Theme Name: Test
*/
```

##### `templates/index.html`

```html
<!-- wp:post-content /-->
```

#### Observed behavior

<table>
<thead>
<tr>
<th>&nbsp;</th>
<th>Front end</th>
<th>Iframe editor</th>
<th>Non-iframe editor</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">Screenshot</th>
<td>

![image](https://github.com/user-attachments/assets/b5d60206-8bf8-447c-922b-0abc6541de91)

</td>
<td>

![image](https://github.com/user-attachments/assets/dee00014-85a9-40af-8b46-25feca143037)

</td>
<td>

![image](https://github.com/user-attachments/assets/f33603a3-18ea-4bee-84f8-f3fc76197fe2)

</td>
</tr>
<tr>
<th scope="row">CSS</th>

<td>

```css
:root :where(.wp-block-heading) {
  font-size: var(--wp--preset--font-size--large);
}
h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
}
```

</td>
<td>

```css
:root :where(.wp-block-heading) {
  font-size: var(--wp--preset--font-size--large);
}
h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
}
```

</td>
<td>

```css
.editor-styles-wrapper h1,
.editor-styles-wrapper h2,
.editor-styles-wrapper h3
.editor-styles-wrapper h4,
.editor-styles-wrapper h5,
.editor-styles-wrapper h6 {
  font-size: inherit;
}
.editor-styles-wrapper :where(.wp-block-heading) {
  font-size: var(--wp--preset--font-size--large);
}
```

</td>
</tr>
<th scope="row">Analysis</th>
<td>

✅ `core/heading` block styles override top-level element `heading` styles.

</td>
<td>

✅ `core/heading` block styles override top-level element `heading` styles.

</td>
<td>

❌ Top-level element `heading` styles override `core/heading` block styles. Element `heading` styles have specificity (0, 1, 1) whereas `core/heading` block styles have (0, 1, 0).

</td>
</tbody>
</table>

### Environment info

- WordPress 6.6.1
- Custom theme (see code snippets)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes
