### ISSUE TITLE
Pseudo-element selectors in `styles.**.css` property no longer work in 6.6 compared to 6.5

### ISSUE THREAD

**Issue by wongjn** [WordPress/gutenberg#63932]
### Description

With the [CSS specificity change in WordPress 6.6](https://make.wordpress.org/core/2024/06/21/wordpress-6-6-css-specificity/), most rules are now wrapped in `:root :where()`. However, pseudo-elements like `::before` and `::after` cannot be wrapped in `:where()`.

This means `theme.json` like this:

```json
{
  "$schema": "https://schemas.wp.org/wp/6.6/theme.json",
  "version": 3,
  "styles": {
    "elements": {
      "h1": {
        "css": "&::before { content: 'Foo' }"
      }
    }
  }
}
```
Produces:

```css
:root :where(h1::before) {
  content: 'Foo';
}
```
Which is invalid CSS and causes the CSS rule to no longer apply.

### Step-by-step reproduction instructions

1. Install fresh WordPress.
2. Add an entry for `core/heading` in `styles.blocks` in `twentytwentyfour/theme.json`:
   ```diff
    },
   +"core/heading": {
   +  "css": "&::before { content: 'Foo' }"
   +},
    "core/image": {
   ```
3. See the invalid inline CSS gets added to the webpage:
   ```css
   :root :where(.wp-block-heading::before ){content: 'Foo'}
   ```
   Compare this to the equivalent in 6.5.5:
   ```css
   .wp-block-heading::before {content: 'Foo'}
   ```
   Which is valid CSS.

### Environment info

- WordPress 6.6.1
- Twenty Twenty-Four 1.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes
