### ISSUE TITLE
Make elements font options referenceable

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/gutenberg#64443]
## What problem does this address?

Should WordPress make element font options referenceable? 

Currently, there's no way to reference, for example, the font family selection for the website's headings because the values of this option are printed in selector-value CSS.

![image](https://github.com/user-attachments/assets/b1d5ce6c-00c1-4fc8-b81d-aa9b622fb7a3)

Example of the  current `theme.json` config:
```json
{
    "styles": {
        "elements": {
            "heading": {
                "typography": {
                    "fontStyle": "normal",
                    "fontWeight": "400",
                    "fontFamily": "var:preset|font-family|abel"
                }
            }
        }
    }
}
```

This config is printed like this in CSS:
```css
h1, h2, h3, h4, h5, h6{
     font-family: var(--wp--preset--font-family--abel);
}
```
This works to set the font family of headings but cannot be referenced in any other part of the styles. Let's say you have a theme and you want to reference the font selection of the heading. That's currently impossible. The only current workaround is using fonts with a 'positional' slug (for example, 'heading-font') and style variations. This way, when the variation is applied, the 'heading font' will change. But style variations are a pre-defined part of a theme, and they cannot be created using the editor (without plugins such as Create Block Theme). 
We could solve this limitation by using the elements font selection as 'positional' variables for fonts. This will allow users to change an entire theme by installing a font using the font library and selecting it in the elements font panel.

## What is your proposed solution?
WordPress should make element font options referenceable. Should it print the CSS variables with the element's font family styles? I imagine that WordPress could print CSS variables for the font options in `theme.json.` This way, the element's font options can be referenced and reused across the site and theme. Font switching will be possible without pre-defined theme style variations that cannot be created in the editor.

Example of how the printed CSS variable could look:
```css
--wp--element--headings--font-family: Abel, sans-serif;
--wp--element--headings--font-style: Italic;
```

The resulting CSS for headings could look like this: 
```css
h1, h2, h3, h4, h5, h6{
     font-family: var(--wp--element--headings--font-family);
     font-style: var(--wp--element--headings--font-style);
}
```

Custom CSS of the theme could reuse these variables:
```css
.my-custom-block{
    font-family: var(--wp--element--headings--font-family);
}
```

Other parts of theme JSON could reference this setting, too:
```json
{
    "styles": {
        "blocks": {
            "core/quote": {
				"typography": {
					"fontFamily": "var(--wp--element--headings--font-family)",
					"fontStyle": "var:element|headings|font-style"
				}
			}
        }
    }
}

```
