### ISSUE TITLE
Hybrid theme editor group and cover block padding does not match published page padding

### ISSUE THREAD

**Issue by andreawetzel** [WordPress/gutenberg#65130]
### Description

Extra left and right padding in the group and cover blocks in the editor on our hybrid theme. Because the editor view is out of sync from the live site experience it may cause page editors to add or remove space when this is not needed. 

### Step-by-step reproduction instructions

In a hybrid theme with theme.json using `"useRootPaddingAwareAlignments": true` and left and right padding set to 1.5 rem under styles/spacing/padding/

1. add a Group block or Cover block
2. Set the block to align none 
3. Add a background color
4. Add a paragraph inside
5. Observe extra left and right padding in the block editor view
6. Publish the page and see that the left and right padding is removed on the live page view

### Screenshots, screen recording, code snippet

![before-Screenshot 2024-09-06 at 2 33 51 PM](https://github.com/user-attachments/assets/f9cb093c-65c8-4eb1-8b7f-1af293002869)

_Screenshot of editor view on left and published live page view on the right. Blocks with added padding are highlighted with a red outline_

For our theme, I found that I could remove the extra editor padding with the following CSS via `add_editor_style()`:

```css
.wp-block-group-is-layout-constrained.has-global-padding,
.wp-block-cover-is-layout-constrained.has-global-padding {
	padding-right: 0;
	padding-left: 0;
}
```

Testing the spacing issue in a Full Site Editing theme such as Twenty TwentyFour, I found that the following CSS is used in the editor to remove this extra padding, but it is not applied to the editor for our  hybrid theme:

```css
.editor-styles-wrapper .has-global-padding :where(:not(.alignfull.is-layout-flow) > .has-global-padding:not(.wp-block-block, .editor-styles-wrapper .alignfull)) {
  padding-right: 0;
  padding-left: 0;
}
```

### Environment info

WP 6.6.1
No Gutenberg Plugin
Chrome
Mac Desktop

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes
