### ISSUE TITLE
Styles: Elements and pseudo elements use different box sizing.

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/gutenberg#6513]
## Issue Overview

`edit-post/assets/stylesheets/main.scss` sets the box-sizing property with this rule set.

```scss
.gutenberg {
	* {
		box-sizing: border-box;
	}
}
```

This causes elements to have `border-box` sizing while pseudo elements (`::before, ::after`) use the browser default `content-box`. 

## Steps to Reproduce (for bugs)

See gif below.

1. Start a new post in Gutenberg
2. Add a block (list block used in gif below)
3. In the inspector, select a pseudo element `editor-block-list__block-edit::before` to inspect styles. Box sizing will show content-box.
4. Select the pseudo elements parent `editor-block-list__block-edit` to inspect styles. Box sizing will show border-box.

## Expected Behavior

A consistent sizing method would be preferable.

## Current Behavior

Sizing method is inconsistent.

## Possible Solution

Two possibilities

```scss
.gutenberg {
	 box-sizing: border-box;

	&:before, &:after,
	*, *:before, *:after {
		box-sizing: inherit;
	}
}
```

or

```scss
.gutenberg {
	*, *:before, *:after {
		box-sizing: border-box;
	}
}
```

Either change will require visual regression testing.

## Screenshots / Video

![box-sizing](https://user-images.githubusercontent.com/519727/39456722-0047fa0a-4d2c-11e8-8d54-babdb92dbc35.gif)

## Todos
- [ ] Tests
- [ ] Documentation
