### ISSUE TITLE
Make it more obvious in the site editor whether a template / template part is modified or reading from disk

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#66646]
Especially in larger WordPress installations we almost never want templates / template parts to get modified in a production environment. Because when you do so you get locked out of code updates. And the templates/template-parts are usually managed in Git. 

Currently it is almost impossible without manually checking every single templates action dropdown menu whether the template has bee modified or not. 

It would be great to add a new field to the DataView that indicates whether the template has been modified. This field doesn't need to be enabled by default. But it should be one of the options of the DataView.

**Comment by fabiankaegy** [comment]
There is a hacky CSS was of achieving this which is basically doing:

```css
[aria-label="Templates"] .dataviews-view-grid__card:has(input[type="checkbox"][aria-disabled="false"]) {
	border: 5px solid red !important;
}
```

Which uses the fact that any modified templates have the checkbox enabled where as unmodified has the checkbox disabled. But an actual native solution would be much preferred :)
