### ISSUE TITLE
FontSize conflict between link and social-links blocks

### ISSUE THREAD

**Issue by CallMarl** [WordPress/gutenberg#67133]
### Description

Customize the font size of link into global settings override the custome size defined into social-links block. Caused by the order of css call, the instruction below should include the native block class `.wp-block-social-link-anchor`:

```css
a:where(:not(.wp-element-button)) {
    font-size: var(--wp--preset--font-size--small);
}
```
to:
```css
a:where(:not(.wp-element-button, .wp-block-social-link-anchor)) {
    font-size: var(--wp--preset--font-size--small);
}
```
I tried into developper tool and  this fix work.

### Step-by-step reproduction instructions

Into `theme.json` set `styles.elements.link.typography.fontSize` with custom size like:

```json
{
    "styles": {
        "elements": {
            "link": {
                "typography": {
                    "fontSize": "var(--wp--preset--font-size--small)"
                }
	    }
        }
    }
}
```

Then try to define into wordpress gutenberg editor custom size into the social links editor.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/21ac3d9c-3abc-4651-a2f2-b7d44da3842c)

### Environment info

- Wordpress 6.7
- [Gutenberg (native) ](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/)
- Theme twentytwentyfour

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure
