### ISSUE TITLE
Editor: When a mouse cursor is over "Add block" line, scrolling stops working

### ISSUE THREAD

**Issue by goodpenguins** [WordPress/gutenberg#67182]
### Description

When scrolling content in the editor with mouse wheel, when the mouse cursor is over the "Add Block" line, even if it has not yet appeared, scrolling stops. Any direction.

### Step-by-step reproduction instructions

Create a page/post with content 2-3 screens high. Start scrolling up and down the page. You will probably catch it. Or just place your mouse pointer between the blocks where the "Add Block" line should be and try scrolling.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/fc3a32ca-1af3-470e-b994-698c1968685a)

### Environment info

WP 6.7
Gutenberg 19.7.0
Theme: Twenty Twenty-Five
OS: Windows 11
Browser: MS Edge

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by im3dabasia** [comment]
Hey @goodpenguins, I was able to reproduce this issue. Good find! This is happening because of the following CSS:

```css
.components-popover.block-editor-block-popover__inbetween .is-with-inserter, .components-popover.block-editor-block-popover__inbetween .is-with-inserter *{
    pointer-events: all
}
```
