### ISSUE TITLE
Social Icons (Links) and Cover blocks include unused CSS in most cases

### ISSUE THREAD

**Issue by westonruter** [WordPress/gutenberg#69613]
### Description

I have a Social Links block which has quite a few items in it:

![Image](https://github.com/user-attachments/assets/9836a2bd-6043-40ed-b362-2e0000a8be69)

Nevertheless, when doing a CSS coverage report, only 26.3% of the CSS in the stylesheet is being used. I think there is an opportunity here to reduce the amount of CSS on the page by inlining the styles for the specific services that are in the block. For example, if I have Facebook then it could add:

```css
:where(.wp-block-social-links:not(.is-style-logos-only)) .wp-social-link-facebook {
    background-color: #0866ff;
    color: #fff
}
:where(.wp-block-social-links.is-style-logos-only) .wp-social-link-facebook {
    color: #0866ff
}
```

Otherwise, this could be emitted entirely. Furthermore, only the `is-style-logos-only` styles could be included if that block style is being used.

CSS in question:

https://github.com/WordPress/gutenberg/blob/22c55f658ed349254bd146c15bc4150c59f68d3d/packages/block-library/src/social-links/style.scss#L109-L131

For reference, the Social Links block is the 4th largest amount of CSS for a block:

```
 19126 ./cover/style.min.css
 16449 ./navigation/style.min.css
 15927 ./gallery/style.min.css
 11740 ./social-links/style.min.css
  6808 ./image/style.min.css
  3855 ./table/style.min.css
  2645 ./media-text/style.min.css
  2391 ./search/style.min.css
  2367 ./comments/style.min.css
  2253 ./button/style.min.css
```

<details><summary>Remaining block style sizes</summary>

```
  1991 ./post-comments-form/style.min.css
  1837 ./latest-posts/style.min.css
  1833 ./post-featured-image/style.min.css
  1596 ./embed/style.min.css
  1566 ./columns/style.min.css
  1521 ./post-template/style.min.css
  1343 ./buttons/style.min.css
  1302 ./latest-comments/style.min.css
  1135 ./pullquote/style.min.css
  1025 ./comments-pagination/style.min.css
  1015 ./heading/style.min.css
   764 ./query-pagination/style.min.css
   699 ./quote/style.min.css
   661 ./calendar/style.min.css
   655 ./paragraph/style.min.css
   654 ./post-navigation-link/style.min.css
   652 ./rss/style.min.css
   642 ./file/style.min.css
   568 ./tag-cloud/style.min.css
   492 ./quote/theme.min.css
   457 ./text-columns/style.min.css
   453 ./site-logo/style.min.css
   437 ./separator/theme.min.css
   432 ./comment-template/style.min.css
   405 ./separator/style.min.css
   404 ./page-list/style.min.css
   358 ./post-author/style.min.css
   339 ./post-excerpt/style.min.css
   319 ./navigation-link/style.min.css
   293 ./categories/style.min.css
   287 ./footnotes/style.min.css
   281 ./read-more/style.min.css
   279 ./video/style.min.css
   267 ./pullquote/theme.min.css
   261 ./post-title/style.min.css
   232 ./table/theme.min.css
   232 ./site-title/style.min.css
   216 ./code/style.min.css
   196 ./term-description/style.min.css
   188 ./image/theme.min.css
   176 ./video/theme.min.css
   176 ./embed/theme.min.css
   176 ./audio/theme.min.css
   156 ./audio/style.min.css
   138 ./avatar/style.min.css
   135 ./preformatted/style.min.css
   126 ./search/theme.min.css
   124 ./comment-content/style.min.css
   123 ./gallery/theme.min.css
   117 ./post-terms/style.min.css
   117 ./group/style.min.css
   116 ./code/theme.min.css
   105 ./template-part/theme.min.css
   101 ./verse/style.min.css
    95 ./list/style.min.css
    89 ./archives/style.min.css
    81 ./details/style.min.css
    62 ./group/theme.min.css
    54 ./post-author-biography/style.min.css
    52 ./comment-author-name/style.min.css
    51 ./comment-reply-link/style.min.css
    50 ./comment-edit-link/style.min.css
    49 ./post-author-name/style.min.css
    45 ./site-tagline/style.min.css
    45 ./comment-date/style.min.css
    44 ./query-total/style.min.css
    44 ./query-title/style.min.css
    42 ./post-date/style.min.css
    41 ./post-content/style.min.css
    41 ./loginout/style.min.css
    28 ./spacer/style.min.css
```

List collected via:

```bash
wc -c $(find . -name '*.css' | grep  min | grep -v rtl | grep -v editor) | sort -nr
```

</details> 

From taking a quick look at the Cover block it's a similar situation, where there are a lot of opacity rules for specific block configurations like:

```css
.wp-block-cover-image.has-background-dim.has-background-dim-10 .wp-block-cover__background,.wp-block-cover-image.has-background-dim.has-background-dim-10 .wp-block-cover__gradient-background,.wp-block-cover-image.has-background-dim.has-background-dim-10:not(.has-background-gradient):before,.wp-block-cover.has-background-dim.has-background-dim-10 .wp-block-cover__background,.wp-block-cover.has-background-dim.has-background-dim-10 .wp-block-cover__gradient-background,.wp-block-cover.has-background-dim.has-background-dim-10:not(.has-background-gradient):before{
  opacity:.1;
}
.wp-block-cover .wp-block-cover__background.has-background-dim.has-background-dim-10,.wp-block-cover .wp-block-cover__gradient-background.has-background-dim.has-background-dim-10,.wp-block-cover-image .wp-block-cover__background.has-background-dim.has-background-dim-10,.wp-block-cover-image .wp-block-cover__gradient-background.has-background-dim.has-background-dim-10{
  opacity:.1;
}
```

No need to include this rule if the 0.1 opacity is not being used by any Cover block on the page.

### Step-by-step reproduction instructions

1. Add a Social Links block to a page.
2. Add a couple links
3. Do a CSS coverage report on the frontend (e.g. in Chrome DevTools)
4. Observe the vast majority of style rules are unused.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure
