### ISSUE TITLE
Navigation block submenu toggle button should inherit link styles

### ISSUE THREAD

**Issue by coreyworrell** [WordPress/gutenberg#69884]
### Description

If you have a navigation block, enable Click to Open submenu option, and then you have a global style or a block style applied, the button should inherit the styles. Example:

*styles/blocks/navigation-1.json*

```json
{
  "$schema": "https://schemas.wp.org/trunk/theme.json",
  "version": 3,
  "title": "Primary",
  "slug": "primary",
  "blockTypes": ["core/navigation"],
  "styles": {
    "elements": {
      "link": {
        "spacing": {
          "padding": {
            "left": ".5em",
            "right": ".5em"
          }
        },
        ":hover": {
          "color": {
            "background": "blue"
          },
        }
      }
    }
  }
}
```

The submenu toggle button element does not change background color on hover. Applying the same values to a `elements.button` property doesn't work either.

Writing custom CSS, like

```json
"styles": {
    "css": "& .wp-block-navigation-item__content:hover { background-color: blue; }"
}
```

gets output as 

```css
:root :where(.wp-block-navigation.is-style-primary--1 .wp-block-navigation-item__content:hover) {
  background-color: blue;
}
```

which just gets overridden by `wp-includes/blocks/navigation/style.min.css`:

```css
button.wp-block-navigation-item__content {
  background-color: initial;
  /* truncated rest... */
}
```

### Step-by-step reproduction instructions

1. Insert navigation block.
2. Insert submenu with child links.
3. Toggle on Submenus "Open on click" setting.
4. Apply global style in theme.json or custom style in block JSON to links

### Environment info

- WordPress 6.7.2

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure
