### ISSUE TITLE
Calendar block: Colors do not change between global styles and `theme.json`

### ISSUE THREAD

**Issue by shimotmk** [WordPress/gutenberg#69896]
### Description

Even if you set colors in the calendar block using global styles and theme.json, the colors of td and caption do not change.

### Step-by-step reproduction instructions

1. Change the default text of the calendar block in the site editor
2. Place the calendar block on a post or static page
3. You can see that the colors set in 1 do not change for td and caption
4. The colors of td and caption do not change even if you set the following values ​​in theme.json
```json
"core/calendar": {
	"color": {
		"text": "#da1bd1"
	}
},
```

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/e91e35c5-653f-4038-b11a-e078c9e74dac

### PR that seems to be related

td and caption have been deleted in the following commit: https://github.com/WordPress/gutenberg/pull/42029/commits/35cab080c622c6269284097e4f129f0ceebcca5c

At this time, it says that td and caption can be overwritten with theme.json and global styles, but at the moment the colors of th and caption do not change.
https://github.com/WordPress/gutenberg/pull/42029#pullrequestreview-1113227231

### Environment info

- WordPress Version 6.7.2
- Gutenberg Version 20.7.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Infinite-Null** [comment]
Hey @shimotmk,
I was able to reproduce the issue:

## Screencast:

https://github.com/user-attachments/assets/51f89520-1dc5-47fb-85e1-688663ae1041

## Expected:
Color to be applied like below:

![Image](https://github.com/user-attachments/assets/f7e709f1-974d-4f88-8f0f-110c94fadbee)

**Comment by asmodeyoriginal** [comment]
I think I found a solution to your issue. Check it out here [click](https://javierlopez.eu/captha/)

**Comment by t-hamano** [comment]
Thanks for the report.

I don't remember exactly, but I think in #42029 there was a very complicated discussion to address issues around backwards compatibility.

To anyone working on this issue, please make sure you understand #42029 and are careful not to affect backwards compatibility.

**Comment by Vrishabhsk** [comment]
Hi @t-hamano @shimotmk 
- I have added the PR for the fix : https://github.com/WordPress/gutenberg/pull/70184

Let me know your thoughts on this. Thanks

**Comment by t-hamano** [comment]
After further investigating this issue, we found that it was a regression that occurred in WordPress 6.6.

Let's take a caption as an example to explain what happens when we apply colors via the global styles.

### WordPress 6.5

![Image](https://github.com/user-attachments/assets/6d4e0322-3d22-4e1c-9846-eafdd023dedb)

```css
// CSS output by the global styles
// Specificity: 0,1,1
.wp-block-calendar table {
    color: var(--wp--preset--color--vivid-red);
}

// Calendar block default style
// Specificity: 0,1,1
.wp-block-calendar table:where(:not(.has-text-color)) {
    color: #40464d;
}
```

As you can see, both selectors have specificity `0,1,1`. The styles from the global styles that are output later take precedence, which is the expected behavior.

### WordPress 6.6

![Image](https://github.com/user-attachments/assets/8d0fbf04-e193-47d6-8cdc-24bce5b116a8)

```css
// Calendar block default style
// Specificity: 0,1,1
.wp-block-calendar table:where(:not(.has-text-color)) {
    color: #40464d;
}

// CSS output by the global styles
// Specificity: 0,1,0
:root :where(.wp-block-calendar table, .wp-block-calendar th) {
    color: var(--wp--preset--color--vivid-red);
}
```

The specificity of the CSS output by the global styles has been reduced from `0.1.1` to `0,1,0`, so the default styles for the Calendar block take precedence.

---

Given this root cause, let's consider whether #70184 is the ideal approach.
