### ISSUE TITLE
Editor always assumes align: full is 100% width

### ISSUE THREAD

**Issue by chrisvanpatten** [WordPress/gutenberg#7374]
In Gutenberg, if a block is set to `align: full`, the editor applies CSS in other areas that assumes the "full" width will always be 100%. If your `align: full` is less, the editor display is wonky.

This causes issues for themes that might want the "full" value to not be fully edge-to-edge in the browser. (In our case, we are aligning full width to the width of a page container element.)

**To Reproduce**
Set your `align: full` width a specific value less than 100%:

```css
body.gutenberg-editor-page .editor-block-list__block[data-align="full"] {
    max-width: 1000px;
}
```

**Screenshots**
![_untitled____ _mindful_ _wordpress](https://user-images.githubusercontent.com/1231306/41612025-06b44f66-73c8-11e8-8fa8-d963eea6faf5.png)
