### ISSUE TITLE
Inline styles in paragraph when setting custom sizes in the editor

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#7765]
**Describe the bug**
I still see this inline styles when adding Custom Size to paragraph in the editor.

**To Reproduce**
- Add new paragraph block.
- Set Custom Size to `L`.
- It adds inline style `style="font-size: 36px;"`.

**Expected behavior**
What it should do is add class `is-large-text` so that it would respect what theme wants.

In Core block these happens to be the same font sizes:)

```css
p {
	&.is-small-text {
		font-size: 14px;
	}

	&.is-regular-text {
		font-size: 16px;
	}

	&.is-large-text {
		font-size: 36px;
	}

	&.is-larger-text {
		font-size: 48px;
	}
}
```

cc: @mtias @jasmussen
