### ISSUE TITLE
Body classes based on page template

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#7810]
**Is your feature request related to a problem? Please describe.**
Page templates can have varying widths on the front end. In order to reflect that on the editor side it would be good to know which page template is currently selected.

**Describe the solution you'd like**
Add page template slug to `<body>` classes on the Gutenberg page and update it automatically when template is changed in page attributes.

So you could do something like:

```css
body.gutenberg-editor-page.page-template-two-sidebars .edit-post-visual-editor .editor-post-title__block,
body.gutenberg-editor-page.page-template-two-sidebars .edit-post-visual-editor .editor-block-list__block {
    max-width: 600px;
}

body.gutenberg-editor-page.page-template-full-width .edit-post-visual-editor .editor-post-title__block,
body.gutenberg-editor-page.page-template-full-width .edit-post-visual-editor .editor-block-list__block {
    max-width: 100%;
}
```

**Describe alternatives you've considered**
Alternatively you can let page template comments contain something like this:

```
/**
 * Template Name: Full width page
 * Gutenberg Width: 1280px
 */
```

and handle it automatically, making it easily possible to change the width when the template gets major changes in the child theme or when creating custom ones.

But at the end of the day body classes wouldn't hurt, could prove useful for other use cases as well.

**Note**
It's already possible to do this for post types for example, since they are already included in the body class:

```css
body.gutenberg-editor-page.post-type-post .edit-post-visual-editor .editor-post-title__block,
body.gutenberg-editor-page.post-type-post .edit-post-visual-editor .editor-block-list__block {
    max-width: 1024px;
}

body.gutenberg-editor-page.post-type-portfolio .edit-post-visual-editor .editor-post-title__block,
body.gutenberg-editor-page.post-type-portfolio .edit-post-visual-editor .editor-block-list__block {
    max-width: 800px;
}
```

**Question**
Is CSS like even the recommended way to alter the editor width or is there anything else available/planned?
