### ISSUE TITLE
Block styles in the editor.scss

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#8094]
There are [Quote styles in the editor](https://github.com/WordPress/gutenberg/blob/b7633877b4db245be686510013bbe15015b8ae77/core-blocks/quote/editor.scss).

```css
.wp-block-quote {
	margin: 0;

	cite {
		display: block;
		font-size: $default-font-size;
	}
}
```

I don't see any reason why they are there. @jasmussen Can you perhaps take a look.
