### ISSUE TITLE
Crashed block z-index problem with add new block button

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#8868]
**Describe the bug**

If a block crashes it shows a crashed block warning. There is some z-index issue with this and the inline 'add new block' button:

![another_post___ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/43990028-462b6090-9d4d-11e8-82c7-876864b33b5b.jpg)

**To Reproduce**
1. In dev console enter `wp.blocks.registerBlockType( 'myplugin/mr-crashy', { title: 'Mr. Crashy', category: 'common', icon: 'warning', edit() { throw new Error(); }, save() { return ''; } } );`
2. Add Mr Crashy block
3. Note that the inline block add buttons appear under the crash warning

**Expected behavior**
The inline block buttons should appear over the crash warning

There's also a slight overlap in the crash warning that can be fixed by changing `block-list/style.scss` with:

```css
.editor-block-list__layout .editor-block-list__block {
	&.has-warning {
		min-height: ( $block-padding + $block-spacing ) * 2;
	}
```
