### ISSUE TITLE
Fixing captions on resized image broke responsiveness

### ISSUE THREAD

**Issue by KittMedia** [WordPress/gutenberg#8931]
In the current version 3.5.0 of Gutenberg and since several previous versions (at least since #6496) resized images are not responsive and would break the complete layout if they’re too big.

A working fix on my site seems to be working fine on my devices in `core-blocks/image/style.scss`:

```scss
	&.is-resized {
		display: table;
		width: auto;

		figcaption {
			caption-side: bottom;
			display: table-caption;
		}
	}
```

**To Reproduce**
1. Add an image block with an image.
2. Resize the image to any size, e. g. 600 px width.
3. Publish the post and visit it on your smartphone.

**Expected behavior**
Even if bigger the image should be resized to don’t be larger than the layout’s width nor should they be cropped.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 12

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 12
 - Browser: Safari
 - Version: 12
